### ISSUE TITLE
Set up some metrics for benchmarking database activity and performance

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/job-server#1034]
Prior to #1033, we should set up metrics to help establish the current activity characteristics of the database. Some questions:

* What is generating most of the write activity?
* When is it happening? Is it smooth, spikey, etc?
* What are the typical response times and variance?
* Are there particular writes that create more locks?
* Is the total amount of write activity beyond the reasonable amount we could expect of sqlite? If not, then something else funny is going on, and we should investigate.

Our options are:

* File logging. Ensure we are logging HTTP activity, and database activity (this can be done via Django). Ensure log rotation is working correctly
* Datadog. We like it. It might take a while to set up, but probably worth it to get easier correlations of activity, detailed insights about resources, etc

**Comment by ghickman** [comment]
I've enabled [pg_stat_statements](https://www.postgresql.org/docs/13/pgstatstatements.html) in the database which is now collecting stats.
