### ISSUE TITLE
Set up permissions for viewing and editing application forms

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/job-server#1135]
As an admin user, I want more granular permission level for other admin user, so that we can control who has access to add comments or view application form submissions.

## Permissions

- View and add comments
- View-only

## To do

- [ ] Admin can apply permissions to other admins
- [ ] View and add comments permission
- [ ] View-only permission
- [ ] Apply permissions to existing staff users
- [ ] Only allow "admin" users to view form submissions (currently all staff can view form submissions)

**Comment by sebbacon** [comment]
Closing this as have captured in a Google Doc for Catherine to assess and recreate as necessary
