### ISSUE TITLE
Public view of projects and their associated application form

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/job-server#1137]
As an admin user, I want to link onboarding applications to Job Server projects, so that I can see the application for each project.

As a user, I want to be able to see the application for each Job Server project, so that I can confirm the projects match the applications. (Information Governance, scrutiny) 

This should contain:

- The application form tied to a particular project
- All fields agreed to be publicly visible
- Show missing fields (as the application was submitted before the current process)
- Highlight fields which need to be updated
- Give the public confidence that their private data is being used responsibly and for valuable purposes

**Comment by ghickman** [comment]
This is blocked on deciding which parts of an application to show publicly, which drives how we'll show an application to the public.
