### ISSUE TITLE
Order applications in the staff area by status

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/job-server#1141]
As an admin user, I want to see all open applications grouped by the next action and ordered by date, so I know what the most urgent things to do next are.

Linked to https://github.com/opensafely-core/job-server/issues/1136

**Comment by ghickman** [comment]
We can easily add a filter by this but for grouping we'll have to add something new.  Lets start with a filter and see how @amirmehrkar gets on with it before we build the grouping part.
