### ISSUE TITLE
Update developer documentation following PostgreSQL migration

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/job-server#1189]
Following the sqlite3 to PostgreSQL change, there are now extra steps to get job-server running locally outside of Docker, over merely having sqlite3 installed.

I think you need to:

1. Have a PostgreSQL instance running, either on your own machine outside of Docker or via `docker-compose up db`.
2. Have `DATABASE_URL=postgres://user:pass@localhost:5432/jobserver` set when running Django-specific commands.
    * If you have a `.env` loading tool that loads on entering directory, and add this variable to `.env`, then this variable will be set.
    * Otherwise, if you're only using `just` to load environment variables, `just run` will work fine with the `DATABASE_URL` added to `.env`. However, you would need to add `DATABASE_URL` to the environment for any non-`just` commands such as `python manage.py migrate` (e.g. by prefixing the command with the variable, `DATABASE_URL=… python manage.py migrate`).

None of this is currently documented: anyone running job-server themselves will have to figure this out.

**Comment by ghickman** [comment]
Does this cover everything you need? https://github.com/opensafely-core/job-server/pull/1186 😁
