### ISSUE TITLE
Make Files on L4 More Obvious

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1217]
When we load the L4 files page (eg https://jobs.opensafely.org/nhsei/prostate-cancer-psa-testing/prostate_cancer_psa_testing_2021/files/tpp/) from outside an appropriate L4 environment we get a network error toast notification, and an error about being unable to load the files, with a mostly blank page otherwise:

![](https://p198.p4.n0.cdn.getcloudapp.com/items/bLudeP4D/bf60d09d-2ccb-48e8-8841-7dc5456a1202.jpg?v=1a45a744b0734eb206b23e35d3fefad5)

Since we should never be able to access an L4 URL from outside an L4 environment we can shortcut the process in the Django view and not render the outputs viewer at all, saving it some error handling.

Something like 
```
try:
    requests.head(backend.level_4_url)
except requests.exceptions.ConnectionError:
    l4_unreachable = True
```

should be good enough.

**Comment by ghickman** [comment]
The Django server doesn't have access to the Level 4 URLs, so we'll need ot handle this in the SPA.

**Comment by lucyb** [comment]
This won't be needed once we move to Airlock.
