### ISSUE TITLE
Co-pilot notifications

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/job-server#1240]
Related to #1208, there are a couple of other co-pilot related things that would be useful to be notified about.

1.  A list of submitted applications that need approval
2. A list of approved applications that have yet to start. This is useful to catch projects that may have not been assigned a co-pilot.

These would most likely be useful for @brianmackenna

**Comment by tomodwyer** [comment]
We don't think this is a co-pilot responsibility anymore. Let us know if you think that it is still required.

**Comment by brianmackenna** [comment]
1. not a co-pilot
1. I think this happens now. @acagreen17 will know for def!

Ok to close though!

**Comment by acagreen17** [comment]
There's not a list of approved applications that have yet to start as such, but can find this into on jobserver via the dashboards and by filtering.
