### ISSUE TITLE
Modify ProjectMembership Roles in the Staff Area

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1293]
Currently we can't modify the roles a user has for a project in the Staff Area (outside when we add them to a project).  It's possible to go to the project in the main section of the site and do it there but let's make it easy to do in the Staff Area too.

**Comment by bloodearnest** [comment]
I think part of specific problem here is that ProjectDeveloper and ProjectCollaborator are disjoint, but folks just get ProjectDeveloper by default. I think there's never a reason for ProjectDeveloper not to also be a ProjectCollaborator?
