### ISSUE TITLE
Present long filter lists as dropdowns

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-core/job-server#1298]
On the [logs](https://jobs.opensafely.org/event-log) page, the filter lists for User and Workspaces are very long and makes the page very long and hard to use - can they be presented as dropdowns?

![image](https://user-images.githubusercontent.com/24392156/141456692-562b5813-8419-4c80-a38a-84b715428b55.png)

**Comment by HelenCEBM** [comment]
This is great thanks @ghickman - just spotted a small problem, the `status` filter lists workspaces not statuses:
![image](https://user-images.githubusercontent.com/24392156/152408310-2650df76-5549-410c-a864-45255234d130.png)

**Comment by ghickman** [comment]
@HelenCEBM – oops!  Will roll a fix out asap.
