### ISSUE TITLE
Show application status on Applications page

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-core/job-server#1305]
https://jobs.opensafely.org/applications/
It would be good to see "Incomplete" "Submitted" "Approved" etc against each application here: 
![image](https://user-images.githubusercontent.com/24392156/141813148-1cb3a9e1-3654-4d6c-84f1-afd6e91995e7.png)

Also having an option to delete an (incomplete) application could be helpful if people have started more than they need.

**Comment by ghickman** [comment]
I've pulled the delete part out into #1306.
