### ISSUE TITLE
Allow Applicants to Delete Applications

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1306]
We should allow applicants the ability to delete their applications _unsubmitted_ applications.  Of course we don't want to lose any data by accident so lets add an `is_deleted` flag and only soft delete them.  We can hide soft deleted applications from the user view, but probably want to display them in the Staff Area with a strikethrough to show they're deleted.

Spun out from #1305

**Comment by sebbacon** [comment]
I'm not 100% sold on the idea it's worth the extra UI fiddle (albeit minor) to preserve a deleted form. It feels like a pretty permanent thing, given people can (will be able to?) already keep draft applications?
