### ISSUE TITLE
Add url functionality to application form

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/job-server#1309]
It would be good to add url functionality

> As an applicant, I want to add a url to the application, to hyperlink to a paper that supports my rationale for conducting the survey

> As a reviewer, I want to click on a url, to take me directly to the location referenced by a researcher.

I think for the moment we could make it clear in documentation that applicants should copy and paste the full url into the application but screenshots to current applications where a url would've been useful/was intended for when we get to it

- In this example the applicant is intending to put ini a url
 ![image](https://user-images.githubusercontent.com/40460354/142011204-0ff5d9ca-20c1-438a-8f16-7e64f6f23242.png)

- In this example I am reviewing this application and I have no idea where xu et al is located 
 ![image](https://user-images.githubusercontent.com/40460354/142011279-7bff205a-3ebf-42a6-bef4-81883f5099da.png)

- sheer laziness but as a reviewer I have to copy and past this link
 ![image](https://user-images.githubusercontent.com/40460354/142011614-83e12fac-7bcd-459c-a171-fe34b992ab58.png)

**Comment by brianmackenna** [comment]
Is it added?

**Comment by tomodwyer** [comment]
We aren't doing any work to improve the applications part of the Jobs site at the moment. We will continue to investigate any bugs or make content changes, but won't add new features.

As for the documentation, we could update that either on the Jobs site, or in the OpenSAFELY Docs – not sure if you have an opinion on where would be better?

**Comment by brianmackenna** [comment]
np - I just want to ensure this type of thing is captured for when we do come to do work on it! Where is the best place to do this?

It used to be issues but I don't think it is anymore?

**Comment by tomodwyer** [comment]
Probably best to talk to Catherine if it's specific work to be added in to the pipeline. We will be running back through all the `amir` tagged issues (open and closed ones) when the new application process is chosen, and making sure those ideas are captured.
