### ISSUE TITLE
Define a Process for Removing Users

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1322]
We have traditionally removed users from the platform by removing their membership to the `opensafely` GitHub Org which blocks them from logging into the service.  This let us punt on deciding how to deal with deleting users.

With the removal of this requirement in #1297 we need to have a think how we'll deal with it.  We don't want to lose User data, eg `George ran Job abc7` is still useful data, but we also need to stop a user from using the site.

**Comment by tomodwyer** [comment]
This is now an IG Team responsibility. There are buttons for removing roles in the Staff Area.
