### ISSUE TITLE
Document new user permissioning

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1341]
Our medium-term goal is to automate new user provisioning and permissioning. However, in the short term, several steps require manual intervention by admins (interacting with users, establishing the permissions they should have, giving them pointers to what they can/can't do, assigning permissions, and perhaps more). And people are routinely a bit confused about the states they find themselves in ([example](https://ebmdatalab.slack.com/archives/C01UJLWNZJT/p1642074477015500))

Specifically, some common actions for users:

* [ ] [initial onboarding/set up of a newly registered user](https://docs.google.com/document/d/1jie8Fy9SP1PWiDEZJA-oq22AARVFszIFQie7DcjqmlA/edit)
* [ ] setting permissions for an existing user to run jobs in an existing workspace. Also see [this thread](https://ebmdatalab.slack.com/archives/C31D62X5X/p1639584453037700)
* [ ] configuing output viewing for an existing user (mostly legacy now but still a semi-common task)
* [ ] configuring output releasing for an existing user (this is slightly different to the previous task!)
* [ ] [fixing missing permissions on older Projects](https://docs.google.com/document/d/11ZWqLCW00HX6TtTusZJpy9uHrDCQXLdhDp5xMdt2wiU/edit#)

The person who picks up this ticket should start by briefly reviewing all the linked discussions (more in the thread below, too), then having a chat with George to check their understanding.  It probably makes sense to turn these into a series of commonly-asked questions. 

Any ensuing notes should be turned into a series of FAQs or similar topic-based narrative. 

Intially, we should draft these in a Google Doc. When we're pretty happy with them, we integrate the text directly into  job-server, displaying a list group of them in the Staff Area index page below the current list group in the left-hand nav.

There may also be some useful background narrative generated as part of this research - planned future directions, etc. This should intially go into a google doc, and then probably turned into a series of issues (coordinate with Seb)

**Comment by sebbacon** [comment]
Given osrelease also leans on permissions, I think [this thread](https://ebmdatalab.slack.com/archives/C010SJ89SA3/p1636397490110700) is also relevant for consideration

**Comment by sebbacon** [comment]
Two things to clarify:

* who / what role currently does the new user permissioning?
* how about _new project_ permissioning for _existing users_? Does that need its own section in the docs?

**Comment by sebbacon** [comment]
Also see discussion [here](https://ebmdatalab.slack.com/archives/C63UXGB8E/p1638351987241800) (Slack)

**Comment by sebbacon** [comment]
And [here's another thread with people seeking clarification](https://ebmdatalab.slack.com/archives/C63UXGB8E/p1643197755241600?thread_ts=1643197660.241200&cid=C63UXGB8E)

**Comment by sebbacon** [comment]
@tomodwyer 

FYI co-pilots have been maintaining their own documentation, which I just found here 
https://docs.google.com/document/d/1odediydaSJI2dwFwqgGO9lDR0HjTaCn9O9IGXAatiCc/edit

**Comment by sebbacon** [comment]
I'm also throwing in [this Slack thread](https://ebmdatalab.slack.com/archives/C31D62X5X/p1645092519085189) (where I learned about that) for the record - I don't think you necessarily need to read it @tomodwyer.

**Comment by tomodwyer** [comment]
Another [Slack thread](https://ebmdatalab.slack.com/archives/C028EJH752A/p1646304712043319) on permissions to create new organisations.

**Comment by sebbacon** [comment]
Note that when this is done, we should link to the published version(s) [from our Policy](https://docs.opensafely.org/developer-access-policy/)

**Comment by sebbacon** [comment]
A [slack thread](https://bennettoxford.slack.com/archives/C028EJH752A/p1649322846236629) not about permissions, but about transferring existing repos to the opensafely org

**Comment by ghickman** [comment]
Moved to the ideas bucket.
