### ISSUE TITLE
Deleting Applications from Testing

### ISSUE THREAD

**Issue by amirmehrkar** [opensafely-core/job-server#1357]
Please delete all **Amir Mehrkar** applications

**EXCEPT** the latest one https://jobs.opensafely.org/staff/applications/63c1/

Im sorry for the mess!

**Comment by iaindillingham** [comment]
I don't think we can delete applications from job-server -- at least, not through the staff area. We can, however, reject them and provide a status comment. Is this preferred, @ghickman? If so, then I'll reject these applications with the following status comment:

> This application was for testing.

**Comment by ghickman** [comment]
@iaindillingham – no, I think for these we just remove them from the database via the manage.py shell.

**Comment by iaindillingham** [comment]
Done! For reference:

```python
from jobserver.hash_utils import unhash
Application.objects.filter(created_by__username="amirmehrkar").exclude(pk=unhash("63c1")).delete()
```
