### ISSUE TITLE
Changes to application form

### ISSUE THREAD

**Issue by amirmehrkar** [opensafely-core/job-server#1362]
1. need add > 1 email addresses to study purpose page https://jobs.opensafely.org/applications/63c1/page/study-purpose/ 
![image](https://user-images.githubusercontent.com/20584513/143458559-b666c7de-c394-4c7c-91f1-8255c5b963a9.png)

2. for now the legal basis page can be HIDDEN (may be helpful in future)
![image](https://user-images.githubusercontent.com/20584513/143459478-d2422346-d58c-4a05-9222-8685bab5db71.png)

3. For research section please remove mandatory component for "If using ONS-CIS, ONS ethics approval reference"
![image](https://user-images.githubusercontent.com/20584513/143473261-42252097-b338-4dce-928b-dcccb2015114.png)

4. for study data section please remove mandatory component if applicant selects "YES" 
![image](https://user-images.githubusercontent.com/20584513/143473416-666ea735-d826-4818-84a2-8f6df308397a.png)

5. in the confirmation view https://jobs.opensafely.org/applications/63c1/confirmation/

we need to make the email address that applicants need to send some documentation to easily visible otherwise they will forget. and it's a pain for them to log back in to the change screens to find it. 

Three places need this: the Research/Service evaluation and Researcher details sections.

**Research bit**
Can you add: "**You will need to email any supporting documents to applications@opensafely.org.**"

** service eval bit** 
Can you plz add: **You will need to email any supporting documents to applications@opensafely.org.**

**The sponsor must also email applications@opensafely.org confirming they have read the Study Information and Study Purpose sections, and that they support the application.**

![image](https://user-images.githubusercontent.com/20584513/143477321-e82ebe4e-fab5-49f6-9361-0a392f46b41b.png)

**Researcher bit.** 

Can you add somewhere inside the box at the bottom: "**Remember: For each researcher who is not named on the "List of Accredited Researchers" document, which is found at the bottom of this page, please email evidence of them completing safe researcher training to applications@opensafely.org.**"

![image](https://user-images.githubusercontent.com/20584513/143477623-bcef9525-bed2-4005-85c9-96aaa2a174fe.png)

**Comment by ghickman** [comment]
Triaged into:
* https://github.com/opensafely-core/job-server/issues/1366
* https://github.com/opensafely-core/job-server/issues/1367
* https://github.com/opensafely-core/job-server/issues/1368
* https://github.com/opensafely-core/job-server/issues/1369
