### ISSUE TITLE
Add a Back Button

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1373]
Helen wrote:

> Make a Back button so that users can go back to edit or copy their previous answers.

**Comment by ghickman** [comment]
@tomodwyer – IIRC we had a back button in early designs but eschewed it in favour of the browser's back button?

**Comment by tomodwyer** [comment]
I don't love having a back button, but if we do think it will benefit the users, I would suggest we follow the [Gov.uk design system](https://github.com/opensafely-core/job-server/pull/1398) and add a back button at the top of the page.

Potentially we want to user test if people notice and/or use this.
