### ISSUE TITLE
Explain how the form works

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1374]
In #1303 Helen wrote:

> Make it clear that after completing all of the sections you will be able to review and amend your answers - this is great but I didn't know it was going to come up while I was completing the form.

and

> Make sure it's clear to the user that progress will be saved as the form is being completed and point out/link to where they can get back to it later.

I've grouped these as I think they're the same issue.

@tomodwyer – How have you tackled this before?  Would it make sense for the form to have an extra page at the start explaining the above points? Or should we add something on each page?

**Comment by tomodwyer** [comment]
I think the best option is you suggested page at the start. It could be something like: **"Before you start"**. We could then list out some basic bullet points which explain these key points.

It keeps it simple and clear, and doesn't require information on each page.
