### ISSUE TITLE
Odd search behaviour

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-core/job-server#1404]
Workspace search/filter is perhaps too fuzzy? There's a workspace matching the string I've typed but it hasn't yet appeared near the top of the list after typing quite a lot of characters:
![image](https://user-images.githubusercontent.com/24392156/144047997-37d9e10f-e2bd-42a5-9a1f-dc6a6b7865b5.png)

**Comment by ghickman** [comment]
@HelenCEBM – could you link the page this is happening on please?

Are you seeing any movement in the list at all?

**Comment by HelenCEBM** [comment]
https://jobs.opensafely.org/

Yes it's filtering but not sure what it's filtering on exactly because (as you can see) lots of workspaces don't match the string being typed. Though it does get there if I keep typing more characters
