### ISSUE TITLE
Multiple applications

### ISSUE THREAD

**Issue by amirmehrkar** [opensafely-core/job-server#1413]
It looks like there is a possibility of making several applications unintentionally. This certainly happened to me!

An applicant has made 3 three but only this one is valid https://jobs.opensafely.org/staff/applications/c058/

The other two can be deleted: https://jobs.opensafely.org/staff/applications/a17b/ and https://jobs.opensafely.org/staff/applications/df35/
and another one from different applicant https://jobs.opensafely.org/staff/applications/fe12/

@ghickman @iaindillingham should we consider if there application form needs a tweak to prevent people creating multiple forms. When I did it, I think a form was created everytime I clicked the first continue page? 

What's the trigger that actually creates the form?
I think a problem might be that people create forms and peruse them because they want to know what the full form entails, understandably. How can we give them that option without creating multiple forms?

**Comment by amirmehrkar** [comment]
If we have this challenge of duplicates i am hesitant to roll this out if it's a headache to delete and also becomes a problem to manage on my dashboard.

**Comment by ghickman** [comment]
> What's the trigger that actually creates the form?

Clicking next on the Terms page creates a new application.

**Comment by amirmehrkar** [comment]
So do we accept this issue given people want to scan the form? Ie that they click next, scan around then come back to it later? 

Or maybe a fix is to render a pdf link saying "please look at this pdf of all the questions you will be expected to answer before starting an application".

If you are not bothered about deleting repeat applications I can advertise the link.

**Comment by amirmehrkar** [comment]
OK after discussion with @ghickman we will proceed and accept additional forms may be created

**Comment by sebbacon** [comment]
Can you record the rationale? In case it's relevant to if/how to action this ticket when the time comes.

**Comment by ghickman** [comment]
Good point.

Amir pointed out that we're getting multiple applications from many users as they move forwards and backwards from the terms page into and out of the wizard (which is seemless from a UI perspective).

Suggestions to mitigate this were:
* Provide all questions up front ala #1203 
* Fold terms page into the wizard

Both suggestions have merit but the work to do them is rather involved, certainly not a quick fix for the issue.  So I felt it was easier to do some Application triage after we have something like #1306 (or the equivalent in the Staff Area).

**Comment by amirmehrkar** [comment]
I've added the word DELETE to the start of every application that is not necessary https://jobs.opensafely.org/staff/applications/

It's really easy to make an application because as soon as you hit the START NOW button on the bottom of this page https://jobs.opensafely.org/apply/ it creates a new application even if no fields have been entered on the first page. 

@ghickman would it be possible to give me an easy way to delete them for now?

**Comment by ghickman** [comment]
@amirmehrkar #1474 will let you delete (and restore) any applications you want to, and Users can do the same.

I think we should certainly look into making it hard to accidentally create new applications, but it needs some thought given the way things currently work.
