### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by amirmehrkar** [opensafely-core/job-server#1455]
Feedback on https://jobs.opensafely.org/staff/applications/9863/

On the whole, I have a positive impression of OpenSAFELY and its systems. The information documentation is clear and informative. The internal hyperlinks are especially helpful. The open forums for queries are such a breath of fresh air. You really are making open feasible and manageable.
I also have some suggestions for improvement. I was going to suggest online applications but that has been sorted, now. However, the online form doesn’t let me go back a page, only forward (I now I can review and edit previous section just before submission, though). Regarding the ‘Add a new researcher’ form, please reword the button to say ‘Add/Amend this researcher’ so that it is distinguished  from the ‘Add new researcher’ button on the ‘Researchers’ page.
Finally, if only to save yourself from variation in applications, perhaps you could provide greater specification of what is required in ‘Study information’ section. Maybe have separate boxes for Why, Aim, Objectives, Methods, and PPI.

**Comment by ghickman** [comment]
We've covered the back button in #1373 and I'm not sure the rest is actionable.
