### ISSUE TITLE
Support configuring new releases per workspace

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-server#1536]
Currently an entire project needs to opt in to new release flow as a whole.

Researchers would like to do it on a per workspace basis instead.

In theory we could add a workspace level flag as well, and if either the project or workspace flag is set, we can use the new release flow.

**Comment by ghickman** [comment]
Rather than two flags, which always ends up complicating logic IME, we could move the flag to Workspace and make setting it for all Workspaces in a Project an action on the Project.

**Comment by sebbacon** [comment]
Seagulling in to say I'm not convinced we've got the whole Workspace / Project metaphor really tied down in any case, have we?  Just wondering if we need to think about that before doing any fiddly extra work.

OTOH if it's JFDI then whatevs.

**Comment by ghickman** [comment]
@sebbacon – agreed but yeah I don't think that's relevant here, this feels like a relatively small change given we already have all the logic, we're shifting it around a little bit, but definitely not worth gating on _that_ discussion!
