### ISSUE TITLE
Update Roles

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1547]
After some discussion we've identified the biggest differences between our Roles&Permissions and how the site is used in reality.  The main change here involves us no longer sticking to Permissions only being assigned to one Role.

* `OutputPublisher`: change to a per-Project Role
* `OutputChecker`: give `release_file_view`
* `ProjectDeveloper`: give `release_file_view`

**Comment by bloodearnest** [comment]
Thanks for getting this done! It's been a pain point for a long time

**Comment by lucyb** [comment]
Oh sorry, we haven't done it, it's just something that we're going to cover in a future initiative, so we didn't need the individual ticket right now. I should have written a comment when I closed it.
