### ISSUE TITLE
Slack notifications for new release method

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/job-server#1588]
We currently get slack notifications in #opensafely-outputs of any releases from TPP using the old release method. As more people shift to the new method, it would be good for these to also be captured by the slack notifications.

A less urgent addition is to also trigger notifications on release from EMIS. Distinguishing the backend in the notification message would be useful when this is implemented.

**Comment by bloodearnest** [comment]
Release notifications for new-style releases makes sense.

But notification for old-style EMIS releases should be happening

**Comment by bloodearnest** [comment]
Adding backend is in #1589 1589

**Comment by bloodearnest** [comment]
New releases added in #1590 

Next: debug why it doesn't work in EMIS
