### ISSUE TITLE
PI/Line manager details 

### ISSUE THREAD

**Issue by amirmehrkar** [opensafely-core/job-server#1620]
We need to collect details of 

1. The name and email of the Principle Investigator (PI) of the study OR Line Manager of the applicant.

I think the best place for point 1 is in the Contact details section at the start:
"Name of Principle Investigator (PI) of the study OR Line Manager of the Applicant"
"Contact Email"

With narrative text saying: 
The PI or Line Manager must email applications@opensafely.org confirming they have read and support the application.

It might be good to also have this narrative text reminder also put at the end next to the SUBMIT button too (as might be easy to forget).

![image](https://user-images.githubusercontent.com/20584513/154775347-39c7a98c-47bd-4d37-8784-09fe658027c1.png)

@sebbacon @ghickman if you could assess how / when this could be added.

**Comment by ghickman** [comment]
This shouldn't be too much work since the application form is dynamically built.  I would think no more than half a day.
