### ISSUE TITLE
Document the roles in use in Job Server

### ISSUE THREAD

**Issue by benbc** [opensafely-core/job-server#1624]
Job Server assigns roles to users ("researchers") within each project (for example "Output Checker" and "Project Collaborator"), but there isn't a comprehensive documentation of what these roles are for. We should document the roles so that people outside DataLab who are trying to understand OpenSAFELY can get a better picture of how our permissions model works.

There is some documentation of a subset of the roles [here](https://docs.opensafely.org/permissions/).

Once the roles are documented they also need to be linked to from the [platform developer access policy](https://docs.opensafely.org/developer-access-policy/). Each reference to a role in that doc should be turned into a direct link to the documentation of that role.

**Comment by benbc** [comment]
@sebbacon I've added this to the backlog so that it doesn't get forgotten. It seems like a good thing to do independent of the policy, but I don't think its super urgent.

**Comment by sebbacon** [comment]
I believe this is covered by https://github.com/opensafely-core/job-server/issues/1341 which is in progress by @tomodwyer
