### ISSUE TITLE
Improve style of single-line <pre> blocks

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1651]
We're using `<pre>` tags to display log paths on JobDetail pages ([example](https://jobs.opensafely.org/qmul/bmi-and-metabolic-markers/bmi-and-metabolic-markers/5905/ca4f5pvbaehznug6/)).

The log paths are very long and need to scroll horizontally.  On macOS at least trying to both scroll and read these blocks is not-ideal, macOS' hidden scroll bars cover all the content.

Ideally it would not.

**Comment by oovk** [comment]
Hi @ghickman, I am new to this project. I work as a student research assistant under prof. sabastian vollmer associated with alan turing institute, we are trying to implement opensafely framework for EHR here in Germany.  Can you please guide me to appropriate code part so that i contribute to opensafely? I belive it will be easier to understand the project structure that way.

**Comment by oovk** [comment]
Hi, I am trying to setup the repo, but i am unable to download the data dump, can you please help?
I am using this dbaddress - 
`scp postgresql://localhost/jobserver:/var/lib/dokku/data/storage/job-server/jobserver.dump jobserver.dump`

**Comment by ghickman** [comment]
@oovk – I'm afraid you won't be able to download a copy of the production database since you're not a member of staff.  However, you can create some testing data by using a local copy of the site.  You'll need to:
* create [a GitHub OAuth application](https://github.com/settings/applications/new), the fields don't matter too much for local dev, except the callback URL which needs to be `http://localhost:8000/complete/github/`.  Then set up `SOCIAL_AUTH_GITHUB_KEY` and `SOCIAL_AUTH_GITHUB_KEY` with values from that application.
* register a user account on your local version of job-server
* give your user the `CoreDeveloper` role by setting `ADMIN_USERS` to include your username, then running `python manage.py ensure_admins`
* create an Org and Project in the Staff Area
* assign your user account to the Project with `ProjectDeveloper` and `ProjectCollaborator` roles
* create a Workspace for the Project
* create a JobRequest in the Workspace

You'll then need to create a Job via the Django shell (`python manage.py shell_plus`) since you won't have a job-runner instance to do it for you (for local dev this is fine).  You'll then be able to view the Job detail page.
