### ISSUE TITLE
Add count to release listings

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-core/job-server#1658]
Example link: https://jobs.opensafely.org/datalab/antibody-and-antiviral-deployment/mabs-codecounts/releases/

When multiple batches of files are released on same day they can't be distinguished:
![image](https://user-images.githubusercontent.com/24392156/158227133-a8ac8a06-ac6b-43d3-bc04-33436daef5bf.png)

Similarly for files released on different days it may be hard for users to remember which batch of files was in each release.

Suggested fix: add count of files to each release to help users distinguish releases.

**Comment by sebbacon** [comment]
If simple enough, it would also be really nice to add "... hours ago" and "...minutes ago" for periods less than a day / hour.

**Comment by ghickman** [comment]
@lucyb – we are already loading the files for each row in this list, the files button here is actually a collapses component from Bootstrap, so you've got a few options to grab the count of them!

Like in #1657 the `WorkspaceReleaseList` view handles this page.

re the hours/minutes ago, we could have a look at how Django's humanize filter works for us here.
