### ISSUE TITLE
Rename "download" button "download all"

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-core/job-server#1660]
The `download` option should be renamed `download all` to be clear it isn't going to give any options

**Comment by ghickman** [comment]
@lucyb – this is on the WorkspaceReleaseView page again, although it should (🤞) be a template-only change.  Helen is talking about the download button for each release, eg on [this page](https://jobs.opensafely.org/datalab/antibody-and-antiviral-deployment/mabs-codecounts/releases/).

**Comment by lucyb** [comment]
How about this, where the number of files that will be downloaded is shown? 

The number of files shows regardless of whether someone has permissions to view the files, hope that's okay?

![Download-All-Files](https://user-images.githubusercontent.com/3889554/159036193-5e7fbd20-7120-467f-ad2a-e953c0cd03bc.png)

**Comment by HelenCEBM** [comment]
Looks good! I don't think there's any risk in showing how many files are released... You still need job server access, right? So it's quite a small group that would be able to see the number anyway...

**Comment by ghickman** [comment]
Yep, only users of job-server, and those with access to this view (IIRC you need at least the ProjectCollaborator role) so a count here shouldn't leak anything 👍

**Comment by sebbacon** [comment]
Sorry to be a pain, but I'm not sure about this.

It is strictly speaking possible for an attacker to use globs to release information via file counts.

My gut reaction is that this is an acceptable risk (which can also be mitigated), so I think it's fine.

HOWEVER, I'm a little uneasy about us making those kinds of decisions on the fly. Perhaps we need a policy that identifies critical boundaries for "data" transfer and describes risks and mitigations? Could we take this to the security group (cc @inglesp) for some kind of "formal", in the round discussion? It should probably go via @amirmehrkar too for backup.

Sorry @lucyb for delaying one of your first releases!

**Comment by lucyb** [comment]
It's not a problem Seb, it's why I asked the question! Having a clearer policy would definitely help with these kinds of decisions in future though

We could hide the counts in the same way that we disable/enable the button, so that only logged in users would see them, which would avoid any concerns.

**Comment by bloodearnest** [comment]
If a user can see this page with counts of files, they can also see the released outputs themselves, so do not need clever tricks?

I don't think there is any additional risk here

**Comment by sebbacon** [comment]
> If a user can see this page with counts of files, they can also see the released outputs themselves, so do not need clever tricks?

The difference I had in mind is that _outputs_ have been output-checked by our rigorous process; they have been assured to be safe even for public release.  Output-counts not so much.

> This is just showing the counts of output-checked and released files i.e. things which are going to be made public in any case.

You're right @evansd that I hadn't explicitly thought that point through.

So maybe that's fine.
