### ISSUE TITLE
capture PI/line manager details

### ISSUE THREAD

**Issue by amirmehrkar** [opensafely-core/job-server#1667]
At the top of the user form - where application details, we also need to capture:

Name of PI/Line manager
telephone 
email 

And blurb: "The sponsor must also email [applications@opensafely.org](mailto:applications@opensafely.org) confirming they have read the Study Information and Study Purpose sections, and that they support the application."

**Comment by ghickman** [comment]
This looks like a duplicate of #1620, re-open if that's a mistake!
