### ISSUE TITLE
"Latest outputs" links to files broken

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-core/job-server#1677]
E.g from this page: https://jobs.opensafely.org/datalab/antibody-and-antiviral-deployment/mabs-codecounts/releases/

Under `Latest outputs` -> `files` it is possible to click on the links to individual files but each one gives an error 404
![image](https://user-images.githubusercontent.com/24392156/159292503-4d59b4dc-9da9-4041-9f04-9ebd83303dcd.png)

However, the equivalent links under each individual release do work. And the files listed as `Latest outputs` can be viewed under `view`

**Comment by lucyb** [comment]
Clicking on the links under `Latest outputs` -> `files` now takes you to the correct page, but it does not automatically show the file (as you'd expect)

**Comment by lucyb** [comment]
Fixed in [pull request #1691](https://github.com/opensafely-core/job-server/pull/1691)
