### ISSUE TITLE
Send Sentry notifications when jobs die with "generic database error"

### ISSUE THREAD

**Issue by evansd** [opensafely-core/job-server#1729]
This depends on two related tickets being closed first:
 * https://github.com/opensafely-core/cohort-extractor/issues/776
 * https://github.com/opensafely-core/job-runner/issues/184

Once these are fixed we will start seeing jobs which have an error message indicating the some kind of unexpected database error occurred (exact text tbc). When we hit such jobs it would be best if we got alerted immediately as there's almost no chance the user can fix this for themselves.

This will mean adding another case to the existing alerting logic here:
https://github.com/opensafely-core/job-server/blob/dec98fc81c4863314e9895a070312da650607cfd/jobserver/api/jobs.py#L190

**Comment by ghickman** [comment]
We should probably get new job-server events posted to Slack from Sentry

**Comment by evansd** [comment]
Now that we have Slack alerts, when we implement this ticket we'll need to update (or at least check) the alerting logic to make sure that Sentry posts the new class of errors into Slack as well.

Alert is configured here:
https://sentry.io/organizations/ebm-datalab/alerts/rules/job-server/8406619/details/
