### ISSUE TITLE
Allow OS Interactive to authenticate against Job Server to view released outputs

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#1738]
OpenSafely Interactive will need to access **released** outputs from the Interactive project on Job Server. To do this it needs some way of authenticating.

**Comment by bloodearnest** [comment]
Output-explorer needs this too, so is being worked on.

The plan is to:

 - a have bot users for OS Interactive and output-explorer that have ProjectCollaborator roles in the projects they need access to
 - @ghickman to add a PAT token alternative API login
    - securely random token in plaintext
    - 90 day expiry
    - sentry and/or slack alerts on expiry
