### ISSUE TITLE
Add watershed text

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#1754]
Add watershed text:

> All projects after this date adhere to our policy. Earlier projects may have some gaps or missing commits as a result of being early projects whilst the system was in an early stage of development.

This follows a redaction issue, which is discussed in [this Slack thread](https://bennettoxford.slack.com/archives/C0270Q313H7/p1646390943161389).

**Comment by sebbacon** [comment]
Sorry, I'm not really able to help much here (yet, anyway). Why does this ticket exist; did I originally request this change?

**Comment by iaindillingham** [comment]
It started out as a note on the regatta board, @sebbacon, which was added to capture the discussion in the linked Slack thread. Simon finished the thread by asking you whether you had seen it 🙂 

I made an issue from the note, because I wasn't sure what, if anything, should be done. FWIW, I don't think we should do anything. The redaction preserved the timestamps and messages of the commits, but removed their contents. Success! However, I don't feel confident closing this issue without another 👀.

**Comment by sebbacon** [comment]
Ah yes, I think this originated in @inglesp's security review maybe?

I'm not completely confident either, I'm afraid. Your analysis sounds correct, but I'm slightly worried there are other reasons to think there's a "watershed" point before which some "policy" no longer pertains.  I don't remember writing that text myself, though it's possible I did.

Do you think you know which policy this is about?

**Comment by sebbacon** [comment]
Having spoken to Simon, he has no idea either. I suggest we just close this. Please re-open if you disagree!
