### ISSUE TITLE
Implement  a JobRequest API

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-server#1822]
This would allow the creation of jobs from OSI and openssfely-cli in future.

We can probably use the job-runner API JobRequest JSON definition?

**Comment by ghickman** [comment]
We can use this as an opportunity to pick apart the `JobRequestCreate` view some more.  My goal would be to extract the core creation of a JobRequest from the view into something both the view and API can call.  I'm not sure if any validation could be shared between the two.
