### ISSUE TITLE
Link from logs page to job_request_detail page

### ISSUE THREAD

**Issue by madwort** [opensafely-core/job-server#1838]
From e.g. [a project log page](https://jobs.opensafely.org/qmul/bmi-and-hba1c/bmi_and_hba1c/logs/) you can click to [a job](https://jobs.opensafely.org/qmul/bmi-and-hba1c/bmi_and_hba1c/8970/fiauaxj5jc6ay5s2/) but not to [a job request](https://jobs.opensafely.org/qmul/bmi-and-hba1c/bmi_and_hba1c/8970/). Any objection to adding such a link?

**Comment by ghickman** [comment]
Please do! I've been meaning to add this for ages, it just needs some UI love to squeeze it in.

**Comment by wjchulme** [comment]
Came here to add this issue! +1
