### ISSUE TITLE
Ingest more fine-grained job information into honeycomb

### ISSUE THREAD

**Issue by madwort** [opensafely-core/job-server#1840]
* This may first require increasing the amount of information we send from job-runner to job-server via the api calls
* particularly interested in more detail about status - currently have `queued`, `running`, `success`, etc, but could also have things like `preparing`, `copying files` (details tbc)

**Comment by lucyb** [comment]
@bloodearnest Is what you're doing going to supersede this?

**Comment by lucyb** [comment]
Superseded by https://github.com/opensafely-core/job-runner/issues/464
