### ISSUE TITLE
Outputs-viewer table UI improvements

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-server#1843]
When reviewing outputs, researchers often need to examine CSV outputs in close details.

This includes sorting and filtering on columns, but also the ability to view min/max/sum values of columns, rows and random selections.

It would be good to support these kind of UI features in the output viewer.

Some slack context: https://bennettoxford.slack.com/archives/C31D62X5X/p1654507486545339

**Comment by lucyb** [comment]
I don't believe this is needed in the Outputs Viewer now that we have Airlock, so I'm closing this ticket.
