### ISSUE TITLE
Identify repos that have had releases added to them

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#1901]
Create a script to check PRs and commits to identify repos that have had released outputs. Label these repos with a particular `topic` in GitHub, so they are easy to filter in job server.

Note: currently users have maintainer permission, which allows them to change topics on a repo. Their permissions need to be changed to write instead.

**Comment by bloodearnest** [comment]
Many of these repos have had the `github-releases` topic added. 



However, for early repositories, it is difficult to tell if the they have had github releases or not, so more work need to go over these repos.
