### ISSUE TITLE
View projects and workspaces you belong to 

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/job-server#1976]
With an ever increasing number of workspaces it's more difficult to navigate to workspaces you're interested in. It would be nice to have a page where you could see:

- All the projects you are involved in.
- All the workspaces you are involved in.
- All of the jobs you've submitted. ie. [this](https://jobs.opensafely.org/event-log/?backend=&status=&username=LFISHER7&workspace=), but more easily accessible

**Comment by ghickman** [comment]
@LFISHER7 – does the homepage redesign cover all of these points for you?

**Comment by LFISHER7** [comment]
Yes!
