### ISSUE TITLE
Add a UserDetail page

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1986]
We have various detail pages (Org, Project, Workspace, etc) which show items in the context of those objects (eg workspaces just for a given Project), but we don't do this for Users yet.

It would be useful to have public pages for our users where we can show which projects/workspace/etc they're involved in.  We can also link to those profiles from all the places we already show users such as the Project page.

Tying this to the people involved in an application would be a nice to have depending on if we've turned that data into user accounts by the time we add this page.

**Comment by lucyb** [comment]
@ghickman to add this to the gdoc and close

**Comment by ghickman** [comment]
Migrated to [this doc](https://docs.google.com/document/d/1TbK52CyVM3dsWpJsEu8ffrgW_dviUMjNxqy6YWvRwZ0/edit) for further discussion.
