### ISSUE TITLE
Publishing Repos: Researcher Agreement

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#1988]
### User story
As the owner of a project with a private repo who has chosen to make my repo public, I have a way to register that choice in the system, so that I can make my repo public with minimal effort

### Further info
Tom O already has a clear idea about how this should look and can wireframe it for us

### Acceptance Criteria
* A link takes the user to a page where they can agree to make their team’s repo public
* The page must clearly display the names of all the workspaces associated with the repo, with a link from each workspace to the branch on GitHub, and the names of their owners (currently creators)
* There must be a way to get the same key information that is communicated via email at 11 months (implementation: the email may direct here?) (I think - ask Tom O for advice on this from a UX perspective!)
* The user must also actively agree that the READMEs on each branch of the repo related to their workspaces are correct (follows OpenSAFELY guidelines)
* Once all users have clicked “agree” an automatic email confirmation must be sent to all workspace owners (the same as those who would receive the email at 11 months - though that email will not have been sent if this is done prior to 11 months)
* Once all users have clicked “agree” Amir must be automatically alerted somehow (whether this should be an email or another route is still to be determined - decision should be made based on things like technical feasibility, what is easiest for Amir, and how it fits into the process for Amir giving approval) - SUGGESTION: change this to auto-alert to co-pilots slack channel when there are no outputs to GitHub
* The page, user journey, and content must have been reviewed and approved by Amir

**Comment by CLStables** [comment]
I have made a couple of edits to the Acceptance Criteria:
* I removed "It must be clear that they are agreeing to make ALL branches of that repo public, and that if they are not the person with the authority to do this then they should not agree"
* "Once a user has clicked “agree”" - changed to "Once all users have clicked "agree""
This is related to changes made in the linked ticket on Publishing Repos: Auto Emails (see comment there for more info). Thanks!

**Comment by CLStables** [comment]
A comment made by Lucy on the gdoc (I've removed this section now, so recording here so we don't lose it): "The email should also explain the next steps (i.e a member of tech support will make the repo public shortly, a reminder of what that means, and a way to contact tech support if needed)."

**Comment by ghickman** [comment]
While implementing this we need to think about how the solution would be affected by a workspace creator being unable/unwilling to sign off a repo for being made public.

**Comment by lucyb** [comment]
> While implementing this we need to think about how the solution would be affected by a workspace creator being unable/unwilling to sign off a repo for being made public.

That could be a strong downside of needing to have ALL workspace owners' approval, as it increases the chances of one person being unable/unwilling to sign it off and makes answering that question more complicated.

Is it possible that someone with a higher level of access (I'm not sure of the roles, is a project owner or the person who submitted the application) should also have the ability to sign-off on making it public (and maybe for ALL workspaces).

**Comment by lucyb** [comment]
The OpenSAFELY Docs state that tech support need to be contacted to make a repo public. This may need updating as part of this change. For example, [see the public/private changes](https://opensafely-documentation-pr-894.onrender.com/repositories/#repository-visibility) on this [branch](https://github.com/opensafely/documentation/pull/894)

**Comment by CLStables** [comment]
The acceptance criteria with "Once all users have clicked “agree”..." need to be updated. At the moment we are building a solution that would change it to "Once all workspaces have had researcher sign-off to be made public" and that sign-off could be given by ANY researcher linked to the project. But I would prefer us to clarify this with Amir before changing the acceptance criteria. George plans to walk him through the workflow.

**Comment by CLStables** [comment]
Last few acceptance criteria need to be reviewed and possibly new tickets need to be created

**Comment by ghickman** [comment]
Last 3 points have been broken out into:
* #2261
* #2262 
* #2247
