### ISSUE TITLE
Publishing Repos: Auto emails

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#1989]
### User story
As the owner of a project with a private repo, I want to be prompted to make it public at 11 months and receive clear guidance on my options, so that I can choose to make my repo public without having to contact Amir or anyone else in the OpenSAFELY team or, if I do not want to make it public, I can contact them easily to discuss.

### Further info
Lisa has already drafted an email to users and is happy to collaborate on this

### Dependencies
Blocked by: [Researcher agreement](https://github.com/opensafely-core/job-server/issues/1988) and [Update README Instructions](https://github.com/opensafely/research-template/issues/92)

### Acceptance Criteria
* Emails must be automatically sent at 11 months after date of first run
* Emails must be sent to the owners (currently creators) of all workspaces associated with the repository - as a single group email with the IG email address cc’d (check with Amir what the address is)
* Emails must contain (or direct users to) the following:
    * The date on which the repo will be 12 months post-first-run
    * Amir’s project number (in both the subject header and the content?) so that he can more easily track replies/conversations
    * A link to the repo and the names of all the associated workspaces
    * Clear guidance on what agreeing to make public means and the implications (either in the body of the email or linked to documentation)
    * A reminder that they agreed in the DAA to make their repo public after 12 months
    * Instructions on what to do next (i.e. if agree go to link, or if disagree contact Amir by replying to this email)
    * (link to) clear guidance on when/how to update the README - including the fact that all branches must be updated
    * An explanation of the fact that EVERYONE on the list must approve via the link before it can be made public
* The content of the email must have been reviewed and approved by Amir
* The email and following process has been tested by at least one internal user

**Comment by CLStables** [comment]
I have updated the acceptance criteria to remove "An explanation of the fact that only one person from the list can approve making it public and verify that all READMEs are updated, and that it is their responsibility to ensure that everyone in their group is happy before they do that" and changed it to EVERYONE having to do this. This is based on our conversations, but I will also check in with users and if anyone here thinks we should change it back for any reason then please let me know. Thanks!

**Comment by LisaHopcroft** [comment]
[Here is the draft email](https://docs.google.com/document/d/1QfXuDfryH5wJrPsiFpBqsusuzTvcmuTUeQM-6d9Xz6Q/edit), which still needs to be:
1. split into two emails, one for the end-of-project and one for the 1 year anniversary
2. finalised with regards to text

I'll be picking this up in the next few weeks.

**Comment by ghickman** [comment]
@LisaHopcroft – the draft email doesn't contain several of the items in the acceptance criteria for this ticket, are you happy to add those or should we discuss them on a call?

**Comment by LisaHopcroft** [comment]
How about I add them, share the updated draft with you and then we can discuss any outstanding issues? I've just finished something so I'll look at this just now.

**Comment by LisaHopcroft** [comment]
Further to a conversation with @ghickman, a new draft of this email is available [here](https://docs.google.com/document/d/1gbAnfs-tb7pz8cNr-dSmIgvj09keOyYQiyboLOO5Ug4/edit).

**Comment by lucyb** [comment]
We've agreed on a manual process for now, so we aren't expecting to automatically generate emails in the near future.
