### ISSUE TITLE
Amir's Approval Process for Repos with Outputs

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#1990]
### User story
As Amir, I want a clear process to follow to review and approve requests from researchers to make their repos public, so that I can make repos public quickly and easily while ensuring all the requirements have been met first.

### Dependencies
Researcher agreement https://github.com/opensafely-core/job-server/issues/1988

### Note
* Speak to Amir once some mockups/plans have been done but before writing the code

### Acceptance Criteria
* A clear process for Amir to follow must be documented and contain all the necessary steps. The contents must be agreed with Amir, but will include:
   * Check that the researcher who has signed off on making the repo public is the right person to do this (has the authority) (what info would make this easier for Amir?)
   * If the repo has data in it, ~request approval from NHSE to make it public (what info will NHSE need?)~
   * Once all approvals have been obtained, trigger making the repo public
* There must be a way for Amir to track where each repo is in the process
* There must be an easy way to be guided through the process from Amir’s “staff page”
* ~If there is information in Job Server that can help Amir to make the decisions, this should be surfaced in the correct place/at the correct time (refine this once we know what the process is!!)~

* Find out from Amir how he wants to be contacted about having new repos to review (i.e push notification or reviewing on dashboard)
* Document that repos with outputs should only be approved by Amir / delegate
* The process and documentation must have been reviewed and approved by Amir

**Comment by CLStables** [comment]
To do: check that all this is covered in Amir's handover doc, then close

**Comment by CLStables** [comment]
I have checked and am happy that all relevant parts have either been done in other tickets or have been captured in Amir's handover doc (see #2247 )
