### ISSUE TITLE
Merge project 110 versions

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1991]
Original Project: https://jobs.opensafely.org/lshtm/vaccine-coverage-and-effectiveness-in-chronic-kidney-disease-patients/
Correct Project: https://jobs.opensafely.org/lshtm/110-covid-19-vaccine-coverage-and-effectiveness-in-chronic-kidney-disease-patients/

Objects to move:
* [This workspace](https://jobs.opensafely.org/lshtm/vaccine-coverage-and-effectiveness-in-chronic-kidney-disease-patients/ckd-coverage-ve/) from the original project to the correct one.
* The researchers on the Original Project will need setting up on the correct Project.

Redirects to create:
* The correct project's slug needs to drop the project number
* The original project should redirect to the correct one, this will cover the workspace and other related objects

**Comment by lucyb** [comment]
Okay, let's see if I've understood things correctly. This is my plan:
0. Let the users Ed and John know what's happening
1a. Edit correct project name
1b. And add redirect
2. Set up researchers on correct project
3a. Move workspace from the original project to the correct one
3b. Redirect original project to the correct one

Only 1a and 3a require any code changes (a data migration). Is that correct?

How do I add users to a project? Do I need to add them to the organisation first?

Is this the correct order in which to do things?

**Comment by ghickman** [comment]
> Only 1a and 3a require any code changes (a data migration). Is that correct?

`1a.` can be done in the admin and will do `3b.` for you.

`3a` doesn't require a code change, you can make the change in the database (if we have to do more than say 3 more of these sorts of moves I'll add something to the Staff Area to do it for us), and you'll need to create a redirect for it in Staff Area.

> How do I add users to a project? Do I need to add them to the organisation first?

You can add members to a project in the Staff Area.  Ideally they are also linked to the same org as the project, it's not a requirement, but it would improve the correctness of our data.

> Is this the correct order in which to do things?

I think so, yep!

**Comment by lucyb** [comment]
> 1a. can be done in the admin and will do 3b. for you.

Oh cool (assuming you mean `1b`). I'd missed the edit option in the staff area the first time I saw it.
Do I need to tell anyone I'm renaming the slug for the current project? Seems like an implementation detail rather than anything people should care about.

**Comment by lucyb** [comment]
> 3a doesn't require a code change, you can make the change in the database 

I've previously written a migration to do this (directly altering data in the database being frowned upon). How would you feel about me writing one in this case?

**Comment by ghickman** [comment]
I did mean `1b`, sorry!  You'll need to add the redirect for `3b` yourself, it should be possible from the Redirects section.

**Comment by lucyb** [comment]
@ghickman Right, I believe I've followed all the steps. Can you just check that the projects look correct, please? If so, I'll close this ticket.

What needs to happen to the old project, is there a way of archiving it? Should I remove Ed and John as members to save confusion?

**Comment by ghickman** [comment]
The old project should be deleted via the shell.  We don't keep these defunct projects around since all the data is part of the child objects and our goal is only to have the projects listed on the Approved Projects page.

**Comment by lucyb** [comment]
> The old project should be deleted via the shell.

I don't see a django command for this, so I assume you mean using `delete()` within the django shell?

Is it worth having something in the staff area to allow empty projects to be deleted? That way this whole ticket could be done in future by someone who's not part of the tech team.

**Comment by ghickman** [comment]
> I assume you mean using delete() within the django shell?

Yep 👍

> Is it worth having something in the staff area to allow empty projects to be deleted?

I've actively avoided the ability to delete in the Staff Area since we, ideally, don't want to delete anything.  These tasks are very far and few between and I'm not sure they should be done by non-tech people yet.  Let's leave that decision until after we know the extent of how many we have to fix first.

**Comment by lucyb** [comment]
What if we restrict it to only being able to delete projects with no users, applications and workspaces? It seems like this is something that will come up occasionally, and manually deleting things in the database sounds error prone and annoying.

**Comment by ghickman** [comment]
I'm keen to stick to my rule of thumb around only adding tools once we've done a task at least 3 times.  Previous data improvements have renamed the Project so they're not all the same.  Let's try out a few more of these tickets first!

**Comment by lucyb** [comment]
I can already see two other projects that need deleting, but I agree about not over-engineering it. So, how about this as a compromise - a quick little django command that will be easy to remove when all data is nicely up-to-date?
https://github.com/opensafely-core/job-server/pull/2181

**Comment by lucyb** [comment]
I ran the following command in production and deleted the original project. I'm now closing this ticket, as I believe there's nothing else to do.

`dokku run job-server python manage.py delete_project "Vaccine coverage and effectiveness in chronic kidney disease patients"`
