### ISSUE TITLE
Clear up terminology in event log

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/job-server#1995]
From the [event log](https://jobs.opensafely.org/event-log/) you have the followinng search options

![Screenshot 2022-08-05 at 12 51 49](https://user-images.githubusercontent.com/37254732/183072140-739300ff-a536-4c8c-b9ac-012e82352702.png)

I think the first search bar should read "Search by Action or Job ID".

It took me a while to figure out where I would find a Job request ID for the second search. It's not until you go into a individual job page (e.g. [here](https://jobs.opensafely.org/lshtm/effectiveness-safety-sotrovimab-molnupiravir/sotrovimab_molnupiravir/10280/tl6vp524w26phxon/) that the request ID is surfaced (in the page path at the top) and even then it's not obvious what this is. This could perhaps be added as a column in the events log?

Regardless, I doubt either of the above are used very much. I only ever find myself filtering by workspace or user.

**Comment by ghickman** [comment]
The staff area has now grown a job requests page with a search box that covers this and a few other fields.
