### ISSUE TITLE
Investigate a release review UI

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/job-server#2024]
# Prototype selectable list view

- User view
  - Add “this” file to Review Request
  - Tree select files to add to Review Request
  - Modal to send Review Request (show steps)
- Reviewer view
  - New section in Staff Area
    - List pending reviews by Workspace
  - Show only requested files / hide non-requested files
  - Only show latest version of the requested file (maybe timeline of previous requests)
  - Approve/Reject button on each file
  - Add comment explaining why on each file
  - Modal to send Review back to user (approved/rejected/pending)

# Implement into existing Outputs SPA

- Todo

**Comment by LFISHER7** [comment]
In case useful, [this](https://docs.google.com/forms/d/1mP2fw3__SZ1DK3B7Kn6Z200z-ZGkPUsHZ1agvqSEXhY/edit) is a google form version of the review request form which includes a few extra things compared to the existing word doc

**Comment by tomodwyer** [comment]
Prototype complete, reverted in https://github.com/opensafely-core/job-server/pull/2083
