### ISSUE TITLE
Release Review UI

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-server#2025]
Shore Leave proposal for @bloodearnest @tomodwyer and @ghickman

We plan to spike an implementation of the release review UI, as defined here: 

https://docs.google.com/document/d/1iGzZUm0YTRTnYC8p_ZnGFT09NP8uXkXDLkN2zQOzdbE/edit#heading=h.a6ye793ybzmm

The goal is an mvp implementation of the base workflow for requesting files for release and approving/rejecting them. We will base it on the current manual process as much as possible.

We do not expect to have it ready to roll out in 2 weeks, but we hope to have a good demo that will help bump its future prioritisation, and hopefully ready to beta test internally.

Related tickets:

* [x] #2026 
* [x] #2027
* [x] #2028 
* [ ] #2029 
* [ ] #2030

**Comment by bloodearnest** [comment]
#2026

**Comment by bloodearnest** [comment]
Bah, can't figure out how to get tickets to show.

**Comment by tomodwyer** [comment]
Work completed in shore leave, future work to be scheduled.
