### ISSUE TITLE
Releases UI: Create Github issue when Release created

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-server#2027]
This should use the current [issue templates](https://github.com/ebmdatalab/opensafely-output-review/issues/new/choose) as a base, and possibly enhance it since we have info about the files.

Talk to @LFISHER7 about the specifics (e.g. internal vs external)

Maybe include a direct link to the appropriate SPA page (which will only work on level 4)

We should store the issue url in the db.

**Comment by LFISHER7** [comment]
I intend to update the templates slightly (see ebmdatalab/service-analytics-team#61). I can hopefully get that done this week in time for the above

**Comment by ghickman** [comment]
@LFISHER7 – what do we normally ask researchers to put for issue titles here?

**Comment by LFISHER7** [comment]
This has generally been the workspace name. This has meant there are duplicate issue names, but I don't think that's a problem unless it would be easy enough to append the review request number for a given workspace

**Comment by ghickman** [comment]
@LFISHER7 – what is the definition of an internal user in terms of requesting outputs getting released?  Can we rely memberhip of the DL org on job-server?
