### ISSUE TITLE
Feedback: What happens next to repos with outputs on GitHub? 

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2065]
Now that we are tracking which repos have had outputs released to GitHub on the repos page we want to find out how Amir's process works in surfacing them to NHSE.

Some points to go through with him:
* do we need to expose the actual outputs to him?
* what the tick/cross signify and how confident we are that no means no
* possibly update tick/cross to yes/no (ask Tom O for input)
* Explore what process Amir will need to follow to get approval from NHSE and if we need to do any more development to help this process

**Comment by lucyb** [comment]
This has now been covered with Amir.
