### ISSUE TITLE
Missing section on release page

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/job-server#2074]
See screenshot below, there is a section missing in the bottom left. I can't remember what used to be there! Found on [this page](https://jobs.opensafely.org/university-of-leeds/cancer-surgery-service-evaluation/all_cause_mortality_with_stratification/releases/01G2CRK604DXZ386RXCTH7KD23/)
![Screenshot 2022-08-30 at 10 06 04](https://user-images.githubusercontent.com/37254732/187396913-b3a4a8ee-b3bf-41f7-8306-303ab8f3e226.png)

**Comment by ghickman** [comment]
@LFISHER7 – apologies that we've not really explained what's currently going on here, this is mostly-a-demo version of the SPA that we're just ironing out a couple of bugs from to get a demo video made with.  `None` here is us hackily showing that there is no cross-release-review data.  We are intending to revert the SPA changes after getting a demo video made so this will go away :)
