### ISSUE TITLE
Improve TPP maintenance mode alert

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2081]
Thanks to some feedback from Dave, 

Rename the freshping alert, so that it appears as:

> TPP Maintenance Mode: DB service is down
> TPP Maintenance Mode: DB service is up

Change the current job server url from:

> https://jobs.opensafely.org/status/tpp/db-availability/ 

to:
> https://jobs.opensafely.org/status/tpp/maintenance-mode/

**Comment by tomodwyer** [comment]
Name updated to "TPP Maintenance Mode: DB service": https://bennettoxford.freshping.io/reports?check_id=864712
