### ISSUE TITLE
Add a users org and backend during application

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/job-server#2130]
A user currently has to be assigned a backend and an organisation to run jobs (and other activities, see #1983). These aren't added during the application and are later added by a co-pilot, often when users discover they can't create a workspace without them. Could we collect and assign these when an application is approved? #1192 suggests adding required backend as a question on the application. Checking whether someone can be added to a specific backend requires confirming if they have signed a DAA (by looking at responses in a google form), which is something else that could be folded into the application process.

**Comment by ghickman** [comment]
We're keen to capture all the necessary details for a user when they're added to the system.  Closing this as there are ideas docs on just this subject already in the pipeline.
