### ISSUE TITLE
Ask user to also sign off GitHub-hosted outputs

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2144]
When a user signs off a repo to say they are ready for it to be made public we need to have some text for repos with outputs on GitHub which remind the user that they are agreeing that the results in the repo are ok to be made public.

We can pull the need for this text from the topics in the GitHub API call.

Amir should probably write if not sign off the final text.

**Comment by lucyb** [comment]
Also worth noting that if a researcher wants to **not** make the repo public at this time, or has any questions, they should email publications@opensafely.org.
