### ISSUE TITLE
Repo internal sign-off by co-pilots

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2155]
**Note:** This is only for repos **without** GitHub-hosted outputs

* [x] Speak to co-pilots to find out if they're happy to sign off repos before they're made public
* [x] Design a process with the co-pilots to do this (e.g when they're notified, etc)
* [ ] Document this in the team manual

**Comment by CLStables** [comment]
George to merge with 2262

**Comment by ghickman** [comment]
The copilot team have a comprehensive process for reviewing projects as they wind up.  Making repos public is a very small part of that and their issue template already links to the relevant docs.  I don't think there's anything we can add to that process other than the notification in the linked PR.

**Comment by lucyb** [comment]
This might be covered elsewhere, but is it worth linking to their process from the team manual?

**Comment by ghickman** [comment]
It's currently in the process of being formalised within the copilot team so I'll leave it up to them to document as they see fit 🙂
