### ISSUE TITLE
Find out if Unknown user can be deleted in job-server

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2201]
We have one user in the Unknown org from when we added orgs and couldn't track down who they were.

We need to find out who the user is so we can attach them to the correct org.  An alternative, if the user is happy with this, is to remove the account.

**Comment by ghickman** [comment]
We found the user, and they were happy for this account to be removed.  It was an old account from very initial testing (no jobs were run with it), and they have another account they use for interacting with the service.
