### ISSUE TITLE
Workflow to manually contact users about making their repo public

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2203]
User story: As Amir I want to easily get a list of user emails on a repo (creators of workspaces) so that I can contact them to request/chase making their repos public

Acceptance Criteria:
- There is a one-step mechanism for Amir and/or Liam to copy all email addresses for workspace creators on a specific repo
- Amir and Liam have demonstrated that they can find and use this mechanism successfully (navigate to it, use it, and send email successfully)
- The email draft created by Lisa has been passed to Amir and Liam to incorporate into their process (as part of general handover documentation at the end of this initiative?)

Background:
- This ticket was created in place of auto emails (https://github.com/opensafely-core/job-server/issues/1989) and will be useful pre-work for that ticket if we do it in future

**Comment by CLStables** [comment]
AC 1 is in another ticket: #2262 
AC 2 has been captured in handover doc
AC3 needs to be captured in handover doc

**Comment by CLStables** [comment]
AC3 has now been captured in handover doc (see #2247 ) so this issue can be closed
