### ISSUE TITLE
Document Project status

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2222]
Now that Projects [have a status field and description](https://github.com/opensafely-core/job-server/issues/2195) we need to explain to users how and when they should be updating it.

Parent: opensafely/research-template#92

**Comment by ghickman** [comment]
@tomodwyer – the ProjectEdit page currently has the status field as a dropdown, is there something we could do in the UI to explain each status there rather than having that information elsewhere (in the docs)?

**Comment by ghickman** [comment]
Digging into where to put this I've found some stale docs around repo visibility and set up which I'll handle as part of this so I can do one major pass of the docs.

Pages to look at:
* https://docs.opensafely.org/publishing-repo/
* https://docs.opensafely.org/repositories

General points to address:
* READMEs don't need updating
* The Project on job-server needs its status (and possibly status description) updating as the project moves forward

Questions to answer:
* Where does the purpose of a project live now it's not in the readme?
  * Should this be pulled from the application's lay description?

**Comment by CLStables** [comment]
Is [this comment](https://github.com/opensafely/research-template/issues/92#issuecomment-1202939704) from Lucy about some of the documentation work she's been doing relevant for this ticket?

**Comment by ghickman** [comment]
@CLStables – No, it's already merged 😁  So this work is layering on top of the foundation she laid!
