### ISSUE TITLE
SPIKE: Add copilots to private repos dashboard

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2251]
Test out the difficulty of adding copilots to the Private Repos dashboard.

We'll need to show a list since some repos still cross project boundaries.

**Comment by ghickman** [comment]
I had a quick bash at a new dashboard page:

![](https://p198.p4.n0.cdn.getcloudapp.com/items/8Lu1KrXY/6296442f-2180-4f78-8b35-44eeed239d60.jpg?v=6b4a8dc662dd041c364c3eaaec66ea26)

@brianmackenna @LisaHopcroft – would this cover much of what you need when chasing projects?  The project and org names link to their staff area pages, and the columns would be sortable.  We could probably add some filtering in there for good measure too.

**Comment by brianmackenna** [comment]
It needs the co-pilot name?

**Comment by LisaHopcroft** [comment]
Fab, thank you! This is really helpful, though copilot name would be a really useful addition.

I did go through the master copiloting spreadsheet the other evening to add missing copilot names. Many were easily identifiable so you should find that the copilot name field is better populated now than it was. Some projects were more problematic (i.e., couldn't find them on jobserver or there were multiple workspaces) so I'd have to do some more digging to work out whose copilot was who.
