### ISSUE TITLE
Set up a dummy-data-only job server as a user sandbox

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#228]
As part of our planned onboarding story we want a dummy deployment users can kick off their first Job on to get a feel for the system without talking to a real database or adding noise to Production.

We'll need:
* a new dokku deployment
* configurable databases
* docs on devs deploying to multiple dokkus

**Comment by sebbacon** [comment]
The dokku deployment could be a jobrunner-and-jobserver-in one.

**Comment by sebbacon** [comment]
When deployed as a sandbox, the job-server should make this very clear in a banner. "This is a sandbox for testing opensafely-compliant repositories against dummy data. To run against real data, <visit the live job server>" or similar

**Comment by ghickman** [comment]
@bloodearnest – does the Test backend remove the need for this ticket?

**Comment by bloodearnest** [comment]
Yeah, I think so
