### ISSUE TITLE
Merge Ethnicity short data report projects

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2280]
The [Ethnicity Short Data Report](https://jobs.opensafely.org/staff/projects/114-ethnicity-short-data-report/) and [Ethnicity short data report](https://jobs.opensafely.org/staff/projects/ethnicity-short-data-report/) appear to be the same project.

We should probably merge the latter into the former (merge == move the workspaces and members over) since the former is already tied to an application so it's probably less work that way.

**Comment by ghickman** [comment]
@andrewscolm – which Org should be the primary org on the final project?

**Comment by andrewscolm** [comment]
I'd say DataLab

**Comment by ghickman** [comment]
Timings:
~2minutes to move the 3 workspaces over
~1 minute to remove the defunct project and fix the slug on the project we kept
