### ISSUE TITLE
Merge BRIT projects

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2281]
* Switch the application for [Project 16](https://jobs.opensafely.org/staff/applications/a6fe/) to the [correct project](https://jobs.opensafely.org/staff/projects/brit-antibiotic-research/), it was accidentally linked to [this unrelated project](https://jobs.opensafely.org/staff/projects/antimicrobial-stewardship-during-covid-19/).
* Move the workspaces and members from [amr_population_serv_eval](https://jobs.opensafely.org/staff/projects/amr_population_serv_eval/) to the [correct project](https://jobs.opensafely.org/staff/projects/brit-antibiotic-research/)
* Move the workspaces and members from [amr_repeat_abs](https://jobs.opensafely.org/staff/projects/amr_repeat_abs/) to the [correct project](https://jobs.opensafely.org/staff/projects/brit-antibiotic-research/)
* Move the workspaces and members from [hosp_os_brit](https://jobs.opensafely.org/staff/projects/hosp_os_brit/) to the [correct project](https://jobs.opensafely.org/staff/projects/brit-antibiotic-research/)

**Comment by Jongmassey** [comment]
Looks right to me

**Comment by ghickman** [comment]
Timings:
~ 10 minutes to dig through all the projects from the RepoDetail view to checking the application in The Spreadsheet
~15 minutes to move the application and workspaces.

**Comment by ghickman** [comment]
Some missed actions, for each of the 3 projects listed above:
* Create a redirect pointing to [Project 16](https://jobs.opensafely.org/staff/projects/brit-antibiotic-research/)
* Delete the project

The redirects and deletions were done in the console.  If we have many more of these I think we can probably invest a bit of time into a merge button/command to speed this up.
