### ISSUE TITLE
Display `action name` and `run_command` on the Job Detail template

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/job-server#2312]
Simon raised that it would be useful to have these two pieces of information visible on the page.

**Comment by bloodearnest** [comment]
run_command is not explicitly sent from job-runner

However, jobs-server has it already, as part of the cache project.yaml for this job request

Perhaps it could pull out the action from the project yaml and display that yaml fragment? and/or deeplink into the github commit's project.yaml?

**Comment by bloodearnest** [comment]
run_command is not explicitly sent from job-runner

However, jobs-server has it already, as part of the cache project.yaml for this job request

Perhaps it could pull out the action from the project yaml and display that yaml fragment? and/or deeplink into the github commit's project.yaml?
