### ISSUE TITLE
Change "View Project" to "Review Project"

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2325]
@tomodwyer – this button is currently using an outline, but we do want folks to use it to update their project's status.  Should it be a primary/success/something else button instead?

![](https://p198.p4.n0.cdn.getcloudapp.com/items/yAuQp8bg/f1dfef01-64c1-4621-9acb-d1cda3029381.jpg?v=d143e149c9e37a4cb1f4ae7546586301)

**Comment by tomodwyer** [comment]
Agreed, I think we go with a primary button.

Is there any way we could should the user the current project status above that button?

**Comment by ghickman** [comment]
We can definitely add that 👍
