### ISSUE TITLE
Add workspace purposes to sign off page

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2326]
@tomodwyer – we want users to update the purposes of their workspaces.  Initially because they won't have them set (we only introduced the field a couple of weeks ago), but going forward they ideally still need to review them.

Do you think adding a row between workspace and project (or maybe elsewhere in the list?) with the current purpose and a button to edit it would make sense? 

![](https://p198.p4.n0.cdn.getcloudapp.com/items/RBuZo6Wk/1e47836f-2b9e-4941-8c1a-0a2920ad5697.jpg?v=ba44ce80d3b649f7588ec4cfcce26109)

**Comment by ghickman** [comment]
@tomodwyer – something like this?

![](https://p198.p4.n0.cdn.getcloudapp.com/items/WnuDLAA1/202b4e22-810b-4c3b-b573-e197c0cec651.jpg?v=a5353dc3e76fe0a6cf5fc85aca3f1385)

**Comment by tomodwyer** [comment]
Yeah that works for me! I can figure out something nicer in the restyle, but that will at least show it to the user, and make clear if it's blank 👍
