### ISSUE TITLE
Invalid workspace name

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2327]
On Friday 11th Nov, Linda asked for [a workspace](https://jobs.opensafely.org/datalab/covid-19-related-death-over-time/covid-19%20mortality%20over%20time%20-%20ons%20deaths/) to be deleted that was giving her an error when running jobs
🧵 https://bennettoxford.slack.com/archives/C33TWNQ1J/p1668158987363669

🐛 It should not be possible to create workspaces in job server with incorrect names.
🐛 [This error](https://sentry.io/organizations/ebm-datalab/issues/3732835757/?project=5443358) is appearing in sentry for this workspace
🧹 Linda's workspace has an event log that needs to be moved before deleting. (Note: there might be other solutions to this problem)

**Comment by ghickman** [comment]
I've fixed up this data in production:
* JobRequest moved to the [correct workspace](https://jobs.opensafely.org/datalab/covid-19-related-death-over-time/covid-mortality-over-time-ons-deaths/)
* Redirect created to point the broken name URL to the correct workspace
* Deleted the workspace with the broken name
