### ISSUE TITLE
Provide a "Historic job runs" link from Job Server to Honeycomb

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2361]
Provide a "Historic job runs" link from Job Server into Honeycomb, so it’s easier to see the performance changes for a given ~Job~ Action over time.

This will help us identify any regressions in our code, such as for [this recent incident](https://docs.google.com/document/d/13rmpZViQoiN4FwfEDuUs96QrQc3ay6XsJeyzWFKBbbc/edit#), and regressions in researchers' code.

**Comment by ghickman** [comment]
By job do you mean `action` here?

**Comment by lucyb** [comment]
Yep..

**Comment by madwort** [comment]
@lucyb clarification/verification - same `action` name in the same workspace? not same `action` name across all workspaces?

**Comment by madwort** [comment]
what I'm thinking is for it to look like this: https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner/result/6SFBdfPiED5 (this one is interesting because it runs very quickly every week, but twice in the last month it has run very slowly)

**Comment by madwort** [comment]
![Image](https://user-images.githubusercontent.com/2082895/203609431-620cd2f0-c618-4bab-a1c9-aa88d450e3af.png)

**Comment by bloodearnest** [comment]
It actually just ran twice, the other spans are from the `tick` traces that were emitted every ~10s  whilst it was running, hence the bimodallity.

adding `tick does not exist` to the WHERE fixes it.

https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner/result/DHGJzeofgCm
