### ISSUE TITLE
Project 12

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2373]
Application: https://jobs.opensafely.org/staff/applications/2b8a/

Title: Investigating events following SARS-CoV-2 infection

Projects:
* https://jobs.opensafely.org/university-of-bristol/post-covid-events/ (use this as the new one)
* https://jobs.opensafely.org/university-of-bristol/post-covid-bristol/
* https://jobs.opensafely.org/university-of-bristol/post-covid-neurodegenerative/
* https://jobs.opensafely.org/university-of-bristol/post-covid-vaccinated/
* https://jobs.opensafely.org/university-of-bristol/post-covid-unvaccinated/

To find:
* ~Project(s)~
* ~Workspace(s)~
* Member(s)
* ~Repo(s)~

**Comment by ghickman** [comment]
@LiamHart-hub – all done.  Please tell Venexia to keep an eye out for anything odd in their workspaces, permissions, etc in case we've missed something.

**Comment by LiamHart-hub** [comment]
Will do. 

Thanks George for actioning this.
