### ISSUE TITLE
Right-click style preference on new template

### ISSUE THREAD

**Issue by madwort** [opensafely-core/job-server#2378]
So this isn't a bug, more like me not liking the style, but... 

How to replicate:

* hover honeycomb link
* right click & open in new tab
* move mouse away
* link remains in focused state
* click elsewhere on the screen
* link returns to default state

https://user-images.githubusercontent.com/2082895/203840930-847cda8d-da02-4f59-921d-247af8e645b7.mov

**Comment by madwort** [comment]
@tomodwyer ah, ok, the behaviour that I'm used to for links (e.g. Guardian & Twitter) is:

default style - default style
hover style - highlighted style
focus style - default style

and we currently have

default style - default style
hover style - highlighted style
focus style - highlighted style

so, right clicking a link has the appearance of the style "going back to normal", although it has actually latched to focus.

**Comment by madwort** [comment]
how about lfgss.com style? 

https://user-images.githubusercontent.com/2082895/207640098-ba860a5f-11a4-4612-90f2-1d7f7feef633.mov

**Comment by tomodwyer** [comment]
I think I’ve finally figured out what is the odd bit here, it’s Chromium versus Firefox. On Chromium, when you select the link, it will add the `::selection` pseudo class to the link (see attached video), which then adds a clear focus to the link. In Firefox, it doesn’t (as per your video).

So we need something to show when the selection pseudo class isn’t added.

https://user-images.githubusercontent.com/24863179/208880343-b3522bc0-deff-4043-949e-e8819895678a.mp4
