### ISSUE TITLE
Add question to application form

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2379]
Request from Amir. NOTE: Catherine needs to report back to Amir on decision

Text box with heading ‘ Commercial involvement’ with text saying something like "Are you funded by a company? If so, does the commercial organisation expect to edit the results, please specify" - to be added just below the contact information at the top of the form (exact wording to be clarified)

**Comment by ghickman** [comment]
Could we clarify:
* how many fields this involves?  (It sounds like at least 2)
* should this be on its own page?  (It feels a bit weird to have it on the very first page of the application form)

**Comment by CLStables** [comment]
Do the answers to either of those questions affect how easy/difficult it is to do? We can explore with Amir but we didn't want to work out all the detail until we knew what was likely to be accepted into the team's backlog...

**Comment by ghickman** [comment]
Both questions will affect difficulty but it's hard to give a definitive on acceptance until we know the answer I'm afraid.

**Comment by CLStables** [comment]
**Response from Amir:**
Can we have it as the page after contact details?
Heading: Commercial Involvement
Text wrapper: "Please specify if you have any industry/commercial involvement in your project, including funding. Also, specify if the funder expects to have involvement in the protocol design, early sight of results and / or input into the manuscripts/reports"
Single text box for their answer
