### ISSUE TITLE
Add a checklist at the end of the application form

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2380]
## WARNING: this description is obsolete -- please see long comment from Liam on 15 Dec

Request from Amir. How difficult would this be to do? Are there alternatives? NOTE: Catherine needs to report back to Amir on decision

-----
At the end of the application as part of the COMPLETION OF STUDY PAGE: 
Adding a checklist with tickboxes (if possible - this makes it more likely they will read it) and the following wording:

All applications

*All sections to be completed if not your application will be rejected 

**Contact details**- All sections completed including mobile number and organisation.
**Study Information**- Study name and purpose to be fully completed with clear evidence of a Covid-19 related purpose. 
**Study Purpose**- Simple lay description provided of no more than 300 words with your project meeting at least one of the topic areas listed. Study lead to be listed too.
**Completion of the full research team** All researchers listed in the researcher section who will write code and/or access the results server must have a completed  Data Access Agreement form and returned to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox. Additionally researchers requesting access to the results server must have passed a safe researcher course and the date passed filled in. 
**Completion of the Getting Started Tutorial** needs to be finished at the point of application submission

For Research

**Type of study**- If your study meets a research focus, evidence of an HRA favourable opinion sent to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox. 
**Confirmation of support of your study** from both the principal investigator and line manager detailing that they have read application Study Information and Study Purpose, and our Opensafely Principles to be sent to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox. 

For Service Evaluation/Audit

**Confirmation of HRA Decision tool** to be completed [http://www.hra-decisiontools.org.uk/research/docs/DefiningResearchTable_Oct2022.pdf](http://www.hra-decisiontools.org.uk/research/docs/DefiningResearchTable_Oct2022.pdf.), and sent to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox. 
**Confirmation of support of your study** from both the sponsor and line manager detailing that they have read application Study Information and Study Purpose, and our OpenSAFELY principles to be sent to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox.

**Comment by lucyb** [comment]
@CLStables We're not sure that it's a good idea to have DAAs signed and submitted before an application is submitted (never mind) approved. This is a significant change to our current process, where we assume that anyone with a signed DAA has a legitimate reason to access the backends.

**Comment by CLStables** [comment]
Good point - I think some of these items need to come later (and an email would be great, but feels like that would be more difficult?). But some of them need to come before the project is approved. Would the actual adding of a checklist be straightforward or not? Thanks!

**Comment by ghickman** [comment]
Adding a checklist is relatively straightforward, we can also pick which checklist once we know the type of study.

**Comment by CLStables** [comment]
The IG team have confirmed that they definitely want this checklist at the end, and have provided updated text (I have modified the top comment to reflect this)

**Comment by CLStables** [comment]
We also had a [conversation in Slack](https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1671792850975109) around the concern over whether signing DAAs prior to application submission/approval would cause a major change to our process, but we came to the conclusion that it wouldn't.

**Comment by CLStables** [comment]
I've just spotted a new request in the IG team's doc: "Once the application checklist has been inserted at the bottom of the application form, please can we then add a text box to enable applicants to insert their github url into the researcher profile located at the bottom of the page." (the current process is that each user has to email that to Amir...)
I think that's actually completely separate to the application checklist and should be a separate issue - do you agree @ghickman?

**Comment by ghickman** [comment]
@CLStables – yep that's a separate issue, but it would definitely be useful to collect!

**Comment by CLStables** [comment]
I've added it as a new issue - thanks!

**Comment by LiamHart-hub** [comment]
UPDATED WORDING OF ORIGINAL REQUEST: 

As the applicant works their way through the Job Server application, they are notified of different tasks that they must complete depending upon the section they are working on and the type of study they are submitting. At points, these additional tasks require documents to be sent to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox, for example, which is often forgotten and requires a reminder to be sent. As a solution, similar to our PDF copy of our application form, we require a checklist to be presented at the point the applicant submits their application reminding them of the remaining activities which has been captured below:


All applications
*All sections to be completed if not your application will be rejected 

1. Contact details- All sections completed including mobile number and organisation.
2. Study Information- Study name and purpose to be fully completed with clear evidence of a Covid-19 related purpose. 
3. Study Purpose- Simple lay description provided of no more than 300 words with your project meeting at least one of the topic areas listed. Study lead to be listed too.
4. Completion of the full research team All researchers listed in the researcher section who will write code and/or access the results server must have a completed  Data Access Agreement form returned to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox. Additionally researchers requesting access to the results server must have passed a safe researcher course and the date passed filled in. 
5. Completion of the Getting Started Tutorial needs to be finished at the point of application submission

For Research

1. Type of study- If your study meets a research focus, evidence of an HRA favourable opinion sent to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox. 
2. Confirmation of support of your study from both the principal investigator and Line Manager detailing that they have read application Study Information and Study Purpose and our [Opensafely Principles](https://www.opensafely.org/about/). Send the confirmation to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox.

For Service Evaluation/Audit

1. Confirmation that the study is not research, for example, either by completion of the HRA Decision toolkit, https://www.hra-decisiontools.org.uk/research/; or providing a note from your institutional ethics committee confirming the study is a service evaluation/audit. Send the evidence to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox. 
2. Confirmation of support of your study from both the sponsor and line manager detailing that they have read application Study Information and Study Purpose, and our [OpenSAFELY principles](https://www.opensafely.org/about/). Send the confirmation to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox. 


For Short Data Reports

1. Confirmation that the study is not research, for example, either by completion of the HRA Decision toolkit, https://www.hra-decisiontools.org.uk/research/; or providing a note from your institutional ethics committee confirming the study is not research, a service evaluation or an audit. Send the evidence to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox. 
2. Confirmation of support of your study from your line manager (which could be a principal investigator you work with) detailing that they have read application Study Information and Study Purpose, and our [OpenSAFELY principles](https://www.opensafely.org/about/). Send the confirmation to the [applications@opensafely.org](mailto:applications@opensafely.org) inbox.

**Comment by StevenMaude** [comment]
I've spent a little bit of time looking at this today.

But I'm not completely sure of what's required, and think it can be potentially more gnarly than it looks, depending on the implementation.

* Is it OK for the applicant to *always* confirm everything is done, before a new submission, or returning to the form.
  * That is: *the state of the checked boxes doesn't need to persist* for an application.
* Or, is the checklist an integral part of the application, where its state is also preserved as part of the application?
  * This is potentially more complicated because the study type could potentially be changed during the application. Is it OK for a user to have to tick all the boxes again, if they tick some of them, and later revisit the form?
* Less important: short data reports aren't an option in the current form (as I have the code checked out, at least).

**Comment by benbc** [comment]
@StevenMaude The lastest request here is for a static list, just as reminder to researchers, not a way of recording which things on the list have and have not been completed.

**Comment by LiamHart-hub** [comment]
Thanks @benbc for bringing this up. Do include me in the ticket for when Short Data Report is added to Jobserver, so I can get the notification to update the PDF copy of the application form.
