### ISSUE TITLE
Allow applicants to upload files to the application

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2382]
Request from Amir. How difficult would this be to do? Are there alternatives? NOTE: Catherine needs to report back to Amir on decision

I am assuming that this will be part of a future initiative, but want to check with the team before parking it...

**Comment by lucyb** [comment]
@CLStables Might need to consider data protection.. what is going to be contained within the files and is job server the right place for them? Will need to consider retention periods, ability to delete and having backups. Is there a better place to store them? Not a trivial thing to do

**Comment by CLStables** [comment]
Thanks. I will move this back into another initiative.
