### ISSUE TITLE
Limit study purpose field to 300 words

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2383]
Request from Amir. How difficult would this be to do? Are there alternatives? NOTE: Catherine needs to report back to Amir on decision

Add text box word count to the ‘Study Purpose’ project description to not go beyond the allocated 300 words that we allow for project descriptions.

**Comment by lucyb** [comment]
A character limit, rather than a word limit would be easier. We'd need to create a custom validation rule for a word limit.

Otherwise, should be straight forward to add validation in the form and on the server. Will need Tom O's contribution for the styling though.

**Comment by lucyb** [comment]
Catherine has confirmed with Amir that a character limit is fine. We can assume 5 characters per word (plus whitespace).
