### ISSUE TITLE
Add additional fields to research ethics page of application

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2384]
Request from Amir. How difficult would this be to do? Are there alternatives? NOTE: Catherine needs to report back to Amir on decision

Add to text and create text boxes - need confirmation from Amir that he is happy with the proposed changes HRA Approvals 6-rubric
https://github.com/LiamHart-hub/job-server/blob/main/snippets/6-rubric.md

Suggestion to add on the following text
“If you are yet to complete a HRA application, please refer to the following link for guidance https://www.myresearchproject.org.uk/help/hlpfaqs.aspx

If you have completed an application, please use the following text boxes and insert link to upload a copy of your HRA/Ethics application if completed

Insert text boxes : REC Name
: REC Reference Number
: Date submitted”

**Comment by ghickman** [comment]
It's unclear which page these changes are for.  `6-rubric.md` is used on the Type of Study page, should it be that one?

**Comment by CLStables** [comment]
This has been passed to Liam as it only requires some text changes
