### ISSUE TITLE
Add radio button to service evaluation audit page of application

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2385]
Request from Amir. How difficult would this be to do? Are there alternatives? NOTE: Catherine needs to report back to Amir on decision

Request:
Insert tick button onto service-evaluation audit rubric
https://github.com/LiamHart-hub/job-server/blob/main/snippets/service-evaluation-audit-rubric.md

[Insert tick button]
Yes, I am a member of the Bennett Institute/LSHTM conducting a study conforming to the Service Restoration Observatory and Aftershocks workstream

**Comment by ghickman** [comment]
It's unclear why we need this, could we work that out before we look at specific controls to add?

**Comment by CLStables** [comment]
It's because the paperwork Amir needs is different if the project sits under one of those workstreams vs. other projects that don't. He wants a way to quickly tell if a project is one of these special cases or not. Does that help?
