### ISSUE TITLE
Remove CMO priority content from application

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2386]
Request from Amir.

Remove completely as it's no longer relevant to the application - CMO Priority
Remove the following rubric as it's no longer applicable according to COVID research guidelines
https://github.com/LiamHart-hub/job-server/blob/main/snippets/9-fieldset0-is_on_cmo_priority_list-label.md

**Comment by lucyb** [comment]
This should be fairly easy to do.

We can remove it from formspec and it should be removed from final validation. It should already be a nullable field.
