### ISSUE TITLE
Allow applicants to download a version of the blank application form

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2387]
Request from Amir. How difficult would this be to do? Are there alternatives? NOTE: Catherine needs to report back to Amir on decision

example text: Please have a look at this PDF of the form with all the questions asked before you start your application

**Comment by lucyb** [comment]
It's already possible to download a copy, once an application has been created with the user's contact details, a PDF can be generated and printed.

**Comment by CLStables** [comment]
From a discussion on Slack: while it's possible to download a PDF currently that doesn't contain all the explanatory text from each page that the researchers would need. One possible solution is for the content to be duplicated into a separate PDF/Word doc and users can download that prior to starting their application. Having the content in two places risks them becoming out of sync, but as long as the IG team can manage that through process then it seems a reasonable short-term solution. I will take it to them as a suggestion...

**Comment by CLStables** [comment]
The IG team have agreed that they will manage the creation of a PDF version (they are probably going to do this by taking screenshots of the application page-by-page), adding that to the first page of the application process, and also manage updating that file when necessary. If they get stuck they will ask for help.
