### ISSUE TITLE
OpenSAFELY Application ownership transfer 

### ISSUE THREAD

**Issue by LiamHart-hub** [opensafely-core/job-server#2436]
Hello, 

Can I have help transferring an OpenSAFELy application over to an applicant who at the time created a paper application. which I copied into a digital application?

At the time of creation, he didn't have a GitHub ID which he has now supplied me with.

The following applicant this concerns is Michael Parker who needs ownership transferred over to him on the below application
https://jobs.opensafely.org/staff/applications/3414/
GitHub ID https://github.com/parkerm98

Do let me know if you require any further information. 

Thanks, 

Liam

**Comment by ghickman** [comment]
@LiamHart-hub – easy enough for us to do, but can you get the applicant to sign up to job-server first so we can make the please.

Once this is done we can transfer over the application.

**Comment by LiamHart-hub** [comment]
Of course. 

I will get this actioned now.

**Comment by LiamHart-hub** [comment]
Hello George, 

The applicant has now signed up to the job server and you should now be able to make the transfer over. 

Thanks :)

**Comment by ghickman** [comment]
I've switched the application owner over to the requested one.

**Comment by LiamHart-hub** [comment]
Thanks George. Much appreciated.
