### ISSUE TITLE
Changing status of application

### ISSUE THREAD

**Issue by LiamHart-hub** [opensafely-core/job-server#2437]
Hello, 

The following application currently has a 'approved' status, but the below application needs to have its status changed to 'deferred'.

https://jobs.opensafely.org/staff/applications/514a/

As expressed in the application for extra detail - "DEFERRED UNTIL permanent legal basis resolved and PPIE group consulted as project is industry application".

Do let me know if there is an issue changing the status. If no 'deferred' status is currently available, please can we have one implemented as we may come across this more and more. Amir primarily requested for this application status to be changed, and for the deferred status to be implemented if it doesn't exist. 

Many thanks :)

**Comment by ghickman** [comment]
We don't have a deferred status but adding one is easy enough.

**Comment by ghickman** [comment]
@LiamHart-hub – This is all done now.  The linked application has been given the deferred status, and it looks like someone has already set the description field with what's needed.  You'll be able to use this status for any other application as needed too 👍

**Comment by LiamHart-hub** [comment]
Thanks George, that's great!
