### ISSUE TITLE
For jobs, use the identifier supplied by job-runner rather than an internal id

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#244]
We're still using Job.id around the UI, including in URLs.  Job.identifier is a more stable string with the current method of updating Jobs via the API, let's use that instead.

Should we swap out Job.id for Job.identifier?

**Comment by sebbacon** [comment]
Makes sense to me

**Comment by ghickman** [comment]
We're now using this around the UI everywhere.
