### ISSUE TITLE
User management in the Staff Area

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2489]
We need to understand how new users will be created in OSI and how to manage users.

We'll be creating a new staff area https://github.com/opensafely-core/interactive.opensafely.org/issues/434 that will allow us to be more flexible with the UI. We're also adding in projects https://github.com/opensafely-core/interactive.opensafely.org/issues/435.

We expect that we may want to create new users as part of creating a project or as part of editing an existing project.

Will we also want to create users separately? This may be useful if we want to add them to multiple projects.

We also know that staff members should be able to:
1. Edit the display name for a given user
2. Give them staff privileges, if appropriate
4. Disable a user account
5. Delete a user account (does this need separate consideration?)

When a new user is created, an email should be sent out automatically with a link that prompts them to set a password (note: this functionality already exists but may need to be updated).

**Comment by ghickman** [comment]
Done in #2468
