### ISSUE TITLE
Write the report code to a commit

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2494]
The output of a AnalysisRequest form submission is a commit in the relevant interactive repo (`<project slug>-interactive`).  We already have the code for this from v1 and it should be possible to copy nearly all of that code into v2.

TBD: whether this code lives in job-server or a new service.

**Comment by lucyb** [comment]
I spoke with @bloodearnest this afternoon and looking at the output from the [SPIKE about moving the analysis code into a resuable action](https://github.com/opensafely-core/interactive.opensafely.org/issues/465). We concluded that Louis' analysis/report code should live in a separate repository in the opensafely-core organisation. It's not appropriate to be a single reusable action, although there's scope in the future to move some of the steps into reusable actions or to create our own internal-only reusable actions, if the analysis/report code grows significantly.

Most of the code from the original interactive.submit.py can be moved over as part of this ticket. The main change is that it will be cloning the new opensafely-core repo and writing a commit based on that into the relevant interactive repo (<project slug>-interactive).

The Interactive bot will be used to hold the PAT with the GitHub permissions needed to do this. This is separate to the current Job Server token for interacting with GitHub.

The code will initially live in job server but it's expected that we'll move it into a new service soon.

An ADR should be written as part of this ticket.

This ticket is linked to/dependent on: https://github.com/opensafely-core/job-server/issues/2498

**Comment by ghickman** [comment]
Done in #2609
