### ISSUE TITLE
List previous analysis reports

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2499]
Any given project can have N AnalysisRequests, each with 0 or 1 related reports.

We need to find a way to surface those for returning users.

One option is to have the homepage for interactive users be just their analysis requests and reports.

**Comment by ghickman** [comment]
From Brian in #2724:

> As a user I'd like to be able to see previous analysis I have requested/run.

> At the moment if you enter via the login you cannot see your analyses - you must go back to your emails to find the correct url. Adding "analysis history" to a users account would be the obvious solution - maybe eventually it might be part of the home screen when you login?

> My experience is that over time the usefulness of having something like this increases.

> In week after I run an analysis I can normally find my analysis in email/slack. Longer it goes I find it difficult to find and tempted to request the analysis again!

**Comment by lucyb** [comment]
Has this now been done?

**Comment by ghickman** [comment]
Nope, just waiting on a review for #2537 :)
