### ISSUE TITLE
Handle DAAs for Interactive users

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2504]
Existing users are required to sign a DAA so they can request code is run on the appropriate backend(s), as specified in the DAA they sign.  We've implemented this via the BackendMembership object, which we check when accessing the CreateJobRequest form.

For v1 OSI used the API to create JobRequests, which allows the calling service to pick which backend is used.  Since this API was only called via the trusted `interactive-bot` user this was fine (and working as designed).

For v2 OSI users are now User objects inside job-server and as such should be the objects attached to the JobRequests we create.  Currently we don't create any BackendMemberships for a user in the form created in #2468, so User objects will have an error/warning on their detail page in the staff area saying they're missing this.

TBD:
* Should we give BackendMemberships to Interactive users?
* If so, do they sign the DAA as normal?

**Comment by lucyb** [comment]
Has this been solved by not requiring them to have any BackendMemberships? The DAA part can be handled by the IG process without any job server changes, I think now?
