### ISSUE TITLE
Improve database backups

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2510]
Digital Ocean provide point in time recovery for any postgres database for up to 7 days. However, we should have [12 months worth](https://bennettoxford.slack.com/archives/C63UXGB8E/p1673885442209289?thread_ts=1673885052.461809&cid=C63UXGB8E) of data available to restore from, if needed.

Digital Ocean have recently bought a tool, [SnapShooter](https://www.digitalocean.com/community/tools/daily-digitalocean-backups-snapshooter) that would be worth investigating.

Acceptance Criteria:
* A documented backup policy (could be an ADR or page in the team manual)
* Weekly backups of the Job-Server database to DO Spaces, stored for 12 months (the deletion of backups could be a separate ticket)

**Comment by madwort** [comment]
DigitalOcean does not support DO Spaces in the London `LON` region, so using the Frankfurt `FRA` region.

**Comment by madwort** [comment]
bah, SnapShooter Serverless is "unavailable via market place purchasing", I'm contacting support as they suggest

**Comment by lucyb** [comment]
That looks really promising! I like that the $49/mo option allows us to backup basically everything we would need to in DO (like the rest of the db cluster, the files on jobserver, etc).

We should confirm with @sebbacon that the cost is okay (although, [he's indicated](https://bennettoxford.slack.com/archives/C63UXGB8E/p1673885442209289?thread_ts=1673885052.461809&cid=C63UXGB8E) that it probably is). We should also check that we can store backups outside of the UK but inside the EU and that the lack of encryption won't be a problem. Is the droplet that jobserver runs on at the moment encrypted-at-rest? I'm wondering about the released (but not published) files on there, as well as the github access it has.

Also, could you try out a restore and (briefly) document the steps, please?

**Comment by madwort** [comment]
> Is the droplet that jobserver runs on at the moment encrypted-at-rest?

No, the droplet's disk is not encrypted at rest, according to [this answer](https://www.digitalocean.com/community/questions/droplet-native-storage-is-it-encrypted-similarly-to-block-storage-volumes) from 2019, but if we were to switch to using a separate Volume & mounting that into the Droplet it [apparently would be](https://www.digitalocean.com/community/tutorials/how-to-create-an-encrypted-file-system-on-a-digitalocean-block-storage-volume), or obviously we could use an encrypted filesystem. So, I don't think that not encrypting our backups would not be a regression from where we are now (although maybe we could be doing more). 

> could you try out a restore

There's a few options for restoring, the SnapShooter has a wizard interface, which I'm slightly hesitant to try out on the production site until we actually need to. I'm attempting to load the backup into a local postgresql server, but it's just a standard SQL file from pg_dump so I'm confident that it'll work. 

> (briefly) document the steps, please?

The wizard interface I haven't tried & doesn't seem to be documented by SnapShooter, although they do document [the standard kind of pg_restore steps that we use elsewhere when we need to move dbs around](https://snapshooter.com/learn/postgresql/pg_dump_pg_restore#guide-to-pg-restore-restore-command) so I don't think we need to do much other than leave a note as to where to find the backups - perhaps in the ebmdatalab/sysadmin repo (as that documents the rest of the infrastructure?
