### ISSUE TITLE
Make it easier for people to navigate back to existing applications

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2518]
See 🧵 https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1674062655051209

I received some feedback from @LiamHart-hub that some users are finding it difficult to locate their existing application in Job Server and so they're starting a new one instead of going back and editing an existing one. I think this might be because the URL we're giving to them, https://jobs.opensafely.org/apply/, automatically sends them to start a new application and generally it's quite hard to find existing applications in Job Server.

As a Small Change :tm: , it's been suggested by Brian that we put a button near the top of that page that says something like "continue a previous application" and that links to https://jobs.opensafely.org/applications/. It will need to be fairly obvious to stop someone from scrolling past it though.

**Comment by LiamHart-hub** [comment]
Yes, a button that allows applicants to clearly see a "continue a previous application" button at the top would be helpful
