### ISSUE TITLE
Add link to job request from logs pages

### ISSUE THREAD

**Issue by madwort** [opensafely-core/job-server#2520]
Looking at pages such as https://jobs.opensafely.org/event-log/ and https://jobs.opensafely.org/university-of-nottingham/postopcovid/postopcovid/logs/?q=xe2reivqosvzs5qh - the results table has a link to the [workspace](https://jobs.opensafely.org/university-of-nottingham/postopcovid/postopcovid/), and if you show jobs to the job pages eg. [job page](https://jobs.opensafely.org/university-of-nottingham/postopcovid/postopcovid/14254/yctjbossvichzaee/). It would be useful sometimes to have a direct link to the [job_request page](https://jobs.opensafely.org/university-of-nottingham/postopcovid/postopcovid/14254/), rather than having to go via the job page.

**Comment by ghickman** [comment]
I think you've already covered this in #1838, and arguably #253 also covers it!

**Comment by madwort** [comment]
doh! closing as duplicate!
