### ISSUE TITLE
Move objects under Project-91

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2523]
[Slack 🧵](https://bennettoxford.slack.com/archives/C010SJ89SA3/p1674172550541579)

We can potentially rebrand [this project linked in the thread](https://jobs.opensafely.org/staff/projects/antibody-and-antiviral-deployment/) as 91, fixing the title, slug, and linking the application to it.

Other workspaces to move:
* [ ] https://jobs.opensafely.org/datalab/antibody-and-antiviral-deployment/paxlovid_sotrovimab/

Todo:
* Get a definitive list of other workspaces

**Comment by lucyb** [comment]
Waiting to hear back from Amir about the information needed to complete this.

**Comment by ghickman** [comment]
Dealt with in the data improvment iniative.
