### ISSUE TITLE
Better copilot support

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2524]
Our project model currently tracks:
* the copilot if a project has one
* when the copiloting window ends for a project
* any copilot notes

Lisa and Brian would like us to add a status field (completely reasonable!) to help them track where a project is for copilots with the following options:

* Not required
* Awaiting assignment
* Awaiting start date
* Active
* Follow up

This is also a good time to review how we model and support copilots on job-server.  Would an M2M through model make better sense here?  Should we require some fields are set when a copilot is added?  Is it all fine as it is?

[Slack 🧵](https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1674216061202629)

**Comment by lucyb** [comment]
I don't think we're going to have time to do this until after SACRO, so I'm removing it from the board. Please put it back into triage if you disagree.
