### ISSUE TITLE
Change repository visibility tweaks

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2528]
#### Read and agree section
* [ ] Add `for each workspace` to the end of `Added or updated the purpose`
* [ ] Add help text to WorkspaceEdit's purpose field with `Describe the purpose of this workspace.  To update your project details, please go to [your project page]`, linking to the ProjectDetail page.

#### Other branches section
* [ ]  `This repo has additional branches that are not attached to workspaces (therefore have not been run against patient data). Their README files must be updated to match the OpenSAFELY guidance [hyperlink].`

#### Project section
* [ ] Tweak the working and layout of this section to match:

This GitHub repository is linked to the [X project]. Before changing the repository visibility to public, please check that the project status and status description are correct and meet these requirements [link to docs page about project status updates].

Current status:
Current status description: (Missing OR content…)

Button: [Edit details]

#### Final sign off section
* [ ] `s/technical support/team/`

#### Project edit page
* [ ] Add help text to the status description field with `This must include links to preprints, journal publications or other websites that host your work, if they exist. For more details see the OpenSAFELY documentation [link to project status docs].`

**Comment by CLStables** [comment]
Note that the screenshot on [this page](https://docs.opensafely.org/jobs-site/#updating-project-status) should be updated once you've changed the "project edit page"
