### ISSUE TITLE
Surface JobRequestDetail page with fewer clicks

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#253]
The JobRequestDetail page is a useful debugging tool, but likely not that interesting to end users.  It's a bit of a faff to get to currently, you have to do WorkspaceLogs -> View Job -> JobRequest.

This could be easier.

**Comment by sebbacon** [comment]
Suggestion: instead of "view" buttons, make them the links here in the log listing (with a hover state with "debug info" or something as a hint of what to expect?)

![image](https://user-images.githubusercontent.com/211271/101179707-7f838800-3642-11eb-8d40-f429a99898df.png)
