### ISSUE TITLE
Hint what to do next when errors are logged

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/job-server#259]
Specifically, "job exited with an error code" should somehow prompt that for security reasons the error can't be published & the user needs to log into the L4 server and inspect the `metadata/` folder.

This message would be identical (or could be constructed from an identical template) for every such error. Perhaps a tooltip?

**Comment by ghickman** [comment]
@evansd – is this something job-runner could add to its error messages?  I'm wary of parsing error messages from another code base when we already render whatever we send!

**Comment by evansd** [comment]
We already set a `nonzero_exit` status code (see [here](https://github.com/opensafely/job-runner/blob/b368809bad04b25dd1d4be2c3be139d146551c8e/jobrunner/models.py#L35)) but I think we're not yet returning those in the API. So the thing to do would be to extend the API and Job model to include those.

**Comment by bloodearnest** [comment]
Bear in mind that the instructions for accessing L4 will vary depending on
backend.

**Comment by ghickman** [comment]
> We already set a nonzero_exit status code

Those will definitely come in handy to add explainers.

> the instructions for accessing L4 will vary depending on backend.

Ahh, yes, that settles it as a job-server task to me, since it's cross-backend and we know the backend-context of a Job.

**Comment by ghickman** [comment]
We have these status codes:

* `waiting_on_dependencies`
* `dependency_failed`
* `waiting_on_workers`
* `nonzero_exit`

The only one I'm not sure about the flow for is `nonzero_exit` since users will need to access the server to do so.  @evansd or @bloodearnest could you lay out the expected flow please? (I'm happy to convert to help text if you want)

Does the flow for `nonzero_exit` change for EMIS?

**Comment by evansd** [comment]
The basic message we want is:

> The job exited with an error. You can check the log output by logging into the TPP/EMIS server and looking at:
>
>     <workspace_parent_dir>/<workspace_name>/metadata/<action_name>.log

We can populate the workspace and action name automatically from the job details and select the appropriate backend.

The `workspace_parent_dir` obviously depends on whether we're looking at TPP and EMIS, but it also varies depending on whether they're accessing the Level 3 or 4 server which we can't determine so I'm not quite sure what to do there. Maybe we just always use L4 and expect people with L3 access to know what to do.

**Comment by evansd** [comment]
Oh, also to say, we can and should add more of these status codes. The ones we have currently are just the minimum I needed to implement the local_run features I wanted. We definitely want an `output_missing` code and an `internal_error` code.

**Comment by sebbacon** [comment]
> Maybe we just always use L4 and expect people with L3 access to know what to do

Yes: very soon we'll be locking down L3 to "just us"
