### ISSUE TITLE
Where to notify output checkers

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2591]
OSIv1 created a ticket in `opensafely/interactive` and notified the `#opensafely-outputs` channel, linking to that ticket.

Should we do the same thing for v2?  Should we try to slot in with the current output checkers process?

**Comment by lucyb** [comment]
Job Server [has access](https://bennettoxford.slack.com/archives/C0441RRL3RC/p1678794295332769?thread_ts=1678794004.416189&cid=C0441RRL3RC) to the ebmdatalab organisation (unlike the GitHub token used in OSIv1), which means we can create the issue in the existing [output-checkers repository](https://github.com/ebmdatalab/opensafely-output-review/issues) and means the output-checkers are notified automatically in Slack.
