### ISSUE TITLE
Form validation schema

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2593]
What do we want to check in the form submission from the react app? and what format does the analysis code invocation function want the data in?

The form currently submits a JSON payload in this format:

```
{
  "frequency": "monthly",
  "codelistA": {
    "label": "Abdominal aortic aneurysm diagnosis codes",
    "organisation": "NHSD Primary Care Domain Refsets",
    "value": "nhsd-primary-care-domain-refsets/aaa_cod/20210127",
    "type": "codelist_event"
  },
  "codelistB": {
    "label": "Active and inactive ethnicity codes",
    "organisation": "NHSD Primary Care Domain Refsets",
    "value": "nhsd-primary-care-domain-refsets/ethnall_cod/20210127",
    "type": "codelist_medication"
  },
  "timeValue": "12",
  "timeScale": "months",
  "timeEvent": "before",
  "filterPopulation": "adults",
  "demographics": ["age"]
}
```

#### `frequency`
One of the following strings:
* `monthly`
* `quarterly`
* `yearly`

#### `codelistA`
`label`, `organisation`, and`value` are all valid values as returned from `get_codelists()`
`type` is one of the following strings:
* `codelist_event`
* `codelist_medication`

#### `codelistB`
`label`, `organisation`, and`value` are all valid values as returned from `get_codelists()`
`type` is one of the following strings:
* `codelist_event`
* `codelist_medication`

#### `timeValue`
A number.

Does this have upper and lower bounds?

#### `timeScale`
One of the following strings:
* `months`

#### `timeEvent`
One of the following strings:
* `before`
* `after`

#### `filterPopulation`
One of the following strings:
* `all`
* `adults`
* `children`

#### `demographics`
An optional list of strings:
* `age`
* `ethnicity`
* `imd`
* `region`
* `sex`

#### Analysis code schema
TBD

**Comment by tomodwyer** [comment]
> #### `codelistA`
>
> `label`, `organisation`, and`value` are all valid values as returned from `get_codelists()` `type` is one of the following strings:
>
> - `codelist_event`
> - `codelist_medication`

Some codelists listed currently do not have an organisation. All codelists have a `label` and `value`

If you would prefer, I can change the type to: `event` and `medication`?

> #### `timeValue`
>
> A number.
>
> Does this have upper and lower bounds?

Yes, it has to be greater than zero, and less than 5 years.

```js
// The following finds validation failures for 5 years
if (timeScale === "weeks" && value > 260) return false;
if (timeScale === "months" && value > 60) return false;
if (timeScale === "years" && value > 5) return false;
```

> #### `timeScale`
>
> One of the following strings:
>

- `weeks`
- `months`
- `years`

**Comment by ghickman** [comment]
> Some codelists listed currently do not have an organisation.

Let's ignore that, I have a feeling we're not going to pass it through anyway.

> If you would prefer, I can change the type to: event and medication?

Sure 👍

**Comment by LFISHER7** [comment]
Below are the parameters required for the analysis code.

**Codelists**

The codelists will be made available within the repo with fixed paths. We can get everything else from OpenCodelists

- `codelist_1_path` - str representing path to the codelist within the repo
- `codelist_1_column` - str representing the column name for the code column in codelist 1.
- `codelist_1_description` - str representing the name of the codelist (equivalent to `label`)
- `codelist_1_system` - str representing the coding system used for codelist 1.
- `codelist_1_type` - str representing codelist 1 type (equivalent to `type`)
- `codelist_2_path`
- `codelist_2_column`
- `codelist_2_system`
- `codelist_2_description`
- `codelist_2_type`

**Analysis options**

`codelist_1_frequency`, `codelist_2_period_start` and `codelist_2_period_end` can be calculated in the analysis code from `timeValue`, `timeScale` and `timeEvent`.

- `codelist_1_frequency` - equivalent to `frequency` from the form.
- `codelist_2_period_start` - str representing the number of days and direction of the start of the comparison period e.g "- 365"
- `codelist_2_period_end` - str representing the number of days and direction of the end of the comparison period e.g "+ 0".
- `population` - equivalent to `filterPopulation`
- `breakdowns` - comma delimited string of the options available in `demographics`

*Report*

- `report_title` - str representing the report title. We could name the report consistently using the other form inputs, or we could let this be user defined.
- `measure_description` - str representing the codelists and logic used to make a measure. This should be the same as the report request summary when submitting the form, and can be generated using the codelists `label` , `timeValue`, `timeScale` and `timeEvent`


Based on that, if we're assuming we'll get all the codelist parameters from OpenCodelists, the only thing missing from the form is `report_title` (if user defined).

**Comment by bloodearnest** [comment]
> Below are the parameters required for the analysis code.
> 
> **Codelists**
> 
> The codelists will be made available within the repo with fixed paths. We can get everything else from OpenCodelists
> 
> * `codelist_1_path` - str representing path to the codelist within the repo
> * `codelist_1_column` - str representing the column name for the code column in codelist 1.
> * `codelist_1_description` - str representing the name of the codelist (equivalent to `label`)
> * `codelist_1_system` - str representing the coding system used for codelist 1.
> * `codelist_1_type` - str representing codelist 1 type (equivalent to `type`)
> * `codelist_2_path`
> * `codelist_2_column`
> * `codelist_2_system`
> * `codelist_2_description`
> * `codelist_2_type`


Update on this: datateam have [made changes](https://github.com/opensafely-core/opencodelists/pull/1528) that means we can fix the code column header to always be `code`. So I think we don't need the two `_column` fields anymore.

> **Analysis options**
> 
> `codelist_1_frequency`, `codelist_2_period_start` and `codelist_2_period_end` can be calculated in the analysis code from `timeValue`, `timeScale` and `timeEvent`.
> 
> * `codelist_1_frequency` - equivalent to `frequency` from the form.
> * `codelist_2_period_start` - str representing the number of days and direction of the start of the comparison period e.g "- 365"
> * `codelist_2_period_end` - str representing the number of days and direction of the end of the comparison period e.g "+ 0".
> * `population` - equivalent to `filterPopulation`
> * `breakdowns` - comma delimited string of the options available in `demographics`
> 
> _Report_
> 
> * `report_title` - str representing the report title. We could name the report consistently using the other form inputs, or we could let this be user defined.
> * `measure_description` - str representing the codelists and logic used to make a measure. This should be the same as the report request summary when submitting the form, and can be generated using the codelists `label` , `timeValue`, `timeScale` and `timeEvent`
> 
> Based on that, if we're assuming we'll get all the codelist parameters from OpenCodelists, the only thing missing from the form is `report_title` (if user defined).

**Comment by ghickman** [comment]
React form, Django form validation, and study code are all now working together 🎉
