### ISSUE TITLE
Dates not formatted properly on "published" pages

### ISSUE THREAD

**Issue by wjchulme** [opensafely-core/job-server#2603]
On [this page](https://jobs.opensafely.org/datalab/opensafely-internal/tpp-vaccination-names/outputs/25/output/vaccination_names.html) the "published date" is reported as `Thu Dec 2022` -- see attached  image.

Doesn't seem to be a problem on other pages

![image](https://user-images.githubusercontent.com/25637345/217280973-e95bc17e-d3ca-4c07-8dbc-0cfc4572d34b.png)

**Comment by tomodwyer** [comment]
@wjchulme this is now fixed 🎉
