### ISSUE TITLE
Remove OSIv1 support

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2614]
To support v1 we added:

* an API endpoint, handled by the JobRequestAPICreate view
* a user, interactive-bot
* a role, `OpensafelyInteractive`

All of these, and any respective tests can go away once v1 is fully shut down.

**Comment by bloodearnest** [comment]
A comment: the jobrequest creation API endpoint was also planned to be used for `opensafely submit $action` type workflow in the future.
