### ISSUE TITLE
Serve dataset for co-piloting report

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2641]
The co-pilots generate a report semi-regularly to help them review how they're doing.

Currently we manually create a sqlite database for them using [db-to-sqlite](https://datasette.io/tools/db-to-sqlite).

This is both a manual process which interrupts members of the pipeline team, but also blocks @LisaHopcroft/the co-pilots from generating their report.

We'd like to provide the necessary dataset on the co-pilot's dashboard in job-server so they can grab an up-to-date version whenever suits them.

@LisaHopcroft has helpfully compiled a list of columns they need from the db:

table | column
----- | ---- 
jobserver_project | id
jobserver_project | name
jobserver_project | org_id
jobserver_project | copilot_id
jobserver_workspace | id
jobserver_workspace | name
jobserver_workspace | project_id
jobserver_workspace | created_at
jobserver_workspace | repo
jobserver_user | id
jobserver_user | username
jobserver_org | id
jobserver_org | name
jobserver_job | id
jobserver_job | status
jobserver_job | job_request_id
jobserver_job | started_at
jobserver_job | completed_at
jobserver_jobrequest | id
jobserver_jobrequest | created_at
jobserver_jobrequest | workspace_id
jobserver_jobrequest | created_by_id
jobserver_release | id
jobserver_release | workspace_id
jobserver_release | created_at
jobserver_releasefile | id
jobserver_releasefile | release_id

The report code also shows which queries they're making on the provided data: https://github.com/ebmdatalab/copiloting/tree/copiloting-report/reports

[`01_extract-jobserver-data-from-sqlite.R`](https://github.com/ebmdatalab/copiloting/blob/copiloting-report/reports/01_extract-jobserver-data-from-sqlite.R) and [`02_review.Rmd`](https://github.com/ebmdatalab/copiloting/blob/copiloting-report/reports/02_review.Rmd) in particular are where the data is queried and used.

Some questions to answer:

* Can we extract the necessary data for the R code to make use of?
* Would a simple format like CSV be ok for this?
* Are we creating further maintenance burden on ourselves when the report queries need to change and only devs familiar with Django can make the change?

---

A completely separate option would be:
1. create a GHA workflow which runs db-to-sqlite to generate a sqlite db with the tables which contain no obviously disclosive user data
2. run it on a regular schedule
3. point datasette at it, enabling the download [sqlite] db option
4. host it behind our Google SSO via cloudflare

This would allow anyone who wants to poke around job-servers non-user data an easy option to do so without bothering the pipeline team each time _and_ would let users download the actual data to build reports on.

**Comment by CLStables** [comment]
One option is just to document the current process so that it's quick to repeat on-demand
