### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2644]
When we start to think about making v2 live we should document the process of setting up an Interactive/email-only user, updating the tech support docs for what the outcome of requests to that group should be.

**Comment by lucyb** [comment]
No one in the tech group should be doing onboarding, it is the responsibility of the IG team. However, people on tech support may have to respond to queries and there should be some documentation about this.

**Comment by CLStables** [comment]
Example of information it would be useful to document re. how the re-run analysis button works: https://bennettoxford.slack.com/archives/C0441RRL3RC/p1684935665745039?thread_ts=1684837611.401309&cid=C0441RRL3RC
