### ISSUE TITLE
Redirect to interactive page after password reset

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2656]
When a user resets their password we don't redirect them to the appropriate interactive page.

**Comment by ghickman** [comment]
@lucyb – I can't replicate this locally so far.

I tried:
* go to `/reset-password/`
* enter test user email
* open link in email in separate browser profile
* set password

and got redirected to the interactive form.

Did you take a different route? and what page did you end up on?

**Comment by lucyb** [comment]
It seems to be working now. Maybe something's changed since I last tried it, or maybe the user wasn't set up correctly. Will close anyway.
