### ISSUE TITLE
Workspace admin section is empty for interactive users

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2657]
When an interactive user views their workspace the admin section is empty.

**Comment by lucyb** [comment]
This is a screenshot from a Interactive-only user viewing the workspace page

![Image](https://user-images.githubusercontent.com/3889554/220101652-81d705da-208c-4680-a404-e986a7fb001c.png)

**Comment by ghickman** [comment]
Fixed in #2826
