### ISSUE TITLE
Get opinion from Data Team on how best to limit the list of codelists that we show to users

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2658]
Ask Data Team (probably Peter and Becky?) to if there are sensible ways to reduce duplicates/bad quality codelists coming in from Open Codelists (e.g. only use certain orgs, only take the most recent version?)

It could be useful to show them a few examples of the searches that are producing lots of duplicates/codelists that should obviously be excluded?

**Comment by CLStables** [comment]
Ideas for useful fields to show users (to help them make the decision of which one to pick): date of creation, description and number of codes

For medications, should we consider only importing codelists with vpid? (this would allow us to group) - not really related but worth asking the question?

**Comment by lucyb** [comment]
After speaking with Becky this afternoon we decided that:

*The OpenCodelists API should return organisation codelists only by default
* but will include user codelists if the "?include-users" query param is used
* Interactive should only display codelists that have an organisation (user defined codelists will require an extra toggle or something, tbc)
* Interactive should display the published date
* Interactive should only display codelists that have a version with a status of published and downloadable true.

See https://github.com/opensafely-core/opencodelists/pull/1541

Becky also noted that the opensafely and primis organisations are the ones they return in the opencodelists main search and are generally "preferred" (paraphrasing heavily). So we may want to consider an option to limit to just those organisations.

**Comment by lucyb** [comment]
Completed: https://github.com/opensafely-core/job-server/issues/2693

All other outcomes from the conversation with Becky have either been completed or have their own tickets.
