### ISSUE TITLE
Allow index-date-range to be specified at form submission

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2665]
Currently the index date range (i.e the time period of interest) for the Interactive report is hard-coded in the project.yaml as
`--index-date-range="2019-01-01 to 2022-11-01 by month"`. However, the Analysis Template renderer should be able to dynamically replace these based on the `START_DATE` and `END_DATE` in the Interactive job server app ([here](https://github.com/opensafely-core/job-server/blob/cb046e80be1150d188f124e04f72ffd8df3bcdd0/interactive/dates.py#L18-L19)).

These should also be the same dates shown to the user when they're making their request:
![Image](https://user-images.githubusercontent.com/3889554/220165029-b74706a0-c740-4e5f-a319-3edd748602b2.png)

**Comment by bloodearnest** [comment]
This is fixed in job-server #2676 and in interactive templates (https://github.com/opensafely-core/interactive-templates/pull/15)
