### ISSUE TITLE
OSI: Change index date to be the end of the month

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2694]
(consult with Catherine and Louis about new figure and wording)

We decided in our weekly meeting on [23rd Feb](https://docs.google.com/document/d/1fPFEypEgLhjM6Yr0XMV_O9xZa6uHbPVYuwUIDYp--lU/edit#heading=h.rabq9glch3ma) that allowing users to request a "codelist 2" denominator was important, and that to make this easier to implement it makes sense to change the "index date" to be the end of the month. This is outlined as "alternative scenario" in [this doc](https://docs.google.com/document/d/1INGJlxGfRDl0yANS9X91h0mK4ViU6y-m1MjMxYrOGTo/edit?usp=sharing)

**Comment by bloodearnest** [comment]
SVG/wording in the form will need updating when this is done

**Comment by tomodwyer** [comment]
- [ ] @tomodwyer to update the SVG

**Comment by LFISHER7** [comment]
Everything else has been completed for this
