### ISSUE TITLE
Add an "analysis history" section to user accounts

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/job-server#2724]
As a user I'd like to be able to see previous analysis I have requested/run.

At the moment if you enter via the login you cannot see your analyses - you must go back to your emails  to find the correct url. Adding "analysis history" to a users account would be the obvious solution - maybe eventually it might be part of the home screen when you login?

**Comment by ghickman** [comment]
@brianmackenna – we started thinking about this in #2499, but paused to get the walking skeleton up and, well, walking. I'm going to close this one as a duplicate but this is really useful info so I've copied them over to the original ticket.
