### ISSUE TITLE
Automatically revoke access if not using after n months (Interactive users)

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/job-server#2725]
I have access to an Oral system run by the NHS Business Services Authority (ePACT2) to access prescribing metrics.

Access is automatically revoked after 6 months of no-use and today at 5 months I received a warning telling me this plus a survey asking me for feedback about why I might not be using.

I think we should implement a similar feature and I think there are two groups

- Group A: Similar to me above. use the system a lot but for whatever reason stop (might be leaving job etc.)

- Group B: people sign up but never submit a job.
For the pilot a substantial amount of people have not submitted an analysis after being granted access. I think we should work very hard for feedback from Group B.

**Comment by lucyb** [comment]
Closing as we're not doing any further work on OS Interactive.
