### ISSUE TITLE
Interactive workspace purpose

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2746]
We're creating an interactive workspace when we create interactive users in the staff area but we don't currently set a meaningful purpose.  Since a user can pick any combination of 2 codelists in the interactive form I think it probably makes sense to have a static purpose added to these workspaces.

**Comment by lucyb** [comment]
Do we have a project purpose and a workspace purpose? If so, then it makes sense for the workspace purpose to be static, automatically generated text. We should check the wording with Catherine though!

I assume the project purpose would be based on what was in the application?

**Comment by ghickman** [comment]
We don't have purposes for projects because we always planned to link out to the application's lay description for that.  We could capture that for the project as part of the new create project page.  However the workspace purpose is to describe why that specific workspace exists so in this context we probably want a reduced version of the project description?

**Comment by lucyb** [comment]
> we probably want a reduced version of the project description

Yes, that sounds sensible.

**Comment by madwort** [comment]
@CLStables to make up some words!

**Comment by CLStables** [comment]
Brian has agreed to the following wording:
This workspace has been created for analyses requested via the OpenSAFELY Interactive point-and-click tool _(link to main marketing page)_. All analyses are required to align with the approved project purpose.
