### ISSUE TITLE
Add Django messages support to base tailwind template

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2747]
Our outgoing base template supports these [in the alerts partial](https://github.com/opensafely-core/job-server/blob/main/templates/partials/alerts.html#L19-L32).

Any view can add to this list of messages, which is cleared once they've been rendered for the user, so they typically go somewhere prominent.

[Django docs on messages](https://docs.djangoproject.com/en/4.1/ref/contrib/messages/#displaying-messages).

**Comment by tomodwyer** [comment]
Closed by https://github.com/opensafely-core/job-server/pull/2762
