### ISSUE TITLE
Dependabot PR checks aren't running in the merge queue

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2751]
We've turned on GitHub's [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions) but Dependabot PRs aren't triggering any checks to run when they get added to the merge queue.  Eventually they are removed from the queue after ~3h of non-activity.

It looks like we need to trigger checks on the [`merge_group` target](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions) in our `main.yml`.

**Comment by madwort** [comment]
next assumption - permissions?
