### ISSUE TITLE
Add a demo of the AnalysisRequest form

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2779]
We'd like to let users get a feel for what is possible from OSI and showing them the form should be a reasonable way of doing this.

The current form requires a logged in user who has the InteractiveReporter role, which requires they've also submitted a successful application.  Not great for demo purposes.

It's unclear where the URL will live but I think adding a demo view and model to mirror the existing ones should work well here, allowing us to keep the React form as is.  We can even run a management command on a schedule to delete the demo runs after N days.

The AnalysisRequestCreate view is a CBV with various methods which configure the view for use.  I think we can lean on this to create a AnalysisRequestCreateBase with all the bits necessary to render the form and get the codelists.  An AnalysisRequestCreateDemo subclass would then create a AnalysisRequestDemo model instance on `post`, and redirect to a AnalysisRequestDetailDemo view which shows a templated report with the details they put in (probably even using the report template from interactive_templates with dummy values).

The AnalysisRequestCreate view would also build on top of AnalysisRequestCreateBase with its current `post` method, continuing to work as it already does.

The high level goal with this idea is to keep bits of views and model which are similar, layering on live/demo parts to concrete subclasses.

**Comment by lucyb** [comment]
No longer required because we're not doing further work on OSI.
