### ISSUE TITLE
Improving UX of links to outputs in Workspace

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2799]
At the moment, on the Releases section of a Workspace the links to "Level 4 outputs", "Released files" and "Published files" only appear if there are files available matching those criteria. This can [cause confusion](https://bennettoxford.slack.com/archives/C0270Q313H7/p1678726719011599?thread_ts=1678367781.695419&cid=C0270Q313H7).

A better solution would be to always display all three links, but to disable/grey out the links that aren't available to be selected and to include a tooltip explaining why (e.g "No files have been released for this workspace")

![Image](https://user-images.githubusercontent.com/3889554/224782171-bf1a796a-78e0-46b5-a98b-a0cfca2d00ab.png)

**Comment by ghickman** [comment]
This would fit nicely with how we handle buttons around the site too 👍
