### ISSUE TITLE
JobRequest page cancellation UI feedback

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-server#2801]
When you click "cancel job" button on the job request page, you get no feed back that you've successfully requested cancellation, unlike on the job page.

The jobs list also doesn't change status, and it might not for some time (if the job-runner loop is stuck copying files for a bit). Might be nice to indicate somehow that cancellation has been request for that job?

**Comment by lucyb** [comment]
Note: also disable the button when the cancellation request is made
