### ISSUE TITLE
Add styling to Interactive Reports

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2802]
Look at whether we can embed CSS into the generated report, so that the styling is linked to a particular version of the of the report.

See this for a starter: https://bennettoxford.slack.com/archives/C0441RRL3RC/p1678791262404799

Assume that the report will be available on job server and available to download via print-to-PDF. Aim for best practice HTML and CSS, but don't worry about having the report viewable on other platforms.

**Comment by tomodwyer** [comment]
Closed by https://github.com/opensafely-core/job-server/pull/3103
