### ISSUE TITLE
Convert Project/Org relationship to an M2M

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2827]
We expected each project to be owned by a single organisation when we added both objects, however in reality it's possible for two or more orgs to collaborate on a project.

We can model this by converting the existing ForeignKey to a ManyToManyField.

~We will also need to remove orgs from the main URL structure.  This _should_ be trivial to manage by setting up the apppriate redirect instances on all projects.~ (done in #3312)

We also need to handle various staff area controls switching to a multiple item selection UI.

**Comment by madwort** [comment]
@bloodearnest to review this week
