### ISSUE TITLE
Infer org membership from project membership

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#2828]
We currently set up new users with membership to both an org and a project.  In OSIv2 we shortcut this for the staff member setting up a user by using the project's org as the target org.  We think this better matches how the platform is used in general, so instead of copying project.org when creating a user we should instead remove OrgMembership and instead infer membership from the current/all projects when that membership is used.

**Comment by lucyb** [comment]
@ghickman to update and then close.

**Comment by ghickman** [comment]
I’ve had second thoughts about closing this! Will update with those thoughts next week

**Comment by ghickman** [comment]
I've flip-flopped on this one several times but I don't think we can do it.

My reasoning is that we're moving to projects and orgs having an M2M to model that orgs collaborate on projects, which means we won't be able to infer which of those orgs a user is a member of from that relation alone.
