### ISSUE TITLE
Show Interactive reports on the Project page

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2851]
We've released at least one report for the [internal workspace](https://jobs.opensafely.org/datalab/opensafely-internal/opensafely-internal-interactive/) now and will be releasing and publishing more.

It should be possible for anyone with access to the project to view a list of released Interactive reports on the project page.

It should be possible for anyone to view a list of published Interactive reports on the project page.

**Comment by ghickman** [comment]
Fixed in #3234
