### ISSUE TITLE
Viewing the amr-uom-brit repo in the staff area doesn't work

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2894]
See https://jobs.opensafely.org/staff/repos/https%253A%252F%252Fgithub.com%252Fopensafely%252Famr-uom-brit/ (or rather don't, because it eventually returns an error)

The repo appears to be okay on github https://github.com/opensafely/amr-uom-brit

**Comment by ghickman** [comment]
Locally this is doing 43 queries in 16469ms locally which explains why we're hitting a gunicorn timeout in prod.

It's the workspace building function triggering the `users` query on each iteration of the workspaces.  I'll switch this to cache the users via a lookup table for the workspace function.

**Comment by ghickman** [comment]
Closing this one as I don't think we're likely to tackle the O(N) queries left but the page is now performant.
