### ISSUE TITLE
Add help text for the Analysis Request purpose field

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2908]
Confirm the wording with Brian. I think Catherine already had some suggestions in the requirements doc.

George had a good suggestion of changing the existing text on that field to something like, "Explain why this analysis fits with the project purpose"

**Comment by lucyb** [comment]
Note: these regulations around the use of data for covid-19 purposes might be helpful https://www.gov.uk/government/publications/covid-19-notification-to-gps-and-nhs-england-to-share-information/notice-under-regulation-34-of-the-health-service-control-of-patient-information-regulations-2002#covid-19-purpose

**Comment by lucyb** [comment]
Might need input from @CLStables . Review with Brian once we have some wording.

**Comment by tomodwyer** [comment]
This is covered in #2981

**Comment by tomodwyer** [comment]
Closed by #2981
