### ISSUE TITLE
Allow users to enter a title for an Interactive report

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2951]
The current title for an Interactive report is auto-generated based on the two codelists that were chosen. However, these often have long and confusing names, which were not expected to be used as a report title. 

When someone is completing an Analysis Request we should ask them for a title that will be used on the report instead. Based on feedback from OSIv1, we should add some help text that explains how and where the title will be used since the user probably won't have seen a report at that point.

**Comment by ghickman** [comment]
Should we have them set a title once the report has been generated? So the flow would be:
1. fill in analysis form
2. wait
3. get email that we've output checked the results and you have a report
4. be asked to set a title for the report

We could even make this part of the publish request flow?
