### ISSUE TITLE
Interactive-only users must not be able to download released outputs

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2973]
We want Interactive users to download an unpublished report via the reports UI, which allows them to do so in a controlled way. i.e by reminding them of the conditions of sharing the report and by generating a watermarked PDF. This means they should not be able to download released outputs, as it would allow them to bypass this.

Note: might be preferable to prevent them from being able to view released outputs altogether.

**Comment by ghickman** [comment]
I've confirmed that an interactive-only user can't view released outputs for their workspace (or any other).
