### ISSUE TITLE
Failed jobs for Interactive should notify tech support

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2974]
If I understand correctly, Interactive users won't know their job has failed and probably shouldn't as they won't be able to take any action. So we should ensure that tech support are notified instead (currently they'd be notified if there was an issue with job runner, but not if there was an issue with the analysis code).

Tech support should know what action to take based on the information in the slack message and the team manual should have the relevant instructions.

**Comment by lucyb** [comment]
We aren't sure that we're getting these alerts, so I'm reopening the ticket for now.

**Comment by CLStables** [comment]
Testing this would involve deliberately running a broken study - can/should we do this?

**Comment by ghickman** [comment]
Confirmed here: https://bennettoxford.slack.com/archives/C0270Q313H7/p1686757920736859
