### ISSUE TITLE
File browser truncating file names

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#2984]
The list of files in the file browser have their first letters truncated. For example, here is [this list][1] of published outputs:

![Screen Shot 2023-04-14 at 09 47 44](https://user-images.githubusercontent.com/477263/231993703-e62bcc58-b496-4958-998d-70ea3e0a9d3c.png)

The list of files should contain _report.html_ and _rows.csv_, as these are the files on the filesystem.

[1]: https://jobs.opensafely.org/datalab/opensafely-internal/tpp-database-schema/outputs/38/

**Comment by tomodwyer** [comment]
Oh boy, this is a very silly bug 🤦
