### ISSUE TITLE
Add extra text to bottom of report to meet publication policy requirements

### ISSUE THREAD

**Issue by CLStables** [opensafely-core/job-server#3012]
Add as text section at bottom of report page (and to be included in PDF)
Catherine to mock up content

**Comment by CLStables** [comment]
Suggested content can be found [here](https://docs.google.com/document/d/1HxBQmJ56laBEVTl-sJYEErKoeNjiAeZvDb8pj-uw52U/edit#bookmark=id.dvwdpxu6sdv8)

**Comment by tomodwyer** [comment]
Blocked waiting on latest COPI notice text
