### ISSUE TITLE
Add text to explain what underlying output html file is

### ISSUE THREAD

**Issue by CLStables** [opensafely-core/job-server#3017]
In case users come across it and download it - there is a risk that users will download the underlying output file and get confused because it is similar to the report.

Consider adding some standard text to the top of the html output file explaining what it is, and then hide it from the reports page (ask Tom O to do that when rendering the page).

@CLStables to add the content.

**Comment by tomodwyer** [comment]
The hiding of the text is blocked pending a release of a HTML file with the text we want to hide.

**Comment by CLStables** [comment]
Can we close this one now @tomodwyer?

**Comment by tomodwyer** [comment]
Oh yup, this is done in https://github.com/opensafely-core/job-server/pull/3103
