### ISSUE TITLE
Automatically alert co-pilot(s) when an OSI intermediate report is downloaded

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#3020]
To meet our [policy on sharing of results](https://www.opensafely.org/policies-for-researchers/#details-all-datasets). If we decide to do this, we should also **update the disclaimer** when downloading a report to read "Your co-pilot will be automatically informed that you have downloaded a copy of this report" (or similar)

See [discussion on Slack](https://bennettoxford.slack.com/archives/C0441RRL3RC/p1680252081868979)

It would also be useful to send an alert into our "OSI monitoring" Slack channel (if we decided to have one?) So we'd be alerting for ~new analysis requests~, reports being released after output checking and reports being downloaded.

**Comment by lucyb** [comment]
@CLStables can you check the existing disclaimer to see if it asks people to notify their copilot when they download the PDF?

**Comment by CLStables** [comment]
I've checked and am happy with the current wording - can someone just remove the yellow highlighting from that text and then close this ticket? Thanks!
