### ISSUE TITLE
interactive_templates package is not versioned

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-server#3031]
Currently interactive_templates is not installed with an explicit version.

This is because we install from a zip archive, in order to support pips require-hashes arguments.

However, this zip file has not version metadata, so pip-compile cannot bump the explicit package version when it installs it.

Which results in interactive_templates package not being updated when running `just devenv`, even thought the url and hash have changed in the requirements.prod.txt file.

This is foot gun that it would be good to fix. Assuming we want to keep require hashes, we can maybe add a github action that runs after merge to main that does either:

a) auto-updates pyproject.yaml with a version.
b) adds a version, and creates a GH release that is used as installable target, rather than the current repo zip

I think b is a more elegant solution.

**Comment by CLStables** [comment]
Tech debt issue - there is a hack workaround. We could fix if we have time, but if necessary move to a future OSI initiative

**Comment by lucyb** [comment]
I updated the justfile a few weeks ago so that the interactive_templates package is updated when running `just devenv`. This ticket would create a much better, permanent solution but I think what we have in place is good enough for OSI:V2, so I'm removing it from this initiative.
