### ISSUE TITLE
Add the email address of the person who downloaded the report into the watermark (“downloaded by X”) to discourage inappropriate sharing

### ISSUE THREAD

**Issue by CLStables** [opensafely-core/job-server#3059]
There is an outstanding question about whether this will work ok for co-pilots downloading reports to send to NHSE for review. If emails cause issues (non-work emails are linked to GitHub accounts) we could use name instead?

**Comment by tomodwyer** [comment]
Closed by https://github.com/opensafely-core/job-server/pull/3103
