### ISSUE TITLE
Analysis detail page for “failed” requests changed from “being processed” to something else…

### ISSUE THREAD

**Issue by CLStables** [opensafely-core/job-server#3060]
The request may "fail" because the job failed to run, or because the output checking wasn't completed (either it was cancelled or something about the data meant it couldn't be released). We will need some way to change the "state" of the request to make this work... (would "rejected" be a useful state to add?)

**Comment by CLStables** [comment]
Could use the existing workflow created in outputting spike.

**Comment by tomodwyer** [comment]
@ghickman is there a way I can see the "failed" status in a boolean on the `templates/interactive/analysis_request_detail.html` template?

**Comment by ghickman** [comment]
I'm leaning in this direction too, but my one worry is the page will continue to say "your report is processing" once we've rejected an analysis 🤔

**Comment by ghickman** [comment]
Thinking through this again, the states for an Analysis are the combination of it's [latest] `JobRequest.state` and the presence of a released file.  We know a file shouldn't be released from a failed JobRequest so we can ignore that combination.

That leaves us with 4 states:
* **Pending**: JobRequest hasn't started/completed, file isn't important
* **Failed**: JobRequest failed, file isn't important
* **Success**: JobRequest succeeded and the file was released
* **??**: JobRequest succeeded but no file has been released

The last state is where things get tricky.  It's really two states: the file has yet to be released and a human chose not to release a file.  However, we have no infrastructure to support the distinction, so I think we're left with the analysis sitting on processing for that.

Which leaves us with the failed one where we can change what we show.
