### ISSUE TITLE
Support re-rendering of code for existing Analysis Request

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-server#3102]
Sometimes bugs cause a job-request associated with an AnalysisRequest to fail.

We want to be able to fix the code, and then take the same AnalysisRequest, and re-render and commit the new code to the repo, and create a new job request

Nothing should change for the user. The audit logs will show 2 job requests for this AnalysisRequest.

**Comment by lucyb** [comment]
This would be nice to have, but can be done manually if needed. Would be useful if we're going to make significant changes to the analysis code.
