### ISSUE TITLE
Mock-up of ACRO-tool within outputs-viewer

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3130]
>**Note**: This issue should be moved into the SACRO repo once we have one

❗ Deadline is end of May

Seb needs to present some of our findings from the discovery work and explain what we're planning on building at a SACRO meeting by the deadline. The mock-ups could take the form of screenshots or wireframes. It is **not** expected that we will be showing a working system.

We need to show the output of the [acro](https://github.com/AI-SDC/ACRO) tool from within the existing outputs-viewer. This could be the version of the outputs-viewer from last year's [spike](https://bennettoxford.slack.com/archives/C63UXGB8E/p1678964100351719) to improve the request/release process. Again, it doesn't need to be functional at this point, just mock-ups to demonstrate roughly what we intend to work on delivering. It should also help us to understand how we might approach integrating the output from acro.

We should involve a researcher (maybe Louis) in this work, so they can provide a data file and corresponding json file produced by the [acro](https://github.com/AI-SDC/ACRO) tool, although this is not essential. They may find that doing https://github.com/opensafely-core/job-server/issues/3131 first is helpful for completing this work.

**Comment by sebbacon** [comment]
Idea: we could implement the static screenshots by saving the previous spike as HTML and providing _that_ to Tom for working up.

**Comment by tomodwyer** [comment]
This work is now picked up in a separate repo and issue:
https://github.com/opensafely-core/sacro-wireframe
