### ISSUE TITLE
Provide feedback on SACRO test script

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3131]
>**Note**: This issue should be moved into the SACRO repo once we have one

>**Note**: This issue may need further information, so ask Lucy or Seb, if required

❗ Deadline is end of May

Lucy/Seb needs to provide feedback on our experiences using the SACRO test script to Jim at UWE. This ideally needs a researcher to be involved.

The process to follow is:

1. The latest version of the code is on pipit so can be installed using:
`pip install acro`

2. We’ve taken the decision to use an open-source well documented dataset of data about nursery admissions. It is fully described and available for download from here:
https://www.openml.org/search?type=data&sort=runs&id=26&status=active

3. We've written an example script for people to try - it is described in this notebook: which you can view online. It doesn’t display all of the functionality yet, and we haven't finished translating the R version to this dataset (but can if you really like) https://github.com/AI-SDC/ACRO/blob/main/notebooks/test-nursery.ipynb

**Comment by sebbacon** [comment]
Things to consider:

* The most important feedback UWE needs is "this doesn't work" or "this doesn't make sense" - high level testing and sense-checking
* The ideal outcome is that we eventually use this as decision support tool for our _own_ output checking, so feedback should also have this in mind. "Will this support your own output checking process? If not, why not? What would you change?"
* We can use the testers' experience with the tool to inform how we incorporate its outputs into [the concept screenshots](job-server/issues/3130)

**Comment by bloodearnest** [comment]
I've dumped some initial thoughts from trying there demo code here https://bennettoxford.slack.com/archives/C63UXGB8E/p1684409451900489

**Comment by benbc** [comment]
@bloodearnest When you get back to this (maybe after you're back from holiday), can you go through it again with @HelenCEBM so we can include her thoughts?

**Comment by bloodearnest** [comment]
https://docs.google.com/document/d/15ElDrxxyBhfByJfPuN1Dkc-qc_0vpv8mmF3-9DbxM5E/edit
