### ISSUE TITLE
Change "contact support" to include email address as text

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3134]
This came up in one of Brian's user videos. NHS laptops won't automatically open a mailto: link, so they can't easily see which email address to contact. Brian found this on an error page (when his report wouldn't run) but it may be similar in other places...

**Comment by tomodwyer** [comment]
This has been done:

https://github.com/opensafely-core/job-server/blob/f09cd89b4819346d1bf98396fa36501865042d97/assets/src/scripts/interactive/main.jsx#L82-L84
