### ISSUE TITLE
Published outputs

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#3136]
I [published some outputs][1] this morning. I have the _Output Publisher_ role. However, the published outputs are marked as _Draft_ in [the list of published outputs][2].

I think I should be able to request one of the published outputs at <https://jobs.opensafely.org/api/v2/releases/file/01H0J2NXVYAWYVCH5EAG6TJDNP>. When I'm logged in, this link downloads the published output. However, when I'm not, this link 403s.

I can request all the published outputs at <https://jobs.opensafely.org/datalab/opensafely-internal/tpp-database-schema/outputs/43/download/>, whether or not I'm logged in.

Being able to download published outputs is important, because we use [tpp-database-schema][3] when developing ehrQL.

[1]: https://jobs.opensafely.org/datalab/opensafely-internal/tpp-database-schema/outputs/43/
[2]: https://jobs.opensafely.org/datalab/opensafely-internal/tpp-database-schema/outputs/
[3]: https://jobs.opensafely.org/datalab/opensafely-internal/tpp-database-schema/

**Comment by evansd** [comment]
@ghickman @bloodearnest I'm not sure this issue is fixed.

On this page, Iain's snapshot from 16 May 2023 is now showing as Published, rather than Draft, which is good:
https://jobs.opensafely.org/datalab/opensafely-internal/tpp-database-schema/outputs/

But _only if you're logged in_. If you visit it incognito, it doesn't show up at all.

**Comment by ghickman** [comment]
Ah, this is another vesitgual use of `Snapshot.published_at` in use.  I've fixed this in #3143 and will try to get it reviewed and merged today for y'all.

**Comment by ghickman** [comment]
@iaindillingham @evansd fixed and deployed, sorry about the rocky road on this one!
