### ISSUE TITLE
Bug: project status not displaying properly

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3139]
Helen [pointed out](https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1684226672877689?thread_ts=1684166541.292749&cid=C03ELD5FEAU) that some of our projects are missing statuses on [this page](https://jobs.opensafely.org/datalab/). Looks likely to be related to paper/report status causing issues?

**Comment by CLStables** [comment]
If not a quick fix, push back to triage
