### ISSUE TITLE
Validate slugified project names

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3211]
🧵 https://bennettoxford.slack.com/archives/C03D1G814BA/p1686734853110499?thread_ts=1686733924.057899&cid=C03D1G814BA

A project was successfully created with the name `-`. This subsequently broke any attempts to access that project, because Django's slugify removes hyphens, so it appeared that the project had an empty name.

We should validate that the name and slug are both non-empty after validation and not allow a user to create project with an "empty" name.

**Comment by ghickman** [comment]
Closing in favour of #3212. I didn't realise you were writing this one, sorry!
