### ISSUE TITLE
Update OSI modal for published PDF download

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#3224]
For published reports all the text content in the Download PDF modal is not necessary and needs to go away.  However this leaves the modal looking odd…

![](https://p198.p4.n0.cdn.getcloudapp.com/items/jkuRlYPY/8877ee1e-445a-4f15-9ff7-acdb56be98ec.jpg?v=541d1855021fa388152b30781f681c2a)

The modal is useful for hiding the generation of the PDF in the background.  Is there something better we can do once the report is published?

**Comment by ghickman** [comment]
Closing this now that #3243 is in as it side steps the problem with the modal being too small.

@tomodwyer – I know you had some technical changes you wanted to do under the hood, can you add another ticket in for those?

**Comment by tomodwyer** [comment]
@ghickman I'm happy with this. Viewing the text provides enough of a distraction from the CSS changes happening behind the modal.
