### ISSUE TITLE
Manually publish a single file

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#3276]
Currently we can only publish all files released from a workspace.  Over time we've found a need to publish a subset of files released for a workspace.

Another request has come in for this, to publish [this released file](https://jobs.opensafely.org/datalab/pincer/pincer-measures/outputs/56/output/report_updating.html).

There are two parts to this ticket:
* [ ] create a draft Snapshot for the linked file above, checking with Louis&Rose that it's correct before making it public.
* [x] Building out a function in the relevant commands.py to release an iterable of the given ReleaseFiles, updating the OSI report-creation code to use it, and wrapping it in a management command so we can try out publishing subsets of files before updating the UI to do it too.

**Comment by lucyb** [comment]
@ghickman has this been documented anywhere?

**Comment by ghickman** [comment]
@lucyb – not yet, we're going to try it out the next time a regular report comes up (there are at least 2 monthly ones so should be soon) and document if we're still happy with the process after that.
