### ISSUE TITLE
Investigate speeding up Job Server tests to improve our deployment times

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3297]
It currently takes around 10 mins to run all the GitHub Actions for Job Server, and as we do branch-based development, this means it takes a minimum of 20 mins to get a change into production.

We should see if there are some easy ways to speed up the time the GHAs take to run. Since the tests are by far the largest chunk, we should look at those first.

Note: see George's xdist branch
Note: using `pytest --durations=0` will show the tests that are particularly slow

**Comment by ghickman** [comment]
Some options to look into:
* can we run postgres in-memory?
* can we turn off fsync for postgres? (we're using GHA's postgres service for the non-docker tests, could we normalise to docker/GHA and apply this change?)
* do we have any tests making expensive db queries?
* what does testing without the db look like? (and how many tests could we feasibly do this with?)

**Comment by bloodearnest** [comment]
I had a play with tweaking postgres config, but both locally and CI it doesn't seem to make a notable difference

https://github.com/opensafely-core/job-server/pull/3479
