### ISSUE TITLE
Add a graph showing P99/P95/P50 to the Honeycomb dashboard

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3305]
This came up as a result of [this incident](https://docs.google.com/document/d/1T-kFEElIqXHgqK8ahtsxbFNOaV0qY2X4G27utBX4Atk/edit)

**Comment by madwort** [comment]
Done (on [this board](https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/board/napZ5kLKTE1/OpenSAFELY-Job-Server-Django-app) ). Only showing P95/AVG as four was very crowded when using overlaid charts.

**Comment by bloodearnest** [comment]
> Done (on [this board](https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/board/napZ5kLKTE1/OpenSAFELY-Job-Server-Django-app) ). Only showing P95/AVG as four was very crowded when using overlaid charts.

Yeah, the super slow peak squashes it.

If you zoom in to exclude that, its much more useful https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/job-server/result/2duZBvjRYcz/a/3vPJptnBo5i/Average-P95-duration-of-requests?preferOverlaidCharts
