### ISSUE TITLE
Remove temporary block on Amazonbot

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3306]
We should remove the nginx config that is stopping Amazonbot from crawling Job Server and monitor the effects. See 🧵 [thread](https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1689869810110059).

This was done as a result of [this incident](https://docs.google.com/document/d/1T-kFEElIqXHgqK8ahtsxbFNOaV0qY2X4G27utBX4Atk/edit).

If the monitoring still shows an issue, we could consider increasing the rate limiting in the robots.txt config. Although, this could potentially take a while to take effect.

**Comment by madwort** [comment]
we have started asking for rate-limiting https://github.com/opensafely-core/job-server/pull/3300

**Comment by madwort** [comment]
Amazonbot has read our most recent robots.txt on 2023-07-21T18:22:16.692023472Z so I will remove the forcible block (but leave the block in robots.txt for now)
