### ISSUE TITLE
Track 404s

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#3320]
With #3310 we've shuffled around the URLs in no small way.  However we don't have much insight into the number of 404s our users might be seeing from this or other views.

Could we add number of 404s to honeycomb? Would a triggered notification be useful here?

**Comment by madwort** [comment]
https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/job-server/result/c22q1LiZ1A4

**Comment by tomodwyer** [comment]
Will be covered as part of dashboard review meetings.
