### ISSUE TITLE
Inaccessible event log page

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#3336]
@LFISHER7 reports that the [event log][] page is inaccessible ([thread][1]). He sees this:

![Screenshot 2023-07-27 114325](https://github.com/opensafely-core/job-server/assets/477263/8c7733d8-aa82-4b15-9413-9d3adb6b9db4)

But I see this, both when I'm logged in and when browsing as an anonymous user:

![Screenshot 2023-07-27 at 11-41-27 Event log OpenSAFELY Jobs](https://github.com/opensafely-core/job-server/assets/477263/2043b75e-a6b6-4429-919e-e76724527f09)

Louis reached the event log page by clicking the _Event Log_ button and the _View all job requests_ button on the homepage.

[event log]: https://jobs.opensafely.org/event-log/
[1]: https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1690449633376449

**Comment by LFISHER7** [comment]
This was an issue with a web tracker blocker blocking the event log page. I've excluded the jobs site domain from the blocker and this it's working now, so I'll close this
