### ISSUE TITLE
Support links in Project Status description

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/job-server#3338]
When selecting a status for projects, users can specify a report/paper is linked in the description. It would be nice to support a link description + url, like we do for OpenSAFELY Reports, rather than just entering links in free text.

**Comment by CLStables** [comment]
A few examples of project status descriptions that would be improved by this change:
https://jobs.opensafely.org/antipsychotics-prescribing-during-covid-19/
https://jobs.opensafely.org/service-restoration-observatory/
https://jobs.opensafely.org/online-consultations/ (it's interesting how they've attempted to make this one easier to read!)
