### ISSUE TITLE
Provide a mechanism to disable user accounts in Job Server

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3343]
We need to have a clearer distinction between users who've been approved to use Job Server and everyone else. So we should provide a clearer way to remove that approval from a user. One way of doing this would be to provide the ability to disable accounts and potentially having them disabled by default when they sign up.

This ticket will be done when:
* New users start off disabled when signing up to Job Server
* The onboarding processes for new BI staff and for researchers are updated to reflect this
* Users can be disabled, giving them the same functionality as anonymous users without removing any permissions/roles/project membership
* Users show up as being "inactive" in the UI. i.e in project membership listings
* The offboarding processes for new BI staff and for researchers are updated to reflect this

[Link to risk in the Risk Register](https://docs.google.com/spreadsheets/d/14p4zoMhV5iAPTjzfTHaHDYBzkZ9Giw2yLUMTXCJdJFU/edit#gid=0&range=A28)

**Comment by lucyb** [comment]
@ghickman to provide some more information and investigate how this would work in the staff area, in particular.

**Comment by ghickman** [comment]
We already have a mechanism for disabling users, removing their roles, but what we have no way to easily list all the roles a user has, so we're going to add a page to do just that.

We'll avoid deactivating users since that will remove the ability for users to use the applications portion of the site.
