### ISSUE TITLE
run_all status incorrectly displayed

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/job-server#3414]
On the run jobs page, the status of the `run_all` selection seems to default to "running", even if there are no actions running (see screenshot below). It probably doesn't need a status at all?

In passing, the tooltip for running jobs on this page is "loading", which is inconsistent with the "running" tooltip used elsewher

![image](https://github.com/opensafely-core/job-server/assets/37254732/205aa5e3-1374-4787-a64a-12d69d95b173)

**Comment by LFISHER7** [comment]
This isn't a specific problem with the `run_all` action. Any action that hasn't been run will display like this

**Comment by madwort** [comment]
see also https://github.com/opensafely-core/job-server/issues/309
