### ISSUE TITLE
GitHub PAT for OSI bot will expire soon

### ISSUE THREAD

**Issue by benbc** [opensafely-core/job-server#3418]
Email from GitHub reads:

> Hi @opensafely-interactive-bot,
> 
> We noticed your personal access token (classic) "opensafely-interactive-token" with public_repo scope will expire in 6 days.
> 
> If this token is still needed, visit https://github.com/settings/tokens/1005632984/regenerate to generate an equivalent.
> 
> If you run into problems, please contact support by visiting https://github.com/contact?tags=dotcom-accounts
> 
> Thanks,
> The GitHub Team

Original Slack thread is [here](https://bennettoxford.slack.com/archives/C0270Q313H7/p1692306586833959).

**Comment by lucyb** [comment]
The instructions for doing this are [here](https://github.com/opensafely-core/job-server/blob/main/DEVELOPERS.md#rotating-the-osi-github-token)
