### ISSUE TITLE
Released outputs giving errors when you try to view them in job server

### ISSUE THREAD

**Issue by benbc** [opensafely-core/job-server#3422]
Some of the files from [one recent release](https://jobs.opensafely.org/the-impact-of-covid-19-on-pregnancy-treatment-pathways-and-outcomes/main_pregnancy_tx_pathways/releases/01H7ZCWQKN7V44Q9W4KVM3SXS0/) give errors when you try to view them in Job Server. Others can be viewed successfully.

These ones give "Unable to load file" errors:
* https://jobs.opensafely.org/the-impact-of-covid-19-on-pregnancy-treatment-pathways-and-outcomes/main_pregnancy_tx_pathways/releases/01H7ZCWQKN7V44Q9W4KVM3SXS0/output/release_11_08_2023/ITS_estimates_overall_12wk.csv
* https://jobs.opensafely.org/the-impact-of-covid-19-on-pregnancy-treatment-pathways-and-outcomes/main_pregnancy_tx_pathways/releases/01H7ZCWQKN7V44Q9W4KVM3SXS0/output/release_11_08_2023/pn_check_ITS_overall_8wk_new_modelled.jpeg

These ones can be viewed fine:
* https://jobs.opensafely.org/the-impact-of-covid-19-on-pregnancy-treatment-pathways-and-outcomes/main_pregnancy_tx_pathways/releases/01H7ZCWQKN7V44Q9W4KVM3SXS0/output/release_11_08_2023/monthly_pn_rate_measures_12wk.jpeg
* https://jobs.opensafely.org/the-impact-of-covid-19-on-pregnancy-treatment-pathways-and-outcomes/main_pregnancy_tx_pathways/releases/01H7ZCWQKN7V44Q9W4KVM3SXS0/output/release_11_08_2023/monthly_pn_rate_measures8wkcode_by_region_8wk.jpeg

This was originally [reported to tech support](https://bennettoxford.slack.com/archives/C01UJLWNZJT/p1692374291552499?thread_ts=1692261798.855379&cid=C01UJLWNZJT).

**Comment by lucyb** [comment]
I've created a ticket for the work to improve the error message provided back to users, so that when they encounter this problem again they know what to do (or what to ask someone else to do).

From Simon in this [thread](https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1692628032701009?thread_ts=1692615832.672489&cid=C03ELD5FEAU):
> If osrelease fails to upload all files successfully, you can re-try all files via osrelease releases/$RELEASEID, which I did and worked perfectly
> osrelease -r $RELEASEID also works
