### ISSUE TITLE
Roll out Pydantic v2

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#3427]
Order of operations:
* [ ] Bump job-runner's pydantic to v2
* [ ] Update job-runner's deps repo with pydantic v2
* [ ] Merge (and tag) job-runner
* [ ] Deploy job-runner
* [ ] Update CLI's vendored job-runner
* [ ] Merge (and tag) CLI
* [ ] Update job-server's CLI to version with pydantic v2
* [ ] Update job-server's pydantic to v2
* [ ] Fix signing module to work with pydantic v2
* [ ] Update release-hatch's pydantic to v2
* [ ] Copy over signing.py from job-server
* [ ] Deploy release-hatch (it has no cross deps)
* [ ] Deploy job-server

The list above is based on how components are connected, so several bullets are blocked by a previous one.

**Comment by ghickman** [comment]
Blocked by #3429

**Comment by lucyb** [comment]
I'm going to assume that this isn't currently in progress. Please shout if I've gotten that wrong.

**Comment by bloodearnest** [comment]
Closing this, as we can't currently use pydantic v2 with our openasfely-cli because we need pure-python only dependencies.
