### ISSUE TITLE
Upgrade otel

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3485]

**Comment by madwort** [comment]
dependabot groups enabled https://github.com/opensafely-core/job-server/pull/3492

**Comment by madwort** [comment]
dependabot not currently working for this repo

**Comment by madwort** [comment]
dependabot is now working, but the otel-dependencies group failed to update as hoped

**Comment by madwort** [comment]
https://github.com/opensafely-core/job-server/pull/3567

**Comment by madwort** [comment]
still doesn't work :/

**Comment by madwort** [comment]
https://github.com/opensafely-core/job-server/pull/3595
https://github.com/opensafely-core/job-server/pull/3596

**Comment by madwort** [comment]
maybe this issue can be closed now? seems we need to periodically manually upgrade otel, but one long-running issue isn't ideal for this.
