### ISSUE TITLE
Provide a better indication of server "busyness" to researchers

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3517]
See 🧵 ([here](https://bennettoxford.slack.com/archives/C63UXGB8E/p1693917870373379?thread_ts=1693915205.798909&cid=C63UXGB8E))

We've removed the filtering options from the event log, which means researchers are finding it harder to answer some key questions:

* Is now a good time to run my jobs?
* Why is my job still queued?

We should enable researchers to get to this information easily, including from the main event log but more generally across the site.

We should show them the number of unique workspaces with pending jobs. In addition to the total number of running and pending jobs. We should explain why this information is important and what it means for them.

It should also be easy for researchers to see the number of jobs they have pending and currently running.

**Comment by lucyb** [comment]
From Tom O:

> Queue (X job requests in Y workspaces pending)
Running (X job requests in Y workspaces)
Completed (in the last 24 hours[?])

**Comment by sebbacon** [comment]
Just to highlight some important points from that Slack thread
* The answer to "is now a good time to submit" is always yes. We should make that clear, and explain why
* What users _really_ want is a sense of how long it will take for their job to get started. Giving them any estimate of this is outside the scope of this task, but we should consider giving some prose explanation of the factors, or _any thoughts at all_, so people don't feel obliged to fall back on forming their own fictional proxy model

**Comment by lucyb** [comment]
How about this as a way of adding more information to the status page? I think it could be improved, so looking for suggestions. We should also add something onto the event log page and point people to here as well.

![Screenshot from 2023-09-19 17-11-41](https://github.com/opensafely-core/job-server/assets/3889554/99bafd8e-0e0c-4c45-aff0-9231096edc52)
