### ISSUE TITLE
Remove the Workspace db field

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3533]
See 🧵 [thread](https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1694104172208749?thread_ts=1694090341.692109&cid=C03ELD5FEAU)

The Workspace db field has been unused for two years. We thought we'd need it, but only used it for a few jobs. We have a separate db field used by the API, which is useful but is easily confused with this field.

A side effect of removing this field would be that a tiny handful of old jobs (we can check exactly how many) might appear to have been run against the full database when in fact they were only run against a small subset of it. In terms of public accountability / audit trail, we don't believe this will be an issue.

**Comment by ghickman** [comment]
Done in #3539
