### ISSUE TITLE
Delay when cancelling jobs

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/job-server#3536]
When cancelling jobs, there is a delay between pressing cancel and the job actually being cancelled.

It would be useful to have some confirmation that the cancel request has been acknowledged.

**Comment by ghickman** [comment]
There's supposed to be a banner thrown up when a user cancels a job[-request] so this is likely a bug that's slipped in.

**Comment by ghickman** [comment]
Closing in favour of #2801, which suggests we don't have a banner for this.
