### ISSUE TITLE
System Metrics

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3637]
# Overview

> We will spot systemic problems before our users do and proactively inform them about problems
> We will fix system reliability issues more quickly, resulting in a better experience for our users
> We will improve our practices/approaches so that we introduce errors/bugs less frequently, leading to more satisfying work
> We will be able to look for patterns in how system reliability fluctuates and possible associations with types/classes of work
> We will be able to measure whether our efforts to improve a particular practice/approach has impacted on system reliability
> We will be able to spot regressions following releases more easily

We need to have a dashboard that will give a high level overview of the system performance and reliability over time. This is not intended to be used during an incident, as we have other tools to help us with that.

Seb is going to act as "customer" for this dashboard. Please talk to him and arrange to spend time with him when picking this up.

# Acceptance Criteria

- The dashboard is viewable by the Tech Group
- The dashboard should have at least 3 metrics, agreed upon with Seb
- Seb feels reasonably confident that he can add new metrics onto the dashboard
- A write up of any areas where we want to add more instrumentation, or other data collection, to be able to show more metrics in future
- The dashboard should be easy for the Ops Team to find and view/login to

**Comment by lucyb** [comment]
A starter dashboard is here: https://grafana.dokku3.ebmdatalab.net/d/c2498d4c-bbbf-4946-87bf-5b72369537d8/system-metrics?orgId=1&autofitpanels

**Comment by ghickman** [comment]
Seb's thoughts on what he would like to see: https://docs.google.com/document/d/16jORRtSwIP0retYt0BIQRQd6OJAQ7A-_vor046GK3Vk/edit

Dashboard: https://dashboards.opensafely.org/d/f023de75-244d-4440-bfb1-149ec1461d41/system-dashboard?orgId=1&from=now-6M&to=now
