### ISSUE TITLE
Delivery Metrics

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3638]
# Overview

> We will improve how we are working so that we have less wasted effort and are more effective at delivering product changes
> We will be able to look for patterns in how delivery by teams changes and explore underlying causes to identify potential opportunities for improvement
> We will be able to measure whether our efforts to improve have impacted on delivery

For example
* Build times / identifying where we have slow tests
* Deployment times
* Measuring open PRs or number of security alerts
* PR latency
* Number of person-days on which there were commits
* Number of requests for tech support on Slack

# Acceptance Criteria 
* The dashboard is viewable by the Tech Group
* The dashboard should have at least 3 metrics, agreed upon with Ben
* Seb feels reasonably confident that he can add new metrics onto the dashboard
* A write up of any areas where we want to add more instrumentation, or other data collection, to be able to show more metrics in future
* The dashboard should be easy for the Ops Team to find and view/login to

# Related Issues
* https://github.com/opensafely-core/sysadmin/issues/142

**Comment by ghickman** [comment]
Thoughts from Ben on things he would like to see:
* something around the health of the PR queue (across all repos, but also broken down?)
  * size/latency/percentiles (based on time to merge?)
  * number of PRs that have been waiting more than N days (very high percentiles might be quite interesting here)
* tech support pings in slack
* DORA metrics, in particular:
  * change/failure rate
  * time to recovery


Thoughts of dashboards that tech teams could make use of that are adjacent to the areas Ben is interested in:
* ticket/PR count above a threshold for particular repos could be interesting for rarely touched repos to capture things like "dependabot is stuck"
