### ISSUE TITLE
Get Grafana running locally

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3645]
* these people have this running locally
  * [x] ghickman
  * [x] madwort 

(edited by @madwort )

**Comment by madwort** [comment]
@ghickman not sure where you're up to with this, but here's what I did:  https://github.com/opensafely-core/job-server/issues/3644#issuecomment-1759637796

**Comment by madwort** [comment]
note to self - default user/pass is `admin`/`admin`

**Comment by madwort** [comment]
think this is working now
