### ISSUE TITLE
Archive flags on workspaces listed for repos is wrong

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#3651]
The [covid-ve-change-over-time repo](https://jobs.opensafely.org/staff/repos/https%253A%252F%252Fgithub.com%252Fopensafely%252Fcovid-ve-change-over-time/) lists all its workspaces as archived, but the [covid-ve-change-over-time--explore-2nd-vax-dates workspace](https://jobs.opensafely.org/covid-19-vaccine-effectiveness/covid-ve-change-over-time--explore-2nd-vax-dates/) is not showing as archived on the user-facing pages.

Which of these pages is correct?

**Comment by madwort** [comment]
Suspected to be the template, @tomodwyer to investigate, otherwise hand over to @ghickman
