### ISSUE TITLE
Limit the size of project.yamls shown on the Job Request Detail page

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3704]
We recently received a [Sentry error](https://ebm-datalab.sentry.io/issues/4553630533/?alert_rule_id=10884789&alert_type=issue&notification_uuid=a157c3c1-b5db-487b-9274-c78157fa8335&project=5443358&referrer=slack) because someone tried to view a 2.25MB (43,000 lines) project.yaml. This caused a timeout and when I tried to replicate it locally (which shouldn't have the timeout issue), it caused the browser tab to become unresponsive due to the large size.

We could optimise how we're rendering this file. However, it's too large a file for someone to reason about or usefully use, so we should put a limit on the size of the file we're willing to render. If a file is too large we should provide an informative error and maybe point to the file in GitHub if that's easy to do.

**Comment by mikerkelly** [comment]
The fix in #3870 has the `JobRequestDetail` view provide an `is_too_big flag` to the template which stops rendering of the YAML in the presentation layer. This stops browser tabs becoming completely unresponsive. However the backend is still doing the pre-processing work of marking up the YAML, which is also computationally expensive. This leads to job requests with large YAML taking a long time to start rendering at all. This is unnecessary, as if we're not going to render the YAML we also don't need to mark it up: we can just not provide it at all.

Spotted through these sentry traces:

https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/job-server/result/gtWeeygSFz6/trace/6mjWDVigRjU?source=query
https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/job-server/result/gtWeeygSFz6/trace?source=query&trace_id=3ff29bb0576ae36dfc004d55da8068fd

Replicated on Job Server with:

https://jobs.opensafely.org/investigating-events-following-sars-cov-2-infection/post-covid-autoimmune/20846/

This page takes 5-10s to start rendering. A page with a small project YAML has an imperceptible delay.

This is a trivial one-line fix in the view code and has obvious benefit so will skip triage and submit a PR for this.
