### ISSUE TITLE
The run jobs page is slow to respond

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#3781]
The run jobs page is slow to respond. This may be where a study has many actions. For example, [long-covid-symptoms/long-covid-symptoms](https://jobs.opensafely.org/long-covid-symptoms/long-covid-symptoms/) has 200 actions.

Thank you for reporting this, @kevwing.

**Comment by ghickman** [comment]
todo:
* get stats from honeycomb about these pages across various workspaces
* check if this is related to the extra checks added for codelist rot
* check honeycomb for the requests made in the background (honeycomb has telemetry for the requests library)

**Comment by madwort** [comment]
https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/job-server/result/nwdBZ8xhqQt

**Comment by tomodwyer** [comment]
No current plans to optimise. The job submission flow will eventually be redesigned to fix some of these issues.
