### ISSUE TITLE
Truncate JobRequest Preview

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#379]
JobRequest previews list their full `requested_actions` list when previewed via the Open Graph meta tag.

For JobRequests with a lot of actions, eg [this](http://jobs.opensafely.org/job-requests/795/), the output is a little over the top.  Lets trim them down to something usable.

Relatedly, can we put some structure in the output?  An action per line, limited to 10 with an ellipsis would be ideal I think.

**Comment by bloodearnest** [comment]
Perhaps only list number of actions run, and explicitly any failed ones?

**Comment by ghickman** [comment]
Number of actions is a good shout 👍

I'm loathe to put state into previews because Slack caches them globally on request (makes them "fun" to develop too!)
