### ISSUE TITLE
Update researcher's email address

### ISSUE THREAD

**Issue by benbc** [opensafely-core/job-server#3803]
Please update the email address of a researcher on Job Server.

The researcher is [Michael Gulley](https://jobs.opensafely.org/staff/users/mgulley1/). The email address we have for him is michael.gulley@students.plymouth.ac.uk, but his new email address is michael.gulley@plymouth.ac.uk.

I have confirmed this change by emailing his old address.

The IG team have already updated their systems.

**Comment by bloodearnest** [comment]
So, the user can do this themselves, by going to https://jobs.opensafely.org/settings/

The contact email in job-server is entirely under a user's control. It's function has been for them to decide where they got notifications sent to.

As it is user controlled, it has never had the role of being an official email in any way. When we've needed that, the IG managed spreadsheets are the source.

**Comment by benbc** [comment]
Thanks Simon.
