### ISSUE TITLE
Researcher can't submit a job in a study with stale codelists even though the action doesn't use the codelists

### ISSUE THREAD

**Issue by benbc** [opensafely-core/job-server#3811]

**Comment by benbc** [comment]
[This is a Job Server issue for the Data team because it relates to stale codelists. Feel free to move it if it belongs in a different repo.]

@LFISHER7 reports that he can't run the `generate_study_population_test` action for [his study](https://github.com/opensafely/FLUCATS) because that study has stale codelists, _even though that action doesn't use those codelists_.

**Comment by benbc** [comment]
Originally reported [in Slack](https://bennettoxford.slack.com/archives/C02HJTL065A/p1700215495802639).

**Comment by inglesp** [comment]
Closing: Louis updated his codelists and the job ran fine.
