### ISSUE TITLE
Add Initial IG Onboarding

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#383]
When a User signs up to the OpenSAFELY platform they have to go through an IG process (eg sign contracts with backend providers).  Their progress through this process is not entirely obvious to the User or the team outside of Amir, who has to manually keep track of the progress of various parts.

We want to start using this site as the initial entry point for users, handling the IG part of their onboarding with tools for Amir and others to manage that process from our side.  Users will be able to see how far along they are in the process, Amir et al will be able to see and modify how far along any User is.

Some useful things to track for most/all steps:
* when and who signed off completion of a step
* who is a step waiting on? (eg User needs to sign contract)

We also want to gate usage of the site to the completion of this process, so instead of unlocking various parts with `request.user.is_autenticated` we'll need a different check.

**Comment by StevenMaude** [comment]
Can this issue be closed with the addition of the new application form? Is this just pending the new application process being used or is there anything left to do here?

**Comment by ghickman** [comment]
Yep, this is superseeded by anything with the [application-form label](https://github.com/opensafely-core/job-server/issues?q=is%3Aissue+label%3Aapplication-process)
