### ISSUE TITLE
Make it easier to view project statuses when viewing lists of projects

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#3844]
See [slack](https://bennettoxford.slack.com/archives/C31D62X5X/p1700584807708589?thread_ts=1700584028.170989&cid=C31D62X5X)🧵 

Helen has been trying to identify what projects are missing linked publications and has been finding it difficult to get that information easily in Job Server:

> on a similar note if we want people to update their projects retrospectively it would be great if [this page](https://jobs.opensafely.org/projects/) showed for each project who is the creator/owner, and the current status, and if the publication is missing (unless i should be looking somewhere else?)

> currently i have to click on each project individually to check them out

> the main projects i want to update are the ones where i created them so it would be easier to filter them (by eye at least) if the lead person's name was shown

Note: it might make sense for some of this information to be accessible in the staff area instead (like missing publications), in which case someone should let Helen know how to access it.

For example: https://jobs.opensafely.org/projects/

![Image](https://github.com/opensafely-core/job-server/assets/3889554/aebf56e2-a416-425e-a74b-8fcef930e7fd)

**Comment by CLStables** [comment]
I'm happy to talk this through with whoever picks it up, if that would be useful...
