### ISSUE TITLE
Create a project output viewer

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/job-server#385]
While github will remain the canonical source, the Job Server should become the preferred place for people to view final project outputs, as it gives us an opportunity to add a number of usability enhancements.

Most importantly, redacted & released outputs can be rendered in a nice viewer. At the time of writing, Github is an adequate viewer, but we are likely to be moving to storing released outputs outside the git repo, as for IG reasons we don't want them to be versioned.

This means we'll want a way of rendering jupyter notebooks, markdown, HTML, and images nicely, inline. For example, we've discussed storing released outputs as build artefacts in Github releases.  Our viewer would proxy to those for the source of its content.

The viewer would use as its manifest the files specified in [a final `publish` action in the project pipeline](https://github.com/opensafely-core/output-publisher/issues/1).

It would use Github Release Versions to allow users to select historic outputs, although the default would always be the latest.

Longer term, we can imagine that papers etc might link to the "project" page in the job server, rather than directly to Github.  This might have a nice landing page that collects together the project overview, links to publications, links to codelists, links to IG approvals, and versioned outputs.

**Comment by sebbacon** [comment]
We've also discussed an `opensafely fetchdata` subcommand for grabbing data for local development etc

**Comment by ghickman** [comment]
@sebbacon – is this superseded by the reports app now?

**Comment by sebbacon** [comment]
No. The Reports app is for a curated subset of all outputs, which are always in HTML (usually Jupyter Notebooks).

There will be some code (e.g. look and feel) in common, though

**Comment by ghickman** [comment]
Done as part of the outputs voyage!
