### ISSUE TITLE
Address round two of project data improvements feedback

### ISSUE THREAD

**Issue by benbc** [opensafely-core/job-server#3871]
Carry out the remaining data tidy-up implied by the answers on the Queries tab in [this spreadsheeet](https://docs.google.com/spreadsheets/d/14BdA3Z4LHWP4HO2nuPohasf2rU9MaBG8h3qBdcfpbBM/edit#gid=1105473596).

Please also read through the Merged Projects tab to see if there are any other actions needed there.

If there are any queries during this work, please get an answer from the IG team directly rather than batching them up as last time.

**Comment by ghickman** [comment]
All follow-ups in the Queries tab have been addressed, apart from the `reinfection` workspace being part of Project 37, awaiting feedback from Amir to confirm what to do with it.

**Comment by ghickman** [comment]
We've identified 28 projects which still need to be assigned to an application/approved project.  Liam is talking to researchers to find where they should live.

**Comment by lucyb** [comment]
Liam has said that he's currently working on other priorities ([thread](https://bennettoxford.slack.com/archives/C04NHSU5DRB/p1709824398724189)), so won't be returning to look at this until mid-March at the earliest.

I'll remove it from the board now and move it back when I hear back from Liam.

**Comment by lucyb** [comment]
Closing as it's not clear any further work needs to be done on this (new tickets have since been opened for specific projects that need updating).
