### ISSUE TITLE
Type of study to include Short Data Report (Data curation) as an option below Research, Service Evaluation and Audit options.

### ISSUE THREAD

**Issue by LiamHart-hub** [opensafely-core/job-server#3874]
In the Job Server application form, in the [Type of study section,](https://jobs.opensafely.org/applications/9440/page/type-of-study/) we need to include a Study Type option called ‘Short Data Report’ “(Data Curation Projects)” as the fourth option in the study type list. This type of project runs differently from Research, Service Evaluations and Audits, as sometimes the condition of the data can be unknown. and therefore a report of the current condition of the data available is required- i.e. short data reports.

Taken from the DPIA (and cleared by Catherine) a description of what this means will need to be placed next to this option:
“OpenSAFELY supports ‘short data reports’ (sometimes also referred to as Data Curation Projects), which provide a carefully documented source of information on data quality that is beneficial to all users of NHS data. These cover four key areas: 
Clinical reports describing how a specific clinical area is recorded in NHS data. 
Demographic reports describing population characteristics and how they can be identified. 
Administrative reports describing patterns in NHS data. 
Methodological reports describing data processing techniques for NHS data. 

As the text is lengthy, but beneficial for clarity, I think it's better to display this text as a click or hover option over the word ‘short data report’ that reveals this describing text. This, of course, depends on the complexity of the task to do such a thing. Nonetheless, the inclusion of the short data report option is still required, and if a hover or clickable option is not available then the information next to it will be needed.  

Once the study type has been selected, the following page is specific to the type chosen.

The following page for short data report studies should contain the following text. There is no need for the researcher to enter extra information on that page. There should be a “continue” button at the bottom of the page which takes the researcher to the study funding page as for other study types.

Text:
“By defining your project as a short data report, you are also confirming it is not a research project, a service evaluation or an audit, as defined by the [HRA toolkit ](https://www.hra-decisiontools.org.uk/research/)and this [definition table](https://www.hra-decisiontools.org.uk/research/docs/DefiningResearchTable_Oct2022.pdf). 

Short data reports (sometimes also referred to as Data Curation Projects) provide a carefully documented source of information on data quality that is beneficial to all users of NHS data. These cover four key areas: 

Clinical reports describing how a specific clinical area is recorded in NHS data. 
Demographic reports describing population characteristics and how they can be identified. 
Administrative reports describing patterns in NHS data. 
Methodological reports describing data processing techniques for NHS data

Your line manager (which could be a principal investigator you work with) must
email [applications@opensafely.org](mailto:applications@opensafely.org) to confirm your project is a short data report (and not a research project, service evaluation or audit), 
and that they have read the Study Information and Study Purpose, and our [OpenSAFELY principles](https://www.opensafely.org/about/), and they support the application. 

You must also provide evidence this is not research, a service evaluation or an audit, for example, by completing the HRA Decision toolkit, https://www.hra-decisiontools.org.uk/research/, or providing a note from your institutional ethics committee confirming the study is not research, a service evaluation or audit.”

**Comment by lucyb** [comment]
NOTE: The IG Team will need to regenerate their PDF of the application form after this change has been made.

**Comment by LiamHart-hub** [comment]
Marvelous. Thanks Iain :)
