### ISSUE TITLE
Ensure people can self-serve deployment of their own job-server 

### ISSUE THREAD

**Issue by tekkisse** [opensafely-core/job-server#398]
README suggests that the supplied .env should start a working job-server but it will not start up.  Are there additional steps needed ?

**Comment by ghickman** [comment]
@tekkisse – thanks for finding this, you're the first user who's tried the project out!  I'm planning on tidying this up by mid-March.

**Comment by evansd** [comment]
First _external_ user. We do actually run this ourselves!

**Comment by tekkisse** [comment]
@evansd - what is ment by that ?

i never said it was wrong ?  merely asking if there are any yet undocumented steps that are needed, because without more understanding i can not get it to run.

As the biggest supplier of Academic TRE's in the UK (x28) and 6 internationally - we need to understand how it works and how such a thing could fit into our approach and deliver the vision that Ben is proclaiming.

**Comment by evansd** [comment]
Hi @tekkisse, it was a silly joke based on deliberately misunderstanding George's comment to mean that literally no one had run this code before.

Yes, absolutely the intention is to make all these projects easy for anyone to get up and running with based on solely on the public documentation. Unfortunately we're a tiny team right now and everything is being developed very rapidly and so stale documentation is one of the casualties of that. In this particular case the README needs fixing and hopefully we'll be able to do that at some point in the next few weeks.

**Comment by sebbacon** [comment]
Just to clarify, the documentation for **end users** of the framework, the [documentation](https://docs.opensafely.org) is up to date.

For people who want to run OpenSAFELY themselves, the documentation is lagging because until now, we've been the only people who deploy the framework itself - it's great to hear you'd like to evaluate it. As it stands there may be one or many steps missing so I'd recommend waiting until we've had a chance to go over it properly, which will be in the next four weeks at the latest. If it can't wait then drop us a line (team@opensafely.org) and we could set up a call.

**Comment by sebbacon** [comment]
Have changed the issue title

Error message reported by OP:

> docker-compose just returns Unknown User Dummy

**Comment by bloodearnest** [comment]
This is a good goal. Thoughts:

- We are not using docker-compose.yaml in prod anymore, so we could repurpose it to be a dev deployment?
- It can deploy mssql and/or presto, and we can have the default env creds point to that.
- We should maybe create a 'test' or 'dev' backend concept?
- We shouldn't make the dev polling url be the production job-server instance, or else confusion would likely arise. (t wouldn't affect production at all (as writes are authenticated), but it would be confusing to see random jobs coming in (and failing) on your local job-runner instance.
- We should check job-runner works on public repos without a PRIVATE_REPO_ACCESS_TOKEN

**Comment by sebbacon** [comment]
> It can deploy mssql and/or presto, and we can have the default env creds point to that.

Ideally we'd have a "test" backend with data generated by the same mechanism as the cohortextractor test fixtures for one of the existing backends (e.g. EMIS).  This could be deployed in a local sqlite?
