### ISSUE TITLE
Test `release` command

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#3986]
We don't typically test commands and aim to make them as thin wrappers as possible around a function call, avoiding the difficulties that running commands directly can bring.

The `release` command has broken, likely due to changes to the underlying `jobserver/releases.py::create_release` function.  This command is very useful to developers when they want to work with releases without having to understand how to construct a working Release object.

We'd like to ensure this command keeps working, and having it create Releases and ReleaseFiles in a test should be fine, so I think we can add tests for it.

We should be able to delete these files after tests have run too.

**Comment by lucyb** [comment]
@ghickman is the `release` command still broken or does it still need to be fixed?

**Comment by ghickman** [comment]
Nope, fixed in #3987
