### ISSUE TITLE
Make it clear what URL to use to report errors

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/job-server#402]
When there's an error which a user can't resolve in their job run, we should make it clear what they need to do next - specifically, which URL they need to copy and paste into Slack or the Discussions forum.

At the moment people either post screenshots of errors, or just give a URL to their workspace.

As an idea, how about adding text to this error message along the lines "click view button to debug"

![image](https://user-images.githubusercontent.com/211271/108048630-2b802100-703f-11eb-8752-5fdd7d4d6a06.png)

And then somehow making "next steps" clearer on this page

![image](https://user-images.githubusercontent.com/211271/108048885-7b5ee800-703f-11eb-9556-36ee3d0e30a2.png)

e.g. "What to do next" header? And some text "if you don't have access or need support from someone else, provide <this link> in your support request" or similar?

**Comment by ghickman** [comment]
@sebbacon – do you feel like this is still an issue? I'm not sure how we can measure it but I _think_ people are posting job links more often than not now?
