### ISSUE TITLE
Link to diff between code for JobRequests

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#4034]
We want to help users understand what's changed in their code between jobs.  We store the commit sha for the latest commit on the configured branch of the Workspace as part of the JobRequest a user creates.  When job-runner picks up this request it uses that sha to check out the expected version of the code for a job to run.

Since we know the sha for all jobs via their JobRequest we can show a link to GitHub's compare view on both the JobDetail and JobRequestDetail pages comparing the current JobRequest with the previous one.

As part of this ticket, it would be useful to look into the feasibility of extending the comparison for JobRequests which have failed, back to the most recently successful request.

[Slack conversation](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1706273317250379)

**Comment by Jongmassey** [comment]
Job detail screenshot 

![image](https://github.com/opensafely-core/job-server/assets/25795240/cce43abb-d098-46f1-9516-ae8697434d14)


Job request detail screenshot

![image](https://github.com/opensafely-core/job-server/assets/25795240/1a8704d6-53f8-4d45-94a3-060b6de205a0)
