### ISSUE TITLE
Remove ensure_admins and related code paths

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#4035]
> [!NOTE]
>This should be done before https://github.com/opensafely-core/job-server/issues/4105

In an effort to move away from a boolean staff field, we ended up with the `CoreDeveloper` role as an unintentionally more complicated of `User.is_staff`.  That's a problem for a different time, but how we assign this role is also problematic.

#### Method
Via the dev&prod entrypoint scripts we run the `ensure_admins` management command.  This reads the list of strings defined in `ADMIN_USERS` to get a list of User instances by username (ignoring any that don't exist).  We then drop CoreDeveloper for all users and apply it to the list we built from the env var.

#### Pros
This was built to avoid the chicken and egg problem, both in dev and prod, of a running instance having no staff users, and thus no way in the UI for a user to set that, either for themselves or anyone else. Early on when we weren't planning to add all staff to the staff area this worked fairly well.  Adding users was done sparingly and very infrequently.

#### Cons
Over time we shifted our stance to giving any staff member access to the staff area.  After all, it exists to help staff do their jobs.  We now regularly find ourselves assigning CoreDeveloper to a user in the UI, confirming they can access the staff area, and then getting a message sometime later saying they can no longer access it.  This is because the person making the change has not updated the ADMIN_USERS env var so the change in the UI is effectively revoked. (IIRC I, the author of the design and implementation, am at ~100% failure rate with this for reference!)

This method also means the CoreDeveloper role acts differently to all the other roles, but it's not _clear_ that it's different.

#### The Fix
Remove:
* the `ensure_admins` management command
* the jobserver/authorization/admins.py module of code and its tests
* the call to `ensure_admins` in the entrypoints
* references to it in DEVELOPERS.md
* the reference to it in pyproject.toml
* any other places it's used or referenced in the codebase
* all references to ADMIN_USERS

Once deployed we can then drop ADMIN_USERS from the configuration in prod.

It would be ideal to have @bloodearnest go over what's done for this given he was involved in the feature and has been a part of various discussions to remove it over the years.

**Comment by lucyb** [comment]
We should do this ticket _before_ #4105. See slack [conversation](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1723625513243139) for details.
