### ISSUE TITLE
Fix missing info box title on UserDetailWithOAuth page

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#4044]
We have two info boxes for missing data on the UserDetailWithOAuth page, selectively showing if a user is missing link(s) to a Backend, Org, or Project.  One of the boxes handles Orgs and Backends, and its title is incorrectly set to "No projects".

Related to this, I can't remember why we split this into two boxes.  @tomodwyer or @lucyb might know?

**Comment by lucyb** [comment]
I don't know. One box would seem to make more sense.

**Comment by tomodwyer** [comment]
Nope, no idea why we did that 🤷

**Comment by ghickman** [comment]
Given no-one can remember why we split them up, I think the pragmatic choice here is to merge them, and set a generic title on the card 👍

**Comment by Jongmassey** [comment]
Merging the current explanatory texts

> A user <strong>requires</strong> access to certain resources to be able to use the Jobs site. The following are missing for this user:
> [...]
> If you think this is incorrect, please speak to the IG Team.

and

> A user would ideally have access to one or more Projects.


doesn't really fit as the suggested action for the former doesn't really apply to the latter?
