### ISSUE TITLE
Rotating the OSI GitHub token

### ISSUE THREAD

**Issue by benbc** [opensafely-core/job-server#4085]
The OSI Github token (`opensafely-interactive-token`) is about to expire.

I tried to follow the [rotation instructions](https://github.com/opensafely-core/job-server/blob/main/DEVELOPERS.md#rotating-the-osi-github-token), but I was unable to log into the bot GitHub account because 2FA is required. I wonder if this has been enforced since the instructions were written.

Please could you rotate the token yourselves if it is urgent.

Please also update the instructions (and also check the other rotation instructions linked from the [playbook](https://bennettinstitute-team-manual.pages.dev/tech-group/tech-support/playbook/#expiry)).

**Comment by StevenMaude** [comment]
I've updated the token.

**Comment by StevenMaude** [comment]
ebmdatalab/team-manual#636
ebmdatalab/team-manual#637

**Comment by StevenMaude** [comment]
The above PRs are now merged, so closing this issue.
