### ISSUE TITLE
Unexpected Traffic

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#412]
Sentry is showing a selection of Invalid HTTP_HOST header values hitting job-server, I _think_ this is related to the test instance which was spun up recently.

@bloodearnest or @madwort  – could you confirm the extra traffic is hitting that test instance?  If that's the case could we limit traffic pointed at it to only the expected domain?  (might need to configure ALLOWED_HOSTS for that too?)

**Comment by madwort** [comment]
yes, I think this is the test instance

**Comment by madwort** [comment]
the test instance is sending these messages to the "development" enviroment on sentry - the current instance is sending them to "production"

**Comment by madwort** [comment]
ah, yeah, the lexicographically first vhost gets the default - have used [their template](https://dokku.com/docs/configuration/nginx/#default-site) to refuse connections for unknown vhosts & verified it works as intended (e.g. http://142.93.40.50/PSIGW/PeopleSoftServiceListeningConnector ) - given that it's mostly spam/bots seems preferable to 410?

**Comment by ghickman** [comment]
444 sounds good to me.

**Comment by madwort** [comment]
Doesn't seem to have solved the issue - digging a bit more

**Comment by madwort** [comment]
Ok, created a minimal blank dokku app named `00-default-blank` using the nginx buildpack, hopefully that will take the hit as the default site now.

**Comment by madwort** [comment]
ok, yeah, the continuing log entries were https traffic getting converted to http traffic by CloudFlare, using a dokku app means that I can also use letsencrypt to easily switch default https to that app & away from job-server

**Comment by madwort** [comment]
pretty sure I've got this covered now
