### ISSUE TITLE
Show warning about the policy for released (not published) files

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#4131]
From slack [thread](https://bennettoxford.slack.com/archives/C63UXGB8E/p1706899245985629?thread_ts=1706789672.606579&cid=C63UXGB8E).

It's been reported that sometimes researchers can get confused about what is permitted for released files. The UI in the outputs viewer is very similar for unreleased files, released files and published files, so we should provide more information.

We should repeat some of the text from the Policies for Researchers and link to that page on outputs viewer when someone is viewing released files.

![Image](https://github.com/opensafely-core/job-server/assets/3889554/22416d88-b423-450b-898c-72cc57860a78)

**Comment by tomodwyer** [comment]
## `release/detail.html`

![CleanShot 2024-02-21 at 16 34 01@2x](https://github.com/opensafely-core/job-server/assets/24863179/88575529-86eb-4ddc-894f-3bab714450bf)

## `workspace/latest_outputs_detail.html`

![CleanShot 2024-02-21 at 16 34 10@2x](https://github.com/opensafely-core/job-server/assets/24863179/731ce81a-6d19-4702-9993-783d00f1d528)

## `release/snapshot.html`

![CleanShot 2024-02-21 at 16 34 17@2x](https://github.com/opensafely-core/job-server/assets/24863179/bae78bc0-6629-4160-a69d-51c73270ebef)

## `release/snapshot.html`

![CleanShot 2024-02-21 at 16 34 21@2x](https://github.com/opensafely-core/job-server/assets/24863179/bb9f20aa-6751-4c49-ac70-86437cc235e1)

**Comment by tomodwyer** [comment]
@Jongmassey 🤦 yes, it didn't auto close
