### ISSUE TITLE
Renaming a project caused a redirect to the same URL

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/job-server#4158]
## Steps to reproduce

1. Go to a project in the Staff Area
2. Rename the project
3. Update the project slug
4. A redirect is created which has the same "to" and "from" URLs

**Comment by StevenMaude** [comment]
I had a quick look at this without yet solving it.

If I try reproducing locally, I found I don't even need to rename the project. Updating the project slug alone creates the redirect that has the same "to" and "from".

**Comment by Jongmassey** [comment]
Once this is fixed (i.e. such that no new spurious redirects are created) do we want to go and remove those that have been created?
