### ISSUE TITLE
Remove organization-level roles

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#4198]
As well as project-level roles, Job Server can record organization-level roles. In practice, it doesn't because:

* they aren't exposed in the UI
* they aren't audited[^1]
* it's unclear how they would interact with project-level roles
* it's unclear whether there is an IG process associated with them

[^1]: The audit log contains entries for three events: _User added [to project]_, _User removed [from project]_, and _User's roles updated [in project]_.

@CLStables suggests either clarifying why organization-level roles exist, and describing the work that would be required to implement them fully, or removing them.

---

@CLStables created this issue as a draft, following a Slack discussion.[^1] It contained two actions, which related to organization roles and the Leaver Checklist. This issue relates to organization roles. #4197 relates to the Leaver Checklist.

**Comment by lucyb** [comment]
I've removed the OrgCoordinator role in [this PR](https://github.com/opensafely-core/job-server/pull/4513) as it's not used. This also included removing mention of it in the UI (which was previously broken anyway). However, the ability to add organisation-level roles remains and should be removed in future too. I anticipate this work will be done as part of the Job Server roles and permissions initiative.
