### ISSUE TITLE
User requests update to permissions to edit workspace purpose

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/job-server#4202]
Request received by email for user Pedro Oliveira who needs to update a workspace purpose, but is getting a 403 at https://jobs.opensafely.org/prostate-cancer-psa-testing/prostate_cancer_psa_testing_2021/edit/.

He has the Project Collaborator role, and would need Project Developer - however I'm not sure enough of who is allowed to have what roles on job-server to just go ahead a do it :)

**Comment by iaindillingham** [comment]
@LiamHart-hub has agreed to take over, as this is an IG issue. Pedro does indeed have the project collaborator role and would indeed need the project developer role. Adding this project-specific role is audited.

Related Slack threads:
* https://bennettoxford.slack.com/archives/C069SADHP1Q/p1710509602906809
* https://bennettoxford.slack.com/archives/C63UXGB8E/p1710507206584009
* https://bennettoxford.slack.com/archives/C04NHSU5DRB/p1710507485866319
