### ISSUE TITLE
Document current behaviour associated with roles, permissions, and auditing

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#4229]
There has been some confusion about roles, permissions, and auditing. Documenting current behaviour would help us reduce this confusion and reach a consensus about terminology, and consequently would help us communicate more effectively.

Although the source of truth is the codebase, the codebase isn't legible to colleagues outside the tech team. Consequently, it would be better to document current behaviour in a Google doc, accepting that a Google doc will need to be maintained until an alternative medium is agreed upon.

**Comment by lucyb** [comment]
We are documenting the current (and desired) behaviour in this [spreadsheet](https://docs.google.com/spreadsheets/d/1UgeWCcbom0Qr2GleY9kx_FuJ8_5vmYC4OTemXR9Ccio/edit?gid=0#gid=0).

**Comment by lucyb** [comment]
We discussed the outcomes of the workshop (as detailed in the spreadsheet linked in my previous comment) with Juliet and Liam. We've agreed a way to improve some of the existing documentation, described in #4584. We don't expect to do any further work to document the roles and permissions beyond that, so I'm closing this ticket.
