### ISSUE TITLE
Merge "Immunosuppresant medication" projects

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#4258]
At the request of @LiamHart-hub, this project:
https://jobs.opensafely.org/staff/projects/immunosuppresant-medication/

Needs merging into:
https://jobs.opensafely.org/staff/projects/investigating-events-following-sars-cov-2-infection/

This involves:
- [ ] TBC

**Comment by lucyb** [comment]
Confirmed with Liam that this is no longer required.

**Comment by LiamHart-hub** [comment]
Thanks Lucy
