### ISSUE TITLE
Remove T1OO permission from several Bristol projects

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#4259]
Our Bristol colleagues would like to remove the T1OO permission from several of their projects (see below). This is because they're submitting manuscripts now and expect reviewers to ask for follow-up analyses later, but the gap between submission and follow-up is likely to bridge the T1OO deadline. Rather than generate results for submission that include opt-outs, and then regenerate results for follow-up analysis that exclude opt-outs, it would be easier for our Bristol colleagues to generate/regenerate results that exclude opt-outs in both cases: now and later.

Removing the T1OO permission means editing `jobserver/permissions/t1oo.py`. Rather than removing the project ID from `PROJECTS_WITH_T1OO_PERMISSION`, we should instead comment out the project ID, and explain why it was removed.

`jobserver/permissions/t1oo.py` is owned by the IG team. Consequently, the resulting PR **must** be approved by a member of the IG team.

The projects:

* https://github.com/opensafely/post-covid-gastrointestinal
* https://github.com/opensafely/post-covid-autoimmune
* https://github.com/opensafely/post-covid-neurodegenerative
* https://github.com/opensafely/post-covid-renal
* https://github.com/opensafely/post-covid-respiratory-incident-events
* https://github.com/opensafely/post-covid-respiratory

There are two accompanying Slack threads. In [the first][1], @inglesp and @evansd help me understand how the T1OO permission is implemented. In [the second][2], @venexia links to the projects. Thank you all for your help 🙂.

[1]: https://bennettoxford.slack.com/archives/C069YDR4NCA/p1712227850330649
[2]: https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1712234011220129

**Comment by iaindillingham** [comment]
This issue would benefit from @CLStables's 👀.

**Comment by iaindillingham** [comment]
NOD discussed this today. @cewalters and @ptid1976 are going to make a decision; I'm going to move it off team-rex's board until they've done so.

**Comment by lucyb** [comment]
Is this ticket still needed?

**Comment by venexia** [comment]
This was an interim solution from before the T1OO deadline so I don't think it is needed anymore?

**Comment by lucyb** [comment]
Thank you. I'll close it now, although it can always been reopened if needed.
