### ISSUE TITLE
Update projects dashboard (on job server) to match co-piloting dashboard

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#4285]
Is it possible (and easy) to make the columns on the [projects dashboard](https://jobs.opensafely.org/staff/dashboards/project/) match those on the [co-piloting dashboard](https://jobs.opensafely.org/staff/dashboards/copiloting/)? (though there seems to be a bug: org names are missing from the co-piloting one)

I think this would help people more easily see which non-copiloted projects have the "ongoing" status when they shouldn't, as this information is currently visible to me in grafana but not easily accessible to people on the service side of the org. 

An alternative would be to create a new dashboard in grafana, but updating the one in job server seems like it would be much quicker...?

Note: fetching the org, in particular, may cause performance issues.

Timebox: 1 day.

**Comment by iaindillingham** [comment]
Co-piloting columns:

* Project
* Organisation
* Co-pilot
* Project status
* Repo status
* Workspaces
* Job requests run
* First run job
* Last run job
* Files released

Projects columns:

* Project
* Organisation(s) (change to Organisation)
* Co-pilot
* Project status (add)
* Repo status (add)
* Workspaces
* Job requests run
* Job first run (change to First run job)
* Last run job (add)
* Total files released (change to Files released)

**Comment by iaindillingham** [comment]
This should, in principle, take a day. However, I uncovered a couple of issues since starting it, which we have discussed as a team. See:

* #4318 
* #4317 
* #4315 

As this issue isn't critical, and as our target date for the current initiative is approaching, I'm going to give it the deck-scrubbing label and remove it from the board.

**Comment by lucyb** [comment]
Is this something that we still want to do?

**Comment by iaindillingham** [comment]
I'm going to say no. At least, not until someone asks for it (or something like it) again.
