### ISSUE TITLE
Update interactive-reports used in Job Server

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#4298]
See slack [thread](https://bennettoxford.slack.com/archives/C0441RRL3RC/p1713798454581309?thread_ts=1712762858.269459&cid=C0441RRL3RC) for context.

When interactive-reports repo is updated it should trigger a PR on job-server. However, the version in job-server appears to be from 12/09/2023 as it's tagged v2023.09.12.100407. There were changes to interactive-templates a few weeks ago, so it should have been updated.

This issue is to do a one-off update of interactive-reports.

**Comment by StevenMaude** [comment]
Assuming this is the interactive-templates repository that's being referred to (the version matches), the update should be completed as part of #363.

Typically, updates aren't automatic; it requires someone to follow the release process in interactive-templates (run `just release` there, merge the corresponding pull request for that new release branch, and a job-server PR should be opened with the update, triggered by the a workflow in the interactive-templates repository).
