### ISSUE TITLE
Make the deploy Action Blocking

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#433]
When we merge multiple subsequent PRs, eg on Monday mornings for Dependabot, we end up with failing deploys because dokku will [correctly] only execute one deploy at a time.

[It seems we're not alone](https://github.community/t/how-to-limit-concurrent-workflow-runs/16844).

Mentioned in that thread, the [turnstyle](https://github.com/softprops/turnstyle) action looks useful.

**Comment by madwort** [comment]
same here https://github.com/ebmdatalab/datalab-team-manual/issues/27 - was considering https://github.com/styfle/cancel-workflow-action but not tried

**Comment by madwort** [comment]
alternative idea: deploy on schedule rather than on push https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule (as deploy is `git push`, will be virtually a no-op if nothing merged?)

**Comment by StevenMaude** [comment]
Looking up something independently and spotted the new (2021-04-19) [`concurrency`](https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/) feature (albeit in beta), which I suspect might fix this.

**Comment by madwort** [comment]
great news, `concurrency` seems like it'll do exactly what we need.

**Comment by ghickman** [comment]
Ok so in initial testing this mostly worked.

Merging #488, #487, & #486 (in that order) resulted in the expected 3 runs ([black](https://github.com/opensafely-core/job-server/actions/runs/806670558), [responses](https://github.com/opensafely-core/job-server/actions/runs/806670740), & [pytest-mock](https://github.com/opensafely-core/job-server/actions/runs/806670998).

The run for black ran without issue, the run for responses was cancelled because of a "higher priority job", and the run for pytest-mock was queued at the `deploy` job, until the deploy of black completed.

So this worked for the happy case as expected but I've yet to find an explanation for why the responses merge got cancelled on me.

**Comment by madwort** [comment]
The docs say say "[Any previously pending job or workflow in the concurrency group will be canceled](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency)" (even if you don't have `cancel-in-progress` turned on), so it probably went:

* merge 488
* start deploy for 488
* merge 487
* queue 487
* merge 486
* queue 486
* => cancel 487
* end deploy for 488
* start deploy for 486
* end deploy for 486

Which in this case is fine. But added to their other caveat `When concurrency is specified at the job level, order is not guaranteed for jobs or runs that queue within 5 minutes of each other.` means I guess we could see some race conditions - where a newer merge gets cancelled whilst queued by an older merge. But it'll become consistent after any subsequent merge...?

**Comment by ghickman** [comment]
Ah, of course, because I merged from newest to oldest - that makes sense!  I've been using this for some other deploys and it's worked As Expected, so I think we can close this one out if you're happy with it too?

**Comment by madwort** [comment]
yep

**Comment by ghickman** [comment]
@inglesp @rebkwok – you maybe find this (and the linked PR) useful for your respective projects.
