### ISSUE TITLE
Consider removing django-upgrade

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#4339]
[django-upgrade](https://github.com/adamchainz/django-upgrade) is a tool for automatically upgrading Django project code. The tool seems to rewrite the code to match a target Django version.

Although `just django-upgrade` invokes the tool, I'm not aware we've actually used it. We should consider removing it; alternatively, we should consider documenting when we would use it.

**Comment by bloodearnest** [comment]
FWIW, George used this whenever he did a django upgrade
