### ISSUE TITLE
Metrics GitHub GITHUB_OS_TOKEN PAT needs recreating by sufficiently-privileged user

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/job-server#4383]
The PAT in use by metrics to get codespaces for the `opensafely` org was deleted after I [lost admin privs](https://bennettoxford.slack.com/archives/C63UXGB8E/p1718888852500409). I recreated it and added it to the dokku config for metrics last week, but did not test it. Having now tested it, [it does not work](https://bennettoxford.slack.com/archives/C63UXGB8E/p1719227213064299?thread_ts=1719220374.042579&cid=C63UXGB8E).

I have now tested the GH_OS_CORE and GH_EBMDATALAB tokens that I created and are also in use by metrics and these appear to be working fine.

Someone with the right privileges (a bennet-admin?) needs to recreate at least the `GITHUB_OS_TOKEN` and probably the other two as well for consistency.

**Comment by iaindillingham** [comment]
I'm confused, @Jongmassey. Did you accidentally create this issue in the wrong repository?

**Comment by Jongmassey** [comment]
I did! And then couldn't transfer it or delete it (I don't think?)
