### ISSUE TITLE
Improve UX for unauthenticated users browsing to private Github Repos

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/job-server#442]
For transparency, we currently allow unauthenticated users to see most information on the job server.

This means for any private repo, when they view [a project page like this one](https://jobs.opensafely.org/anticoagulant-sensitivity-analysis-5-check/), they are presented with a link to a repo to which they have no access; Github then gives a 404, which makes it look like all our links are broken
![image](https://user-images.githubusercontent.com/211271/113147543-c700d600-9228-11eb-8db7-f9f7fb26f5ac.png)

In the first instance, some explanatory text would be good on the home page, at least for unauthenticated users. Ben suggested

> some very brief light touch single para explainer at the top of the page to explain that this is a working tool for the team; shows every github repo and commit ID for every task executed against the data. Some GitHub links will show a 404 if you are not logged in, or not part of an OpenSAFELY analyst group: that means the repository is currently closed; we log all repo's and commit IDs executing code against NHS data here; we require analysts, at minimum, to make code open at the time when results are shared publicly; you can read the Principles of OpenSAFELY here

**Comment by sebbacon** [comment]
Longer term perhaps we can also intercept private links, per my notes in Slack:

> Longer term I presume we could do something with https://github.com/opensafely-core/job-server/blob/ef0d28b16f84e875512de468440763f1fb4aaf41/jobserver/github.py#L117-L150 to return public/private state for each repo and do something with that when rendering links

**Comment by madwort** [comment]
@sebbacon first pass, wdyt?

```
All jobs executed on production data are logged on this site as they happen, with a link to the github repository and commit reference that uniquely identifies the exact code that was run. However, in accordance with the [Principles of OpenSAFELY](https://opensafely.org/principles/) some Github repositories are kept private until the results are shared publicly, at which point we require the entire repository to be made public. If the repository is currently private, any links to it from this site will return 404 unless you are logged in and have the relevant permissions. 
```

follow-up thoughts
* have we unintentionally moved to essentially closed-by-default for analysis repos?
* reading around the issue https://docs.opensafely.org/en/latest/open-methods/ , https://opensafely.org/principles/ , it feels like something that's not quite living up to our rhetoric around OpenSAFELY, and is slightly tucked away in the terms & conditions (in that sense, I feel like the original poster does have a good-ish point...) 
* I think we (the team) have good ideas about why closed is important (i.e. academic credit / citations), it might be nice if someone with more clue than me had the time to write up a blog discussing the issues around this & why a lot of our analyses are currently closed, and link it to from this para?

**Comment by madwort** [comment]
It also strikes me that this page could use the same [private] badge that github has 
<img width="64" alt="Screenshot 2021-03-31 at 16 46 09" src="https://user-images.githubusercontent.com/2082895/113172735-9d53a900-9240-11eb-906f-7aef055ee5c4.png">

<img width="784" alt="Screenshot 2021-03-31 at 16 45 12" src="https://user-images.githubusercontent.com/2082895/113172619-7bf2bd00-9240-11eb-95d7-9899bf174518.png">

**Comment by ghickman** [comment]
We can grab the `isPrivate` field from the [Repository](https://docs.github.com/en/graphql/reference/objects#repository) object as part of [this query](https://github.com/opensafely-core/job-server/blob/baca754f6d6283f39bde9911039a5f1e71b6c557/jobserver/github.py#L90-L98).
