### ISSUE TITLE
[Spike] Transfer a dashboard from job-server to Grafana

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#4454]
job-server has [four dashboards](https://jobs.opensafely.org/staff/dashboards/) that could be transferred to Grafana[^1] (i.e. https://dashboards.opensafely.org/). Following a quick poll,[^2] it looks like they are used as follows:

* **Copiloting**. Brian and Millie. Clinical Informatics.
* **Private Repos**. Nick.
* **Projects**. Liam and Juliet. Information Governance.
* **Repos with Multiple Projects**. Liam and Juliet. Information Governance.

For this spike, we should choose a dashboard to transfer to Grafana, and work with its users to establish that they can access Grafana and can use the dashboard effectively. We should time-box the development work to one or two days, with a short window for working with users.

Following this spike, if we choose to transfer all four dashboards, then we should write an ADR.

[^1]: The "Copiloting" dashboard in job-server isn't the same as the "Copilot dashboard" in Grafana.
[^2]: https://bennettoxford.slack.com/archives/C31D62X5X/p1721209714684339

**Comment by iaindillingham** [comment]
Thanks for this, Jon. Couple of questions:

* Is it possible to replicate column-level sorting in the job-server dashboard?
* Similarly, is it possible to replicate column-level filtering? ([Variables](https://grafana.com/docs/grafana/latest/dashboards/variables/) look like they would be useful. See the [Product dashboard](https://dashboards.opensafely.org/d/adb76f4d-0bcc-4d0d-adb3-e2fcbfcc6993/product-dashboard?orgId=1), too.)

**Comment by Jongmassey** [comment]
>Is it possible to replicate column-level sorting in the job-server dashboard?

I find that clicking on the column header in the panel [sorts](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/table/#sort-column) it - is that not working for you?

>is it possible to replicate column-level filtering?

Yes - filtering on org and project now added :)

**Comment by iaindillingham** [comment]
Ah, I see! The arrow icon appears on the sorted column, not all columns. Thanks for pointing that out. And thanks for adding filters 👍🏻

**Comment by Jongmassey** [comment]
Implementation notes from this spike on some rough edges encountered:
* the setting for enabling value filters for a Table isn't the most obvious - I've now turned this on and probably negates the need for the Copilot/Project filters (Org might be more complex on account of multiple orgs for a project being concatenated into a single field)
* The "Github opensafely" data source includes only private repos
  * therefore to infer private repos, this panel requires pulling in the list of repos from the Job Server database project table and those that are missing from the github data source are therefore private
* It's hard to resolve cardinality mismatched data in a Mixed data source
  * There is a one-to-many relationship between projects and repositories
  * When using a Mixed data source, one can only do simple single-column joins where the join key column is named identically on both sides.
  * It's seemingly not possible to do multiple sequential joins (e.g. to join tables A & B, perform some aggregation and then join this result to C)
  * It's not possible to reference an existing dashboard (e.g. where one might have already done the aggregation and formatting necessary to resolve the cardinality mismatch)  in a mixed data source.

This is why the "private repos" information is in a separate panel, not inlined into a field within the main panel.

**Comment by Jongmassey** [comment]
Copilot [slack thread ](https://bennettoxford.slack.com/archives/C028EJH752A/p1722331049952179) discussing this spike

**Comment by Jongmassey** [comment]
Slack reminder set for 6 months for `#team-rex` to follow up on usage of this.
