### ISSUE TITLE
Add unit test to fail on warnings in Django Templates

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#4462]
We currently ignore errors in our Django templates ([example](https://bennettoxford.slack.com/archives/C01SE1WB6AW/p1721142918550459)). This is good because then users don't see an error, but it's bad because we don't see the error either. In Airlock, they've configured their app to produce warnings if there are missing variables and added a unit test to fail if there are any warnings. We should do the same in Job Server.

In Airlock, the main bit of code is this logging filter defined here:
https://github.com/opensafely-core/airlock/blob/e4b686debd5738ff639ec469db2396c78cd55fb1/airlock/settings.py#L363-L399

Which is then used in the logging config here:
https://github.com/opensafely-core/airlock/blob/e4b686debd5738ff639ec469db2396c78cd55fb1/airlock/settings.py#L421-L424

Finally, there is a hook in the main conftest.py file which fails the test run if any warnings are present:
https://github.com/opensafely-core/airlock/blob/e4b686debd5738ff639ec469db2396c78cd55fb1/tests/conftest.py#L35-L40

Warnings that they don't care about are configured in pyproject.toml:
https://github.com/opensafely-core/airlock/blob/e4b686debd5738ff639ec469db2396c78cd55fb1/pyproject.toml#L28-L31

**Comment by iaindillingham** [comment]
@lucyb suggested that the changes made as part of this issue are accompanied by an ADR, which is a honking good idea.
