### ISSUE TITLE
SPIKE Show human readable permissions when selecting a role

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#4521]
Create a mock-up of what it would look like to expose the permissions to someone editing a user's permissions and to show those permissions in a human readable form. i.e:

* When you select a role, there is a box to the side which says in prose what the current permissions allow and do not allow the user to do
* When you tick a role, those permissions update in real time, before you press save
* For example: Project Developer
   This user can: View the staff area, Update X
   This user cannot: Run jobs in any project

**Comment by tomodwyer** [comment]
The deployed app is here :point_right:  [ebmdatalab.github.io/job-server-permissions-ui](https://ebmdatalab.github.io/job-server-permissions-ui)
The source code is here :point_right: [github.com/ebmdatalab/job-server-permissions-ui](https://github.com/ebmdatalab/job-server-permissions-ui)

If you want to run it and test it locally, you'll need Node/npm, clone the repo, run npm install and then npm run dev. After that you can mess with the Roles and Permissions files, which will change what is shown to the user.

I'm happy for people to come up with any ideas for roles and permissions and drop them on to branches for testing.
