### ISSUE TITLE
Remove `attrs`

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/job-server#4532]
Similar to #4491, we could consider removing `attrs`.

It's used in a few places. However, from a quick look, it doesn't seem like we often use much additional functionality over that which Python's dataclasses provide.

(This was prompted by reviewing #4531 and wondering what we used `attrs` for.)

**Comment by StevenMaude** [comment]
This is actually dependent on interactive-templates; that depends on `attrs` too.

If we ever remove the use of interactive-templates, we can completely remove `attrs` as a dependency. In the meantime, we can clean up the uses of it in the job-server code directly.

**Comment by StevenMaude** [comment]
#4456 is the first part of this.

**Comment by iaindillingham** [comment]
As #4556 is merged, and as completely removing `attrs` is wrapped up in removing interactive-templates, I'm going to close this issue.
