### ISSUE TITLE
Project page doesn't load when GitHub API is unreachable

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#4534]
We received this error on the project detail pages when the GitHub API was temporarily unavailable recently (see [slack](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1723554717290339) 🧵 ).
https://ebm-datalab.sentry.io/issues/5708489567/?alert_rule_id=10884789&alert_type=issue&notification_uuid=9b0e6bca-d903-4eaf-a0c7-1be130894177&project=5443358&referrer=slack 

This resulted in a 500 error back to users when they tried to view any project detail page (Dave tested it on the [internal project](https://jobs.opensafely.org/opensafely-internal/)). 

We can expect to receive these errors from time-to-time as GitHub's API may not always be available and should handle them more gracefully. 

Note: we received a [similar error](https://ebm-datalab.sentry.io/issues/5708512496/?alert_rule_id=10884789&alert_type=issue&notification_uuid=ecef0488-2232-4b76-a3a7-707898d01ab7&project=5443358&referrer=slack) from another endpoint at the same time

**Comment by Jongmassey** [comment]
This is a little strange as I believe this scenario is already handled by this [block ](https://github.com/opensafely-core/job-server/blob/e1870ad339f06a3410eb47bebe99cc7f94cff664/jobserver/views/projects.py#L172-L177) and this corresponding [test](https://github.com/opensafely-core/job-server/blob/e1870ad339f06a3410eb47bebe99cc7f94cff664/tests/unit/jobserver/views/test_projects.py#L175-L199)
