### ISSUE TITLE
Clarify copilot-project relationship and associated permissions

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/job-server#4536]
Current, a `User` can be [associated ](https://github.com/opensafely-core/job-server/blob/main/jobserver/models/project.py#L37-L42) with a `Project` as its Co-pilot.

In many cases, it also appears in many cases, that co-pilot is also listed as a `ProjectCollaborator`, has membership with no role, or has no listed membership :

```sql
with copilots as  (
  select 
    id as project_id,
    copilot_id
  from jobserver_project
  where copilot_id is not null
)
select 
  pm.roles,
  count(*)
from copilots c
left join jobserver_projectmembership pm 
  on pm.user_id = c.copilot_id
  and pm.project_id = c.project_id
group by pm.roles
```
roles | count
-- | --
NULL | 38
[ ] | 13
[ jobserver.authorization.roles.ProjectCollaborator ] | 8
[ jobserver.authorization.roles.ProjectCollaborator, jobserver.authorization.roles.ProjectDeveloper ] | 1

It is not currently clear:
* why the co-pilot does or does not have certain project roles or membership
* when the co-pilot became the co-pilot for a project and if this has ever changed (in most cases it is 4 weeks from project start but this isn't always a clear date and sometimes things change)

I believe in the cases where there is no roles or membership, co-pilots have been able to achieve their co-piloting activities using permissions granted via a global role they hold (on account of being a output checker, for example).

With the goal of improving our audit trail of who had what permissions for a project at what time and for what reason, I believe that we should:
* clarify what permissions a co-pilot requires for a project (e.g. editing project metadata, workspace creation, running jobs, viewing outputs)
  * and if these need to change throughout the project lifecycle (e.g. initial setup, supporting/debugging action development, publication checklist, project closedown)
* implement these permissions, and the co-pilot-to-project relationship through the existing `ProjectMembership` and `Role` structures such that they are appropriately added to the Audit Log as being present and necessary for the purpose of co-piloting.

**Comment by Jongmassey** [comment]
From @acagreen17 on [slack](https://bennettoxford.slack.com/archives/C068NDYALSF/p1725275873301009?thread_ts=1725262790.676429&cid=C068NDYALSF)
* only permission currently needed is to view released and unreleased outputs
* currently all copilots are output checkers, but may not always be the case

**Comment by inglesp** [comment]
It's not only co-pilots who may need permission to view unreleased outputs (but not run jobs).  For instance in the Developer Permissions Log, Chris has been given permission to view outputs but not to run jobs.

Supporting users being able to view outputs without being able to run jobs is a prerequisite for us turning off file-sync.

**Comment by Jongmassey** [comment]
Depending whether he needs to view unreleased or released files, the pre-existing [`ProjectCollaborator`](https://github.com/opensafely-core/job-server/blob/4ec94ffb4330aa0673d3d98a9a993e7c208f39c6/jobserver/authorization/roles.py#L97-L110) role may fit that bill

**Comment by Jongmassey** [comment]
Let's not do this right now:
* we don't yet have a clear definition of what permissions co-pilots need
* it's a big bit of work that we don't have capacity for right now
* we can revisit it in the context of aligning job server's `Roles` with real-world roles at a later point once the latter are well defined.
