### ISSUE TITLE
Pages with Redirect Error

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/job-server#4545]
Google Search console has highlighted the below pages as having redirect errors:

- https://jobs.opensafely.org/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1688/v23wauxcsoibbf6c/
- https://jobs.opensafely.org/datalab/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1718/
- https://jobs.opensafely.org/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1688/oe2a5smsfcrvh6aa/
- https://jobs.opensafely.org/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1603/
- https://jobs.opensafely.org/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/
- https://jobs.opensafely.org/datalab/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1688/oe2a5smsfcrvh6aa/
- https://jobs.opensafely.org/datalab/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1603/
- https://jobs.opensafely.org/datalab/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1688/v23wauxcsoibbf6c/
- https://jobs.opensafely.org/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1603/sqcfuzzbrcnhfkuu/
- https://jobs.opensafely.org/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/outputs/
- https://jobs.opensafely.org/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1603/aemwzevstck23ipl/
- https://jobs.opensafely.org/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1623/qzwhzgerbjfaoql4/

---

## Example request

```
❯ curl -I https://jobs.opensafely.org/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1688/v23wauxcsoibbf6c/
HTTP/2 301
server: nginx
date: Mon, 19 Aug 2024 09:53:16 GMT
content-type: text/html; charset=utf-8
location: /factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1688/v23wauxcsoibbf6c/
strict-transport-security: max-age=15724800; includeSubdomains
```

---

From Google docs ([source](https://support.google.com/webmasters/answer/7440203#multiple_redirects))

> ## Redirect error
> Google experienced one of the following redirect errors:
>
> - A redirect chain that was too long
> - A redirect loop
> - A redirect URL that eventually exceeded the max URL length
> - A bad or empty URL in the redirect chain

**Comment by Jongmassey** [comment]
Having taken a look at  https://jobs.opensafely.org/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/1688/v23wauxcsoibbf6c/ it appears that there are two redirects returned in the redirects middleware by:

```py
Redirect.objects.extra(
                where=["%s LIKE concat(old_url, '%%')"],
                params=[request.path],
            )
            .annotate(url_length=Length("old_url"))
            .order_by("-url_length")
```

one with an `old_url` of `/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination_wip-branch/` and the other with `/factors-associated-with-covid-19-vaccination/factors-associated-with-covid-19-vaccination-wip-branch/` (note the underscore and hyphen difference). The `first()` of these is taken, which happens to be the one with the underscore, whilst in this case the request path is the one with the hyphen.

This difference means that the following code block does nothing to the request url and thus a circular redirect is formed

```py
new_url = request.path.replace(
            redirection.old_url, redirection.obj.get_absolute_url()
        )
return redirect(new_url, permanent=True)
```

**Comment by Jongmassey** [comment]
Looking at the SQL query generated, the LIKE comparison here is the problem because the underscore is interpreted as a single char wildcard which matches both the `_` and `-` in the urls.
