### ISSUE TITLE
Remove `User.is_staff` and `User.is_superuser`

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#4590]
What's the purpose of `User.is_staff`? How does it relate to the `CoreDeveloper` role?

**Comment by mikerkelly** [comment]
From a quick look I think it does nothing and is a leftover from a time when we either used django.contrib.admin or intended to mirror some of its User fields and behaviours. We don't use that app now. I think we don't use is_user or is_superuser for anything and they can/should be removed. Detail:

In [django.contrib.admin](https://docs.djangoproject.com/en/5.1/ref/contrib/admin/#module-django.contrib.admin), [is_staff](https://docs.djangoproject.com/en/5.1/ref/contrib/auth/#django.contrib.auth.models.User.is_staff) allows a user to access the admin site and read models and view any custom views there (eg reports) but cannot create/update/delete models without further permissions. is_superuser users are given those permissions on all models.

We don't include django.contrib.admin in INSTALLED_APPS in job-server/settings.py, however.

References to is_staff in our job-server code:

```
templates/base.html:    <meta name="is_staff" content="{% if user_can_view_staff_area %}true{% else %}false{% endif %}">

jobserver/models/user.py:    is_staff = models.BooleanField(default=False)
jobserver/api/releases.py:            staff=user.is_staff,

tests/integration/test_auth.py:    assert not user.is_staff
tests/unit/jobserver/models/test_user.py:    assert su.is_staff
tests/unit/jobserver/api/test_releases.py:    token_login_user.is_staff = True
```

- base.html -- not used, should be removed.
- models/user.py -- defining the field.
- releases.py -- build_level4_user() -- but would only achieve something if any other code referred to this.
- tests -- of the above.

None of these appear to have any effect. Maybe at one time there was more code that referenced these but it has been removed without removing the fields. Or maybe we once used django.contrib.admin.

Note: this should be tested carefully if removed -- if this is all wrong, high potential impact! Perhaps some other installed app refers to these fields that I'm unaware of?

**Comment by mikerkelly** [comment]
Worth checking if the Airlock team/code would be affected by this -- they use this API for authentication.

**Comment by mikerkelly** [comment]
[This commit](https://github.com/opensafely-core/job-server/commit/17f3d4f191d0dc2a4d02d40dc275cc0513fd7def ) added these fields but they weren't used at the time, and we had already removed django.contrib.admin in #950. I've skipped around a couple of times in the repo and can't see that they've ever been used.

I looked in job-runner and airlock I see no reference to that string in either repo (except in [this JS assets file](https://github.com/opensafely-core/airlock/blob/main/assets/dist/assets/base-Bspn_4xV.js), which I think is not relevant, not completely sure)

I've asked in #team-rap if it affects them in any way.

**Comment by mikerkelly** [comment]
I further checked the history of this with:
`git log -G 'is_staff' --all --patch --stat --pretty=fuller > is_staff_log.txt`
... and have seen nothing that contradicts my previous comments. We can go ahead and do this, I think.

**Comment by iaindillingham** [comment]
Alas, `base.html` is a red herring. We use the same name, but for a different thing.

https://github.com/opensafely-core/job-server/blob/8656ca1c7e298d7d61a6d55a785085f7597aad83/templates/base.html#L26

Above, `meta.content` is unrelated to `user.is_staff`.[^1]

[^1]: https://bennettoxford.slack.com/archives/C069SADHP1Q/p1726647726439369
