### ISSUE TITLE
Replace `pragma: no cover` with a test

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#4593]
For expediency, #4574 added a `pragma: no cover`:

https://github.com/opensafely-core/job-server/blob/22f5abdc0bc2e4269fb9b214c037e22bcba7db83/jobserver/forms.py#L138

We should remove it and exercise the line with a test. It's worth taking some time to do so, as -- to me, at least -- it isn't clear how we might end up here, and what returning `None` from `WorkspaceCreateForm.clean` means.

**Comment by mikerkelly** [comment]
I don't think this block of code achieves anything after #4725 and #4730 remove the rest of `clean()`. I suspect it existed to try and avoid that code accessing attributes of `repo` or `branch` when either was not provided in `data`. This would have caused `branch.lower()` to fail, for example, even though `branch` being `None` would independently have failed field validation. `clean()` is executed even if field-level validation fails, to allow for fuller error reporting.

So I think `clean()` can be removed altogether if #4730 is approved and merged. Nice.
