### ISSUE TITLE
Review maintenance of `signing.py`

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/job-server#4602]
While looking at #4601, and searching around for `crypto` in the code to figure out where this was used, I noticed with `signing.py`:

* it's a copy-paste from code in release-hatch — [possibly the version](https://github.com/opensafely-core/release-hatch/blob/527fdc0c8c62cce67f04af1589aa3720e87c7ec5/hatch/signing.py) added in job-server commit 264a2671b69a71340f1b81909db274772e9a5780) — but isn't marked as such in the module (even though the upstream code now does have a [warning about this](https://github.com/opensafely-core/release-hatch/commit/693f35116b318b1a7c7634a849b38858e7fe897d))
* it's slightly out of date with respect to the upstream code, which has a [few additional commits](https://github.com/opensafely-core/release-hatch/commits/main/hatch/signing.py) since this code was copy-pasted, everything from [this commit](https://github.com/opensafely-core/release-hatch/commit/693f35116b318b1a7c7634a849b38858e7fe897d) onwards, I think
* because it's a copy-paste, it has a confusing comment about how `cryptography` is a "heavier" dependency than `itsdangerous` as a reason to not use `cryptography` — yet in job-server, we in fact use `cryptography` as a transitive dependency via `social-auth-core`

We could update the code to match the latest release-hatch upstream if it's sensible to do so, or at least pull in the comment of its origin.

**Comment by bloodearnest** [comment]
There is some more context here: https://bennettoxford.slack.com/archives/C069YDR4NCA/p1725554357114719?thread_ts=1725547669.768179&cid=C069YDR4NCA

Essentially, I think this file and any dependencies it requires (e.g. itsdangerous and pydantic) can likely be removed from job-server now that the Level 4 outputs-viewer is no longer needed.

The comment about cryptography dependency was in relation to release-hatch dependencies, not job-server's. release-hatch is not django, so we needed a signing library, and when with its dangerous.

**Comment by StevenMaude** [comment]
> The comment about cryptography dependency was in relation to release-hatch dependencies, not job-server's.

Yep, it totally makes sense there, just that it conflicts with the actual state of things here.

**Comment by Jongmassey** [comment]
AFAICT, [`sign`](https://github.com/opensafely-core/job-server/blob/56c13a2db1e29621c45c809f32272792ee82cd3d/jobserver/signing.py#L100-L103) is the only thing that's used in this, in `releases.build_hatch_token_and_url()`(https://github.com/opensafely-core/job-server/blob/56c13a2db1e29621c45c809f32272792ee82cd3d/jobserver/releases.py#L45-L62), which itself is used in the `WorkspaceBackendFiles` view. This strongly suggests this is something which has/soon will be replaced by airlock

**Comment by StevenMaude** [comment]
Looking too, I think Jon's assertion is correct.

From that, I believe `signing.py` and its associated tests would be removed as part of #4588, because #4588 proposes removing the `WorkspaceBackendFiles` view.

We could then add this as an item there and close this issue.

But I'll check with the RAP team that the removal of `signing.py` OK.

**Comment by StevenMaude** [comment]
Added removing this code as a task to #4588, which closes this issue; removal answers the question of the code's maintenance.
