### ISSUE TITLE
`CoreDeveloper` role might be mis-named

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/job-server#4604]
`CoreDeveloper` is used to grant access to the Staff Area

Many of those assigned the role are not _developers_ but other Bennett Institute staff.

Should this role be renamed to reflect this, e.g. `BennettStaff` or just `Staff`?

- [x] Decide on a new name, with NOD's input
- [x] Update codebase
- [x] Speak to NOD and IG, and others, so they update their documentation and processes.

**Comment by lucyb** [comment]
I've let NOD know that we're going to do this. They didn't respond, so I'm going to say that it's fine for us to go ahead.

**Comment by iaindillingham** [comment]
@Jongmassey or @lucyb, just to highlight that this issue has been closed (possibly automatically) but there's still one more thing to do...

> Speak to NOD and IG, and others, so they update their documentation and processes.

**Comment by mikerkelly** [comment]
When this is done we should also update the new joiner tech checklist (Bennett internal link: [here](https://docs.google.com/document/d/1U0GCsYTB3qar4m0eEBaXj_0Z7spAFnM3jYUy6IIzv3g/edit?usp=sharing)).
Not sure if there are any others out there in Google docs or elsewhere we might miss?

**Comment by mikerkelly** [comment]
(Bennett internal relevance and links):
I think [this Slack thread](https://bennettoxford.slack.com/archives/C068NDYALSF/p1728552952389019) and [this Google doc](https://docs.google.com/document/d/1bQUVf-v5qafokp0BW_uenYbkYF1MQf9d8IUZzwbrYHI/edit) mean that NOD are already updating the relevant process relating to this change. I believe the change was discussed with both NOD and IG around the time of the first PR towards this.

**Comment by benbc** [comment]
@Jongmassey This is marked as completed, but it looks like maybe the [team manual PR](https://github.com/ebmdatalab/team-manual/pull/890) has been left by the wayside.

**Comment by mikerkelly** [comment]
In Jon's absence I'm re-opening for the issue benbc mentions which I can review next.

I've also noted some further indirect references to CoreDeveloper that I've addressed in #4688.
