### ISSUE TITLE
Workspace creation: a validation error causes the github repo field to be reset

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#4618]
When creating a new workspace for a project, the GitHub repo field is reset when there is a validation error on form submission.

The other fields retain the values that have been entered, however the GitHub Repo field resets to the first item in the list. It's easy to miss that this has happened and not possible to change after the fact.

Steps to recreate:
1. Enter a workspace name with a space or a hypen
2. Enter a workspace purpose
3. Select a repo from the list
4. Click "Create workspace"

The form is refreshed with an error in the Workspace name, but all user entered values are the same, except for the GitHub repo.

![Screenshot from 2024-09-19 17-43-21](https://github.com/user-attachments/assets/3bd0bd37-9688-4626-ad62-77bab90c10f8)

Suggested fix:
1. Ensure the selected repo is preserved when the [clean_name](https://github.com/opensafely-core/job-server/blob/5baa27649eabd878fa63c53476d2bff23de84bce/jobserver/forms.py#L159) step fails in the form.
2. (Bonus) With a new form, default to selecting a blank value in the list, so that users always need to make a choice as selecting the first value by default is confusing.

**Comment by iaindillingham** [comment]
It looks as though[^1] this bug has caused a user to create a workspace that's incorrectly associated with the `.github` repo 🙁 

[^1]: https://bennettoxford.slack.com/archives/C06GRHZF295/p1727260170436519

**Comment by iaindillingham** [comment]
In today's standup, I said I thought I'd found the source of this bug:

https://github.com/opensafely-core/job-server/blob/01352d0b3c4e1b72fe048b8748509d812cd2858a/jobserver/forms.py#L129

On closer inspection, I hadn't.

**Comment by mikerkelly** [comment]
The repo and branch `ChoiceField` are constructed dynamically as they depend on the GitHub API. They also use our `form_select` component. This means the field construction needs to tell the template what the initial values should be -- the Django machinery does not automatically apply them to the bound field.

Addressed in #4682.

We could also do with tagging the [.github](https://github.com/opensafely/.github) repo as non-research, as it's confusing it shows up in the selector.
