### ISSUE TITLE
Simplify `jobserver.models.User`

### ISSUE THREAD

**Issue by mikerkelly** [opensafely-core/job-server#4627]
#4625 removed `User.is_staff` and `User.is_superuser` as no longer required. They were present as we once used `django.contrib.admin` but no longer do (instead having a completely custom staff app).

While working on #4625 I noticed some possible further simplifications to the `models.User` module. There are several more bits of code or peculiarities that may exist for historical reasons but are no longer required. Simplifying the module and using less custom-behaviour where appropriate would aid understanding and maintenance.

This might need breaking up into multiple issues. Possible changes to investigate:

* We could be better off extending `BaseUserManager`, as we extend `AbstractBaseUser`, rather than `UserManager` that is intended for managing `BaseUser`. The names are a little confusing here, careful.
    * This could remove the need to access the pseudo-private `super()._create_user`.
    * We may not need the `UserManager.create_user` behaviour around normalizing username and e-mail and hashing the password as we use social auth, but this needs investigation.
        * This might not be the case for Interactive users that enter e-mail as free text -- and enter a password(?). We are planning to remove Interactive, but may still need this for now. Or maybe not, if we're not creating any new Interactive users? To investigate.
* " TODO: rename `name` and remove the `name` property once all users have filledin their names"
	* Is `get_full_name` needed?
- We may be able to remove some or all of: 
	- the custom `UserQuerySet` for sorting
		- "TODO: remove this method in favour of `order_by(Lower("fullname"))` once all users have `fullname` populated"
	- custom `UserManager` -- as above. Could it be the default?
	- custom `create_user` -- could this be default, or at least be called `User.objects.create()` to be idiomatic?
	    - `get_or_create_user` -- if we do the above, is this function then needed or do we get it "for free" by the normal `User.objects.get_or_create_user` machinery?
	- ~~Separate email and username properties if these are always the same?~~
	    - email and username are distinct -- for social-auth users it's GitHub email vs GitHub username.
* There were several comments that I didn't understand or seemed out-of-date, inaccurate or unhelpful. Those included:
	* "Using a custom Model allows us to add extra fields trivially, eg Roles."
		* Obvious.
	* `UserQuerySet` docstring / TODO
	* "We cannot use get_or_create here because the create_user factory function is special, and does additional work when creating users." -- why can't the extra work be on User.create, then we would get it "for free" (would we?).
	* "PATs are generated for bot users.  They can only be generated via a shell so they can't be accidentally exposed via the UI."
		* Could this use a reference to more info about this functionality/bot users?
	* "single use token login"
		* Is it clear what this means?
	* "normally this would be nullable..."
		* It is now.

**Comment by iaindillingham** [comment]
@mikerkelly to break this into smaller issues.

**Comment by mikerkelly** [comment]
The [`UserManager` ](https://github.com/django/django/blob/stable/5.1.x/django/contrib/auth/models.py#L137) that our `User` model's manager extends provides the following functionality:
* `_create_user` function that ensures:
    * `username` is set.
    * email is normalized by [BaseUserManager.normalize_email](https://github.com/django/django/blob/stable/5.1.x/django/contrib/auth/base_user.py#L23C9-L23C24) to lowercase the domain.
    * username is normalized by [`GlobalUserModel.normalize_username`](https://github.com/django/django/blob/f59cdd00093338427acde555c9b687acc5ac67ea/django/contrib/auth/base_user.py#L162) to normalize unicode.
    * password is hashed.

A social-auth (GitHub) user doesn't need any of these steps.

On creating an Interactive User through the staff pages with e-mail "MixEdCaSe@eMaiL2.cOm" the resulting User in the DB has no `password` set and the `username` and `email` fields remain mixed-case. Attempting to enter an e-mail with unicode is rejected by the form. Moreover we're not actively creating Interactive users, and may remove the feature in the future.

Therefore I conclude that the `UserManager` special user creation behaviour is not needed and that the use of the custom manager, create, and the `get_or_create_user` can all be removed.

**Comment by mikerkelly** [comment]
A quick prototype showed that most of the troublesome code in the `User` model could just be removed and everything still worked fine with some minor tweaks. So instead of splitting this I've created PR #4698 with that and some other small improvements from this ticket or noted during that work.

The only outstanding thing from the description is this:
> " TODO: rename name and remove the name property once all users have filledin their names"
