### ISSUE TITLE
Remove redundant dependencies after removing L4 file viewer code

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#4661]
As a result of #4588 we can now remove:
- Pydantic
- itsdangerous

Pydantic may still be a requirement of the current version of the pipeline library. However, it's just been removed from there, so I think updating to the latest version means we should be able to remove it from Job Server too.

**Comment by StevenMaude** [comment]
#4664 removes `itsdangerous`. #4666 removes `pydantic`.
