### ISSUE TITLE
Consider adding end-to-end tests

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/job-server#4702]
We currently do not have any end-to-end (e2e) tests. If we should, then we should add them.

In #4701, the following note is proposed to be removed from `TESTING.md`. It's worth recording that note here.

> We don't currently have any end-to-end tests but with the upcoming addition of onboarding it's clear we need a way to test across multiple views.
> The expectation is that these tests will check user flows work as expected, eg "As a user who has not signed up before who has received an invite email I can…".  These tests would likely like Client instances.

**Comment by iaindillingham** [comment]
I'm not clear whether you're suggesting we add an end-to-end test, @StevenMaude, or discuss whether we should add an end-to-end test. If the former, then what end-to-end test should we add? If the latter, then where and when should we have the discussion?

As written, this issue isn't actionable; it's not clear what the person assigned to it should actually _do_. It would be great to make it actionable, such that it doesn't languish.

**Comment by StevenMaude** [comment]
That's fair.

Since we don't have end-to-end tests, but that developer documentation proposed to add them, it seems reasonable to discuss whether or not we *should* add them.

Primarily, I just didn't want to lose the note after the change in #4701.

> where and when should we have the discussion?

If adding such tests has not been a priority in three years (based on [the commit when the note was first introduced](https://github.com/opensafely-core/job-server/commit/ae2e03ce01390340733df0c1b4b5ea11148e6727)), maybe it's not important at all.

Or at least we can open another issue should we want to in future.

It would be good for someone to make that decision, nonetheless. For now, I'll stick in triage for discussion at planning. That may see this issue closed there and then.

**Comment by lucyb** [comment]
As a general idea, yes we should use e2e tests as part of our testing strategy. However, we should employ them as-and-when we will find them useful rather than spending ages retro-fitting a whole suite of tests. We could start by doing a spike of playwright, at some point, after identifying a specific e2e test that we want to write. We should create a ticket for that specific spike, rather than one general ticket about the approach so I'm closing this one.
