### ISSUE TITLE
Better Handle Errors on Workspace Creation

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#473]
When submitting an invalid form on the Workspace Creation page, the view re-renders the form with an error message and the previous field values pre-populated.  However, the branch selector is made after page load because it's based on the value of the `repo` field, which means resets to `main` or `master`.

We need to find a way to tell the JS that a selection was already made on that page.

**Comment by evansd** [comment]
Just came here to report this, but glad I checked first!
