### ISSUE TITLE
Add a "search by partial job ID" feature

### ISSUE THREAD

**Issue by evansd** [opensafely-core/job-server#493]
A non-urgent, nice-to-have.

The lack of copy-paste in the secure environment can make certain debugging tasks more difficult. I quite often make use of the fact that the first 4 or 5 characters of a job ID are generally long enough to get uniqueness but short enough that you can hold them temporarily in memory while re-typing them in the secure environment. This works for searching log files and most of the tooling I've added will accept partial job IDs for this reason.

However sometimes we want to go in the other direction by taking a job ID on the secure server and finding the corresponding job on the website. It would be useful to have some simple page which would let you type a partial ID and take you straight to the corresponding job (if there was an unambiguous match) or link to the possible matches if there are multiple.

**Comment by ghickman** [comment]
Do you think we should provide this for non-staff users?  I've been pondering about setting up an internal tools page of some sort…

**Comment by evansd** [comment]
I can't think of any reason a non-staff user would want this feature, but equally I can't think of any harm it would do. So I think it just depends on whether we have a natural staff-only tools place to put it.
