### ISSUE TITLE
Document required environment variables

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/job-server#607]
From speaking to Chris and Mike at Graphnet Health, they told me that: **external developers wanting to run job-server need to know the required environment variables**. Graphnet had to discover most of these variables themselves.

The developer documentation should include the required environment variables with the following details:

* how to generate or obtain values for variables
* what the values do
* examples of valid values might also help

List of variables that Chris documented internally for Graphnet:

```
ADMIN_USERS
DJANGO_SUPERUSER_USERNAME
DJANGO_SUPERUSER_PASSWORD
DJANGO_SUPERUSER_EMAIL
DEBUG
SECRET_KEY
GITHUB_TOKEN
GIT_ORGANIZATION_NAME
SOCIAL_AUTH_GITHUB_KEY
SOCIAL_AUTH_GITHUB_SECRET
DATABASE_URL
BACKENDS
DB_DIR
```

The [current dotenv-sample](https://github.com/opensafely-core/job-server/blob/6a4041d6414fee0e2060a892f76dfdee1673f3db/dotenv-sample) does not include all of these variables. The comments there are terse in their advice for getting appropriate details.

**Comment by StevenMaude** [comment]
Assigned @sebbacon on request for triaging purposes.

**Comment by StevenMaude** [comment]
(More generally, I think it would be helpful in our documentation that we do not assume much, or any, Django experience of developers attempting to run our code.)

**Comment by StevenMaude** [comment]
Looking again, some of the details are in [INSTALL.md](https://github.com/opensafely-core/job-server/blob/6a4041d6414fee0e2060a892f76dfdee1673f3db/INSTALL.md), but without an explanation of how to get the values,

**Comment by bloodearnest** [comment]
While it would be good to have, I'm not sure how much of a priority documenting these things is.

job-server is intended to be a centralised service, not a run your own. We should focus on getting job-runner easier to set up and install first, IMO

**Comment by ghickman** [comment]
I think there's some low hanging fruit to take away from this feedback:
* Add `BACKENDS` to `dotenv` sample with an explanation of how to configure it
* Add `DATABASE_URL` to `dotenv-sample` with an explanation that it has a default and a link to where to find possible options for it (eg we should _not_ try to cover all the myriad options it supports but copying Django's settings template by linking to relevant docs in a comment is 👌)
* Modify the docs for `ADMIN_USERS` to explain it's a list of Users, _which need to exist first_, *or* remove the need for this setting (something we've already planned to do)
* Be more explicit in the `GITHUB_TOKEN` docs around what it actually needs, a docs link to GitHub is probably the highest value here.

I agree these are all low priortiy fixes, and this should be an easy task for anyone to pick up as well.
