### ISSUE TITLE
Review hardcoding of OpenSAFELY details

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/job-server#608]
From Mike and Chris at Graphnet Health, Chris had to patch a couple of source files to use their GitHub organisation instead of `opensafely`.

* In `roles.py`, [this call](https://github.com/opensafely-core/job-server/blob/6a4041d6414fee0e2060a892f76dfdee1673f3db/jobserver/roles.py#L20).
* In `github.py`, [this function](https://github.com/opensafely-core/job-server/blob/6a4041d6414fee0e2060a892f76dfdee1673f3db/jobserver/github.py). 

This works, but maybe there's a better way of doing this already?

I also had a quick check and there are a few places where `opensafely.org` is referenced as of current main (6a4041d6414fee0e2060a892f76dfdee1673f3db):

```
jobserver/settings.py
195:    "MAILGUN_SENDER_DOMAIN": "mg.jobs.opensafely.org",

jobserver/templates/base.html
28:      if (document.location.hostname === "jobs.opensafely.org") {
32:        script.setAttribute("data-domain", "jobs.opensafely.org");
33:        script.src = "https://pa.opensafely.org/js/index.js";

jobserver/templates/job_request_detail.html
49:      <a href="https://docs.opensafely.org/security-levels/">security level</a> various outputs were written to. Outputs

jobserver/templates/index.html
10:      Welcome to the <a href="https://opensafely.org">OpenSAFELY</a> Jobs site.
16:      href="https://opensafely.org/principles/">Principles of OpenSAFELY</a> some Github

jobserver/templates/workspace_detail.html
42:  contact an <a href="mailto:team@opensafely.org">admin</a>.

jobserver/emails.py
23:        sender="notifications@jobs.opensafely.org",
42:        sender="notifications@jobs.opensafely.org",
```

Most of these are fine and don't break functionality for someone who would run our code in local testing.

The email details might be better supplied as configuration and not hardcoded, to make it easier to override. However, these only appear in a couple of places, so this doesn't feel too critical.

**Comment by StevenMaude** [comment]
Paging @sebbacon for triage.

**Comment by evansd** [comment]
It might be worth noting that the job-runner is _deliberately_ hardcoded to use only the `opensafely` github org. You can see the original discussion on this [here](https://github.com/opensafely-core/job-runner/pull/206#discussion_r627451272). Obviously that's not definitive but just to say that there might be wider issues at play here.

**Comment by StevenMaude** [comment]
That's useful; I hadn't seen that discussion @evansd.

An alternative to actually changing any code might be that we note some pointers on what an external developer needs to modify to run the code. That at least saves someone from having to debug themselves. Hopefully we'd never have too many hardcoded-specifics to override.

**Comment by ghickman** [comment]
Both `jobserver/roles.py` and `github.py` have already been dealt with (🎉) by attaching GitHub org names to OpenSAFELY Orgs and then looking them up for the User in the current context.  More work needs to be done here to support a User having 2+ orgs, but we considered this first pass good enough.

Email sending config is only used in non-DEBUG situations and I'm keen to not add too much more configuration there since local dev testing shouldn't touch it (we use the console email backend to avoid the need for relay credentials).

**Comment by StevenMaude** [comment]
@ghickman: feel free to close if you're happy with how things are here.

**Comment by ghickman** [comment]
@StevenMaude – I don't think there's any further actionable points here, thank you for taking the time to dig through this though! 🙌
