### ISSUE TITLE
Use Better Timings Labels

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#610]
The current labels for Job timings have led to some confusion, particularly when a Job is cancelled.

Take this cancelled Job: https://jobs.opensafely.org/jobs/nkwdbphyc34fnc57/

The timings section states that it "started" at a particular time, "finished" at another time, and had a runtime of 27 minutes.  We know from the job-runner logs that this was not actually the case.

Due to the way job-runner works (optimised in opensafely-core/job-runner#22) the flow goes something like this:
1. a JobRequest is seen
2. a Job is created and started_at populated
3. Job data is synced up to job-server
4. job-runner moves onto another Job
5. the second Job takes a long time to manage (this is commonly seen when there are large file transfers involved)
6. User requests the cancellation of a Job on job-server
7. job-runner spends several minutes still dealing with the second Job
8. job-runner sees the request to cancel, cancels the relevant Job
9. Job data is synced up to job-server

None of the steps here are incorrect in the design we created, however how we dispaly the outcomes to the user is.

Since started_at is more accurately the acknowledgement of a Job moving to the `pending` (or `running`) state we should label it `Acknowledged`.

Runtime is also confusing but we've yet to come up with a better label, however we know a Job has been cancelled when `status_mesage` has the value `Cancelled by user`.  We could expose an `is_cancelled` check on the Job object aid ease of use in the templates.

**Comment by sebbacon** [comment]
How about the following?

-----

At the top, to explain what the page is

<<action_id>>

This page describes a "job": a request initiated by a user for something to to be run on a secure backend.

----

## Timings

These timings represent interactions between the job and the secure backend.

Job created: 2 days ago
Job acknowledged by backend: 1 day, 21 hours ago
Job finished on backend: 1 day, 20 hours ago
Duration of job on backend: 00:27:22
This job last updated by backend: 1 day, 20 hours ago
