### ISSUE TITLE
Should Workspace Branches be Mutable?

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#719]
We've talked previously about allowing the branch for a Workspace to be editable.

Some reasons why that would be useful:
* Branch renames (particularly `master` -> `main`)
* Reusing of workspaces for new work

Some reasons why that could be tricky:
* new branch removes costly-to-compute L4-outputs from previous branch

Currently a Workspace is unique on its name, and conceptually captures a repo, on a branch, with a db.  However, the concept of different dbs hasn't really been used of late, and only exists on the TPP backend.  So typically discussions on this subject veer into "what is a Workspace anyway".  For the purpose of this change I think we need to address that question but also roll out a branch editing screen if only for admins to help with the first point for researchers.

**Comment by evansd** [comment]
In the mesolithic, when we came up with the term "workspace" the original idea was that it was basically just a "working directory" to put outputs in rather than something that represented, in any conceptual sense, a (repo, branch, db) combo.

We were even thinking of something a bit like a file explorer interface that would let you duplicate an entire workspace so you could do further investigative work on already extracted data in a new branch.

I'm not suggesting that's necessarily a good feature, or a good way to think about workspaces, but maybe useful context if you're pondering wider questions about workspaces.

**Comment by sebbacon** [comment]
Driving our original design decisions, we also wanted to be able to:

* say with some confidence "this is the code that produced these outputs"
  * and, related, "all these outputs were produced with the same code" (i.e. avoid output A being from one code state, and B being from another)
* allow different people to work on different ideas (i.e. branches) at the same time

The current solution doesn't really achieve any of those goals!

I think for the first bullet point, the right solution would be to surface the commits that produced each output in the UI (perhaps also showing branch name); and to highlight if they were produced by a consistent codebase/branches (or not). For example, there could be a noisy alert at the top saying "these outputs were produced by code written at different times". The alert could just be for project developers, and could give them a quick option for re-running all the actions prior to publication.

The second point was supposed to be supported by something like Dave describes. I now wonder if we should just continue with the "surface-it-in-the-ui" paradigm I just described. So:

* Allow branches to be changed
* Stop storing outputs in a per-branch folder; this info should be in the manifest anyway
* When outputs are generated by code in different branches, highlight that in a different way from when it's from different commit hashes

There's a lot more thinking to do about the right UI here (for example, there are some kinds of errors resulting from not running consistent code that are worse than others, i.e. transformation steps downstream of several analytics steps); I think the main thing is that we should strongly nudge people to re-run all actions downstream of a cohortextraction against the same commit prior to project publication, and therefore label non-consistent output sets with some sort of red/orange/warning indication.
