### ISSUE TITLE
Investigate Consolidating PrepareButton & PublishButton

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#723]
Both buttons are very similar in that they:
* are displayed based on the presence of a URL
* POST to the given API
* need `csrfToken` to be able to POST
* use React Query's `useMutation`hook to do the POST

We've taken a couple of very quick runs at consolidating them but an obvious abstraction didn't present itself so parking until we have a bit more time.

My working theory is pulling the mutation outside the button component would mean we could pass it and an onClick handler in as a prop.

**Comment by tomodwyer** [comment]
We should also consider:

- whether it is worth creating a generic `<Button />` component, which can be extended for use in forms, and in this situation
- if we should build a container component for displaying the buttons
- if it should be one button (with varied props) or two buttons
