### ISSUE TITLE
Create a workspace and add to an existing project

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#734]
Harriet from LSHTM wanted to create a workspace and add it to an existing project (opensafely/documentation#346). There isn't a button, so I've suggested she visits `/new-workspace/` relative to the project URL. This worked for @Jongmassey ([thread](https://ebmdatalab.slack.com/archives/C31D62X5X/p1627292128212200)), but we feel there might be a permissions issue.

**Comment by ghickman** [comment]
Fixed in #722
