### ISSUE TITLE
Add an Inspector for Staff-only Tooling

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#737]
We have a handful of pages which are only for privileged staff users.  Currently they're linked to in the main menu, with no real distinction over the rest of the menu (there's a separator).  We're expecting to add more pages like this over time as the project expands and we need more tooling to support users.

The model I've used for this before was an "inspector", which is "a tailored Django admin" where pages are built around the concepts you need in the site (eg for us Backends and Users currently).

Let's pull the pages into a new Django app, with a URL namespace of `inspector`, and URL prefix of `/inspector/`.

We can link to the inspector in the drop down menu below a Users avatar, although if that gets annoying we could also link to it above the current menu with a different colour so it's obviously a different section and doesn't interfere with screenshots.

**Comment by sebbacon** [comment]
Bit unclear about the terminology, and worried that means I misunderstand! Why "inspector" - what are we inspecting here?

When you say "tailored Django admin" you mean literally using the Django Admin interface?

Thanks!

**Comment by ghickman** [comment]
> Why "inspector"

"inspector" is just the name I and previous colleagues called the concept, I guess because we're inspecting objects (where objects covers both Django Models and also cross-model concepts).  We wanted to not have it be an "admin" so as not to confuse ourselves between it and the Django Admin (which we're still tied to in job-server for the short term).

> using the Django Admin interface?

Definitely not the Django admin.  These would be pages built around various objects/concepts (eg Users or Backends which you can already use on the live site) with tooling built around managing those things, or related things (eg cancel all Jobs for a JobRequest).  We already use a bit of this concept in our JobRequestDetail and JobDetail pages where you're looking at the $thing and have various bits of information for debugging and controls.  This differs from the Django Admin which is tied to being either directly working with a given Model (rather than potentially a conceptual object) or performing actions across a user selected number of objects.

Previously I've also had the page which lives at `/inspector/` be a search page for jumping to objects quickly, so ours might let us jump to a partial Job[Request] ID, User, Backend, Snapshot, Workspace, etc.  The core concept is to enable faster management of the site by staff.

**Comment by bloodearnest** [comment]
I'm a fan of putting things like this, that have broad admin privileges, behind a different domain and login if possible e.g. https://staff.opensafely.org w/Google SSO auth, IP/DNS ideally only accessible over VPN.

It removes the chance that a regular user can accidentally (via bug or human error) be promoted to an admin level, as the two are separate authentication mechanisms.

IDK how well this plays with django. It could be a parallel deployment, using the same DB maybe.

**Comment by sebbacon** [comment]
All sounds good. I would be interested in bikeshedding a name other than `inspector`!

:+1: to @bloodearnest's suggestion, too

**Comment by ghickman** [comment]
> I would be interested in bikeshedding a name other than inspector!

🍿

---

I'd have to look into how we might go about setting up a separate domain and auth mechanism.  I can vaguely imagine how some of the pieces might fit together (different auth backend, maybe even a different user), but a spike into this would be useful.

But I don't think that should gate access to starting to add these pages because currently the pages are replacing me hand editing the database, baby steps, etc.

**Comment by sebbacon** [comment]
I think the different domain thing should be pretty easy - [here's an approach using a "vhosts" middlewere](https://www.valentinog.com/blog/django-vhosts/) that looks perfectly adequate.

We could still use the same auth backend for the admin app; it's just the admin app would additionally require access over tailscale (@bloodearnest I can see what you're up to!) by checking certain headers or tokens provided by tailscale.

**Comment by ghickman** [comment]
> should be pretty easy

I've used Django's sites contrib app extensively, a similar tool for the same outcome, it's not great to work with for various reasons and we really don't need that level of complexity for this.  The project is tied to a single base domain in various places and based on past experience we would be much better off with a second deployment and some more env-var based config options.

> admin app

In all seriousness, this is exactly why we named it "inspector"!  The "admin app", or really anything to do with "the admin" is so completely owned by the Django Admin that it nearly always causes confusion.  I'm really against calling it an admin here, we already have enough naming problems with this project and job-runner.

Separately, it's not necessarily for _admins_, which we don't really have a concept of here (CoreDeveloper is our closest role), and I'd like to lean into the roles and permissions framework where we can to open bits of it up to various staff.

> same auth backend

Not as it currently stands, the auth backend is tied to one OAuth app by design, which is tied to a single domain on GitHub's side.

---

I think we're getting off piste with naming and deployment ideas though.

Currently I hand edit the production database for certain tasks, I would like to stop doing that.  We need more staff-only pages to avoid doing that.  We already have a few staff-only pages, but they're oddly mixed in with the normal pages (both URL-wise and visually), so lets have them separated:
* into an app in the code base
* with a base template to make it clear you're on an admin page
* with obvious URLs

Once those basics are in place lets definitely look at the other bits.

**Comment by evansd** [comment]
> I'm a fan of putting things like this, that have broad admin privileges, behind a different domain and login if possible

I definitely get the reasoning behind this and it's good to know this has worked for @bloodearnest in the past. Just to throw in one opposite piece of anecdata that I remember working with a startup which had adopted this approach and the parallel deployments and additional codebase complexity caused quite a few issues and I ended up having to unpick it all.

That's definitely not to say we shouldn't do it. But I think it needs some careful forethought and a bit of discipline to keep it all under control.

> I think we're getting off piste ... Once those basics are in place lets definitely look at the other bits.

:100:

**Comment by sebbacon** [comment]
All good with me. My one request is if we could use something like "admin" or "manage",  rather than "inspector"?

**Comment by ghickman** [comment]
@sebbacon – do you have any suggestions for a name that don't include the word "admin"?

I'm really not sure the name "inspector" will have any problems, this is a staff only tool (currently only 5 of us would have access to it), and it does gel fairly well with what the tools purpose is.  Most importantly, it's a name that's not already in use by any other tool or process we have, a seemingly hard goal to achieve!

**Comment by sebbacon** [comment]
:+1:   to "staff"
