### ISSUE TITLE
Status page times are in UTC not local tz

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/job-server#740]
Made me think things had stalled before I refreshed a couple of times and saw it updating. 

Maybe change  https://github.com/opensafely-core/job-server/blob/main/jobserver/models/stats.py#L20 to `self.api_last_seen.strftime("%Y-%m-%d %H:%M:%S %Z")`  ?

**Comment by ghickman** [comment]
Thanks for taking a run at this, we really need to address display of all times.  I'm hoping to get to it before BST finishes so it's more obvious when I get it fixed!

Closing in favour of #451
