### ISSUE TITLE
Turn on WAL Mode

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#865]
We've been seeing some intermittent [Database is locked](https://sentry.io/organizations/ebm-datalab/issues/2489593003/?project=5443358&query=is%3Aunresolved) errors in Sentry.

I couldn't track them down to anything in particular but came across [this article from SimonW on turning on WAL mode to alleviate the error](https://til.simonwillison.net/sqlite/enabling-wal-mode), and [SQLite's WAL docs](https://www.sqlite.org/wal.html) suggest that the downsides shouldn't affect us.

@bloodearnest @evansd @inglesp – as the SQLite stans, does this seem like a good idea?

**Comment by sebbacon** [comment]
So is this the correct list of tasks?

* Change deploy process to create a backup (how? Online Backup API documentation is a bit... dense...) before each deploy, for manual rollback goodness
* Turn on WAL mode
* Set up some kind of alert or reminder to monitor if the locked errors decrease over time
* Report back here

**Comment by bloodearnest** [comment]
To perform the backup: `sqlite3 /path/to/db.sqlite ".backup /path/to/backup.sqlite"`.

I'd suggest including at timestamp in the backup filename.

**Comment by evansd** [comment]
I've created a one-off backup (using the online backup API) and enabled WAL mode and it all seems to be working OK.

I couldn't find an obvious pre-deploy hook to hang a backup command off though.

**Comment by bloodearnest** [comment]
Might also let us move some of this out of the entrypoint: https://github.com/opensafely-core/job-server/blob/main/entrypoint.sh#L5

**Comment by sebbacon** [comment]
WAL mode is now on. Leaving backups for a different ticket
