### ISSUE TITLE
Trial Template-based Component Library

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#922]
All our HTML forms are currently written out in long form in their respective page templates.  This was to avoid the difficulty of styling and debugging the HTML generated from Django and the various form libraries which exist for it, sticking to the [Locality of Behaviour principle](https://htmx.org/essays/locality-of-behaviour/).  We'd like to factor out individual form inputs, with labels, and per-field error displays for reuse.  These inputs would cover the 80% use case, taking a Django Form field instance as part of the include, eg `{% include 'text_field.html' with field=form.name %}`.

We're worried our attempt at factoring these out will end up in the same so as a spike we'll pick 3 types of field:
* a text input, eg ProjectCreate's name field
* an email input, eg UserSetting's email field
* a roles picker (multiple select checkbox), eg ProjectMembershipEdit's roles field

**Comment by sebbacon** [comment]
I like the way that link describes the tradeoffs. What it makes clear is that to benefit from the LoB principle (which I agree is super important in forms), we need to accept a lot of copy-and-paste and cross-cutting concerns.

By factoring out we're moving the tradeoffs nearer the centre; I guess the question is how we monitor where the right balance lies. Let's review the spike with that in mind!

**Comment by ghickman** [comment]
Initial version of this merged in #935

**Comment by ghickman** [comment]
First bug: the ProjectCreate page skipped the `name` kwarg resulting in a form which didn't submit anything Django could use.

I'm not sure how we can require the correct kwargs and trivially test that they're always called in the correct way.

**Comment by ghickman** [comment]
Big thanks to @tomodwyer for finding [slippers](https://pypi.org/project/slippers/) and building this idea out 👍
